### ISSUE TITLE
Misalignment in issues page when page scroll down   

### ISSUE THREAD

**Issue by baladkb** [gitlabhq/gitlabhq#10007]
Hi, 
I am using Git-Lab, I'm facing one issue in Desktop Mode{I'm using windows 8 }, 

In issues page > open any issues and we see the right side bottom many Labels(Assignee, Milestone, Labels, Cross-project reference, participants, Notifications), we scroll down and see Notifications Label means that entire portion got misaligned.

For Your Reference we attache the screen shot :       
![git-lab](https://cloud.githubusercontent.com/assets/4152211/12605166/5ee6b17e-c4e8-11e5-9cfa-818d8baf6d1e.png)

**Comment by rymai** [comment]
Hello @baladkb and thanks for your report,

- What's your version of GitLab?
- Can you reproduce the problem on GitLab.com, for instance with this issue?: https://gitlab.com/gitlab-org/gitlab-ce/issues/12762

I cannot, see for yourself:
![screen shot 2016-01-27 at 09 32 22](https://cloud.githubusercontent.com/assets/1168/12607945/fc74d8fe-c4d8-11e5-939b-8b1cf989d4aa.png)

I think this got fixed by the 8.4 release: https://about.gitlab.com/2016/01/22/gitlab-8-4-released/

**Comment by baladkb** [comment]
We are using GitLab 8.3.0
Thanks @rymai

**Comment by rymai** [comment]
You're welcome @baladkb. I will close this, if you ever happen to reproduce it on 8.4, please open a new issue on the GitLab.com issue tracker as we try to centralize all GitLab issues there: https://gitlab.com/gitlab-org/gitlab-ce/issues

**Comment by baladkb** [comment]
Ok Thanks @rymai

**Comment by baladkb** [comment]
Thanks @rymai, this is working fine with Git-Lab 8.4.
