### ISSUE TITLE
Number of like visible on merge requests list

### ISSUE THREAD

**Issue by thyagorafaell** [gitlabhq/gitlabhq#10069]
In my company, we use the number of likes to decide if the request would be approved or not.
It would be nice if we had the number of likes/thumbs up of our merge request visible in merge requests list.

![Suggest](https://cloud.githubusercontent.com/assets/3964505/13529843/012bd05a-e1fd-11e5-8d40-7c5546b2066c.png)
It can be placed next to the comments counter.

All the best,
Thyago.

**Comment by diogocavilha** [comment]
Great.
I'd like to have this feature too.

**Comment by carlospaulischen** [comment]
Good idea!

**Comment by rymai** [comment]
@thyagorafaell @diogocavilha @carlospaulischen This is possible since GitLab 8.5 (you can even sort by "Most popular" / "Last popular": https://gitlab.com/gitlab-org/gitlab-ce/merge_requests?assignee_id=&author_id=&label_name=&milestone_title=&scope=all&sort=upvotes_desc&state=opened

See the announcement: https://about.gitlab.com/2016/02/22/gitlab-8-5-released/

**Comment by diogocavilha** [comment]
Good to know! Thank you a lot.

**Comment by thyagorafaell** [comment]
Thak you @rymai, we will check it
