### ISSUE TITLE
Upgrader script check postgres pg_trgm

### ISSUE THREAD

**Issue by scottix** [gitlabhq/gitlabhq#10102]
I don't have the log file but when I upgraded Gitlab with the upgrader script to 8.6.0 the database migration failed because of missing pg_trgm extension.

It would be nice to have a check to tell the user to install the correct package and to install the extension and I also noticed I couldn't find a way to just rerun the upgrader so I had to do it manually.

Having a way to force the upgrader script regardless of if it thinks it completed would be nice. Maybe there is a way but I didn't see any documentation.

**Comment by axilleas** [comment]
Please don't use the upgrader script, it's no longer maintained and you're practically on your own. Also, the postgres change was announced in the release blog post under the Upgrade barometer section, and we provided documentation in the update guide `8.5-to-8.6` as well.

I'm gonna close this as it seems your issue is resolved :)
