### ISSUE TITLE
validate schema after calling `beforeCreate` 

### ISSUE THREAD

**Issue by jurajsimbs** [gitlabhq/gitlabhq#10358]
model schema needs to be validated after `beforeCreate` hook, not before it.
We might have some mandatory fields like this:
```
schema: {
                //..............
                unique_identifier: {
                    type: DataTypes.STRING,
                    allowEmptyValue: false,
                },
                //..............
}
```
but don't want to insert them via `.create` method - but compute them in `beforeCreate` hook

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
