### ISSUE TITLE
gitlab commit的图片内容为空 Version:	8.5.12

### ISSUE THREAD

**Issue by njqaaa** [gitlabhq/gitlabhq#10353]
![pic-error](https://cloud.githubusercontent.com/assets/5145656/15603343/ba71ee3e-242c-11e6-9e16-a9edb800bbd9.jpg)

直接访问http://10.48.160.93/njqaaa/zzzz/blob/master/zx.jpg 图片返回是200 不过内容为空

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
