### ISSUE TITLE
fatal: The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by nileshadiyecha** [gitlabhq/gitlabhq#10367]
I am facing the below issue while push the code to the git.

error: RPC failed; result=22, HTTP code = 413
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
