### ISSUE TITLE
GPG signature verification

### ISSUE THREAD

**Issue by cyberhck** [gitlabhq/gitlabhq#10360]
Any plans on GPG signature verification? We could just add a GPG public key to server, then verify the commit using `git verify-commit <commit>` and display if it's a good signature, shouldn't take much time. I would like to give it a try if I could this working on my machine :)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by connorshea** [comment]
Relevant GitLab issue is here: https://gitlab.com/gitlab-org/gitlab-ce/issues/4232
