### ISSUE TITLE
Default group visibility error!

### ISSUE THREAD

**Issue by takeseem** [gitlabhq/gitlabhq#10378]
Thanks for your help!

- Admin Area/Settings
  Default group visibility：Set to Private
- Admin Area/Create group
  Visibility Level ：default is Public

Gitlab version: 8.10.1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
