### ISSUE TITLE
git-http-push failed

### ISSUE THREAD

**Issue by jxva** [gitlabhq/gitlabhq#10374]
git-http-push failed #10369, The problem still exists in the gitlabhq-8.10.0 version, tks.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
