### ISSUE TITLE
Connection refused via launchd.plist execute “pod repo push spec --verbose”

### ISSUE THREAD

**Issue by ybma-xbzheng** [gitlabhq/gitlabhq#10371]
When i manually execute “pod repo push spec”，everything is ok.
But when sleep my mac，and use launchd.plist execute the command timing,i received error:
```
Pushing the `spec' repo
ssh: connect to host gitlab.company.domain port 10022: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
