### ISSUE TITLE
external_url port will not be used if you save/update entries

### ISSUE THREAD

**Issue by andreasunterhuber** [gitlabhq/gitlabhq#10375]
With update to 8.10.0 and have problem with external_url and port:
external_url port will not be used if you save/update entries
Saving works, after update/save it will redirect to host WITHOUT port added in "external_url"

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
