### ISSUE TITLE
cant comment

### ISSUE THREAD

**Issue by kessanro** [gitlabhq/gitlabhq#10383]
i tried to comment on something but it wont letme i tired again reload diffrent browsers NOTHING
does that mean my acccount is blocked from commenting

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
