### ISSUE TITLE
can't list all deploy keys of other projects

### ISSUE THREAD

**Issue by lazywhite** [gitlabhq/gitlabhq#10380]
I add a deploy key for Project A ,  but when I setting deploy keys from Project B,  It didn't list the key pre-defined

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
