### ISSUE TITLE
Deliver gravatar data as HTTPS (again)

### ISSUE THREAD

**Issue by R1kk3r** [gitlabhq/gitlabhq#10390]
Hi all,

I am using gitlab behind a Nginx reverse proxy which handle HTTPS and redirect traffic to the real gitlab server over HTTP. 

When gravatar option is activated, my browser complains about part of the page not being securely delivered. With my friend Google, I found this old issue https://github.com/gitlabhq/gitlabhq/issues/690. I set up the X-Forwarded-Proto header without any success. Regarding the new code of GravatarService, it appears that the gravatar link is based on the gitlab config (https or not) instead on the request.

Any idea on how to get back the old behavior?

Thank you !

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by vsizov** [comment]
@jvanbaarsen I guess this issue is still exist since it's created 2 hours ago :)))

@R1kk3r Could you re-create issue here https://gitlab.com/gitlab-org/gitlab-ce/issues ?

**Comment by jvanbaarsen** [comment]
@vsizov This is a copy-paste answer.I close all issues within a hour when they are opened here. As discussed with the team :)

**Comment by R1kk3r** [comment]
@vsizov Done ;-)
