### ISSUE TITLE
Repository stuck at importing

### ISSUE THREAD

**Issue by ashutoshvct** [gitlabhq/gitlabhq#10397]
I was using Bitnami AMI on AWS. When i tried to import git repo by url, it is stuck at importing. It's been like 24 hours, still importing.
I have installed runner on the same host. 
Sometimes while the runner is running I cannot open .yml file for CI.

**Comment by Wachiwi** [comment]
The gitlab team is closing the github issue tracker. You need to submit your issue at [gitlab.com](https://gitlab.com/gitlab-org/gitlab-ce).

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
