### ISSUE TITLE
Mysql2 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by Uni9k** [gitlabhq/gitlabhq#10480]
I modified the default database to mysql

gitlab10.5.0 centos7.2 mariadb10.1

How can i fix this error?thx~
------
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_lfs_file_locks_on_project_id_and_path` USING btree ON `lfs_file_locks` (`project_id`, `path`) 
/opt/gitlab/embedded/service/gitlab-rails/config/initializers/connection_fix.rb:20:in `execute'
/opt/gitlab/embedded/service/gitlab-rails/config/initializers/mysql_ignore_postgresql_options.rb:23:in `add_index'
/opt/gitlab/embedded/service/gitlab-rails/config/initializers/mysql_set_length_for_binary_indexes.rb:15:in `add_index'
/opt/gitlab/embedded/service/gitlab-rails/db/schema.rb:960:in `block in <top (required)>'
/opt/gitlab/embedded/service/gitlab-rails/db/schema.rb:14:in `<top (required)>'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:52:in `block (3 levels) in <top (required)>'
/opt/gitlab/embedded/bin/bundle:23:in `load'
/opt/gitlab/embedded/bin/bundle:23:in `<main>'

Caused by:
Mysql2::Error: Specified key was too long; max key length is 767 bytes

**Comment by mkozono** [comment]
Unfortunately MySQL is not recommended, or officially supported in CE, so the first suggestion is to migrate to PostgreSQL if possible.

Otherwise, you should be able to modify your DB to accommodate the long index. Please see these related issues:

https://gitlab.com/gitlab-org/gitlab-ce/issues/43591
https://gitlab.com/gitlab-org/gitlab-ce/issues/26268
https://gitlab.com/gitlab-org/gitlab-ce/issues/35223
https://gitlab.com/gitlab-org/gitlab-ce/issues/41483
