### ISSUE TITLE
Issue Search not case-insensitive

### ISSUE THREAD

**Issue by Philzen** [gitlabhq/gitlabhq#3108]
Running gitlab 4.2 under ruby 1.9.3p392 against a postgres database.

Test: Enter `app` in the Search Field.  
Expected behaviour: All my issues containing `App` or `app` will be displayed 
Observed behaviour: Only Issues containing the exact matching case show up

Not sure if it's only my installation or if this is a general problem.

**Comment by samskiter** [comment]
Hi there, can't find this bug on gitlab issue list. it's still broken for us in GitLab 7.6.2 16f0968

**Comment by ivilata** [comment]
Also biting us hard with in GitLab-CE Omnibus 7.8.4.

**Comment by randx** [comment]
Can someone tries it with 7.9.0 when released and give a list of pages where we still have case-sensitive search

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by pietsch** [comment]
On a GitLab 7.13.0 source instance with PostgreSQL 9.1.16, a comment containing the string “BibTeX” is not found when I search for “bibtex”.

**Comment by randx** [comment]
@pietsch thank you. I made a fix - https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1174
