### ISSUE TITLE
GitLab 5.1: rake import brings empty project

### ISSUE THREAD

**Issue by sroth80021** [gitlabhq/gitlabhq#3693]
Using GitLab 5.1 and following the rake import help, when I:
1) place my bare repository in the repositories directory as configured in config/gitlab.yml
2) run the import task -- bundle exec rake gitlab:import:repos RAILS_ENV=production

Even though the bare repository was not empty, the repository is imported as an empty repository.   No error was reported by the gitlab:import:repos tool.    The empty repository is confirmed when I run gitlab:check, which says the 'repository is empty'.

import command output:
bundle exec rake gitlab:import:repos RAILS_ENV=production
Processing a.git
 * Created a (a.git)
Done!

While this ran, the production log said:
Connecting to database specified by database.yml
Creating scope :opened. Overwriting existing method Issue.opened.
Creating scope :closed. Overwriting existing method MergeRequest.closed.
  Rendered notify/project_access_granted_email.html.haml within layouts/notify (1.3ms)
  Rendered notify/project_access_granted_email.text.erb (0.3ms)
Sent mail to admin@local.host (176ms)

And the sidekiq log said:
2013-04-23T20:09:35Z 7310 TID-onsc8 GitlabShellWorker JID-8622acbf78ef3b2f1d4fb837 INFO: start
Initialized empty Git repository in /scratch/git/repositories/root/a.git/
2013-04-23T20:09:35Z 7310 TID-onsc8 GitlabShellWorker JID-8622acbf78ef3b2f1d4fb837 INFO: done: 0.468 sec
2013-04-23T20:09:49Z 7310 TID-onsc8 Sidekiq::Extensions::DelayedMailer JID-50883b71e51e95f93b3a666a INFO: start
2013-04-23T20:09:49Z 7310 TID-onsc8 Sidekiq::Extensions::DelayedMailer JID-50883b71e51e95f93b3a666a INFO: done: 0.205 sec

I am able to successfully import via the browser 'new project' page, accessing a http URL.  This leads me to conclude the issue is somewhere specific to the rake import call path.

Also, potentially related -- once the import of the repository has finished, I am unable to transfer it outside of the Administrator namespace -- in the browser, I get the error: 'Cannot move project' -- no error was logged in either the production log or the sidekiq log.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by larlin** [comment]
@Razer6 I think I still got this bug in GitLab 7.11.2 dac18e7.

I have a number of bare repos that was created with gitorius. I have a new git lab installed from the debian repo and then manually updated with the .deb as described [here](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/567).

I run gitlab-rake gitlab:import:repos as root and it creates a empty repo in the first owned by the first admin user.

The output is:

    Processing meexplorer.git
     * Created meexplorer (meexplorer.git)
    Done!

And I can't find anything relevant in the logs.
