### ISSUE TITLE
gitlab 5.2 - network graph - circle hover box with long commit message overlaps with commit hash

### ISSUE THREAD

**Issue by vemod** [gitlabhq/gitlabhq#4025]
in some cases long commit messages overlap with commit hash in the box showing up on mouse over a commit point.

![commit-msg](https://f.cloud.github.com/assets/4331256/546201/490105e2-c286-11e2-9ac2-f709470e0637.jpg)

also if branch has multiple tags it overlaps with date column. (was fixed but still there are cases when it persists)
![tag-overlap](https://f.cloud.github.com/assets/4331256/546213/00e10d1a-c287-11e2-8bf5-0f14ad3c2ee7.jpg)

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
