### ISSUE TITLE
[error 500] Cannot delete project, info says repository does not exist and owner deleted

### ISSUE THREAD

**Issue by stetskevych** [gitlabhq/gitlabhq#4370]
GitLab 5.2.1 6a868a4

![gitlab-cant-delete-project1](https://f.cloud.github.com/assets/835270/686453/e8ee1398-da59-11e2-99c9-b2210f3e61bd.png)

I created a test user, then he created a test project.
Then I removed the test user from the project and I also moved the project to the '/' namespace.
Then I deleted the test user from gitlab.
Trying to delete the test project now, I get the following log entry:
```
Started DELETE "/test-project" for at 2013-06-21 12:47:59 +0300
Processing by ProjectsController#destroy as HTML
Parameters: {"authenticity_token"=>"XIGFPDYMGzvlIc7muVtcJX1Rjj1fSSx0OsS+/HMD7mg=", "id"=>"test-project"}
Completed 500 Internal Server Error in 53ms
NoMethodError (undefined method `name' for nil:NilClass):
app/services/system_hooks_service.rb:30:in `build_event_data'
app/services/system_hooks_service.rb:3:in `execute_hooks_for'
app/observers/system_hook_observer.rb:9:in `after_destroy'
app/controllers/projects_controller.rb:75:in `destroy'
```
And here's the output of checks:
```
root@git:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
Checking Environment ...

Git configured for git user? ... yes
Has python2? ... yes
python2 is supported version? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.4.0 ? ... OK (1.4.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
post-receive hook up-to-date? ... yes
post-receive hooks in repos are links: ... 
Repo1 ... ok
Repo2 ... ok
Test project ... repository is empty

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes

Checking Sidekiq ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
Projects have satellites? ... 
Repo1 ... yes
Repo2 ... yes
Test project ... can't create, repository is empty
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.7.10)

Checking GitLab ... Finished
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
