### ISSUE TITLE
Empty link to Merge Request when Merge Request title is a reference to an Issue

### ISSUE THREAD

**Issue by opotemkin** [gitlabhq/gitlabhq#4627]
in Merge Request:
if number task is used in the name Merge
![bug](https://f.cloud.github.com/assets/1541100/846565/b252ecc4-f416-11e2-874c-674c07e61852.jpg)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
