### ISSUE TITLE
After deleting original project, visiting a merge request throws error 500

### ISSUE THREAD

**Issue by bertjwregeer** [gitlabhq/gitlabhq#4909]
The following steps can be used to reproduce the issue:

1. Create a project with User A
2. Fork the project with User B
3. User B makes changes to forked project
4. User B requests merge from User B's fork to main project
5. User A closes the merge request as invalid
6. User B deletes their fork
7. Visiting the previously created merge request causes Error 500.

Expected behaviour:

That on step 7 the user is able to see the previous merge request.

---

This is also an issue on other pages, when the user visits his personal merge requests page http://host/dashboard/merge_requests and clicks "closed", an error 500 is thrown as well.

I am unable to get access to the logs at the moment, but when I get them I will make sure to add them as an addendum to show a backtrace.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
