### ISSUE TITLE
Viewing branch with .json in the name will 404

### ISSUE THREAD

**Issue by jsternberg** [gitlabhq/gitlabhq#5244]
This is similar to issue #3132. If you push a branch that ends with the name ".json", such as "package.json", then viewing the branch will fail.

So if you added a package.json branch to gitlabhq and pushed it, the following URL would fail: `http://gitlab.org/gitlabhq/gitlabhq/branches/package.json`.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
