### ISSUE TITLE
Wrong user auto-commenting on a commit when other commit mentions this

### ISSUE THREAD

**Issue by mecp** [gitlabhq/gitlabhq#5690]
One commit SHA is mentioned in some other commit, then I guess some automatic comment is made on referenced commit that it has been mentioned in this commit. 

But the user using which that comment is made is wrong. I don't know who should be the correct user for this auto-comment but as of now it is using completely wrong user who is not even member of the project.

To reproduce this, you can mention SHA of some other commit in the new commit and it should reproduce this. 

In my case user is not even member of the project.

**Comment by Razer6** [comment]
This merge request has been closed because a request for more information has not been reacted to for more than 2 weeks. If you respond and conform to the merge request guidelines in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#pull-requests) we will reopen this merge request.
