### ISSUE TITLE
Web/System hooks not retried if remote server returns non-200 error code.

### ISSUE THREAD

**Issue by bladealslayer** [gitlabhq/gitlabhq#5768]
It seems that executing Web and System hooks ignores the return code of the remote server. As a result a hook calls with return code 4xx or 5xx from the remote server are considered successful and not retried.

See https://github.com/gitlabhq/gitlabhq/blob/master/app/models/web_hook.rb#L31.

Perhaps if the return code should be checked and exception raised on non-200 return code?

I can submit a PR, if you think this is the right way to go, @randx.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
