### ISSUE TITLE
CommitDate order incomplete after git rebase in merge request view

### ISSUE THREAD

**Issue by jmuulo** [gitlabhq/gitlabhq#5832]
CommitDate order is sometimes incorrect after a git rebase when viewed in gitlab merge request view. It appears as if the CommitDate ordering does not always match the git log if there are commits with same date stamp.

To reproduce:

Rebase a feature branch so that commit date of several commits becomes identical. Create a merge request. Open the merge request in gitlab.

Expected: The commits with the same date stamp appear in the order they are applied.

Observed: Commits with identical CommitDates are ordered by some other factor (sha1?) than their original commit order in git log. An edit to a function may appear bottom ('earlier') and the addition of that function on top, 'later' in time.

gitlab version 5.4.0 94a814d

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
