### ISSUE TITLE
URL Encoding in feeds

### ISSUE THREAD

**Issue by jbrooksuk** [gitlabhq/gitlabhq#5940]
If you post a comment containing a link, which contains an `&` character as part of the URI, it'll get encoded and then the link will probably no longer work when clicking the link within the Dashboard feed.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
