### ISSUE TITLE
Server Reboot Hangs at "Shutting down both Unicorn and Sidekiq..."

### ISSUE THREAD

**Issue by jawinn** [gitlabhq/gitlabhq#6019]
When running a "sudo reboot", the server hangs with an increasing number of dots after 

```Shutting down both Unicorn and Sidekiq........```

I'm running "GitLab 6.4.3" on Ubuntu 12.04.3 LTS. When the server reboots, I get this in some of the startup messages, which may or may not be helpful:

```
Starting redis-server: redis-server.                                                                  
Removing stale Sidekiq web server pid. This is most likely caused by the Sidekiq crashing the last time it ran.                                                                                             
Starting both the GitLab Unicorn and Sidekiqscript/web: line 21: bundle: command not found............. 
```

Also Gitlab is not running after reboot, and I have to run "sudo service gitlab start" (not sure if this is default or part of the error).

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
