### ISSUE TITLE
Merge request with wrong id after repository change

### ISSUE THREAD

**Issue by diguliu** [gitlabhq/gitlabhq#6039]
Hello guys,

I have a repository for my projeto and a fork of it for myself. I was going to make a merge-request for my projetct's repository from my own repository, but I ended up creating a merge-request for my own repository and then the merge-request got the id 1 (since it was the first request). I edited the merge request to the right branch on my project's repository and instead of assigning a new id, it stayed (apparently) with id 1, which conflicts with another merge request. Now on my merge-requests' page I can see the merge-request with the id 1 but I can't edit it since it directs to the original merge-request with id 1.

Here is the merge-requests page: https://gitlab.com/noosfero/noosfero/merge_requests/

The problematic merge-request's title is: "Remove Reply On Self View"

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
