### ISSUE TITLE
Backup restore not setting correct permissions on /home/git/repositories/

### ISSUE THREAD

**Issue by d1** [gitlabhq/gitlabhq#6064]
I'm using an internally developed Chef cookbook to build gitlab v6.4.3 and I'm seeing the backup restore process not set the correct permissions on `/home/git/repositories/`.

Steps To Reproduce:

```
# Build a fresh instance
$ vagrant destroy && vagrant up && vagrant ssh
$ cd /home/git/gitlab

# Run gitlab:check, all checks should pass
$ sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production

# Copy a backup into place and restore
$ sudo -u git -H cp /vagrant/<timestamp>_gitlab_backup.tar /home/git/gitlab/tmp/backups/
$ sudo -u git -H bundle exec rake gitlab:backup:restore RAILS_ENV=production

# Re-run gitlab:check, the check of permissions on /home/git/gitlab should fail
$ sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
```

After the restore, the permissions look like this:

```
$ ls -l /home/git/
...
drwxrwxr-x  5 git git     4096 Jan 15 11:12 repositories
drwxrws---  3 git git     4096 Jan 15 11:01 repositories.old.1389805956
```

Running the commands suggested by the check, or re-converging the node via Chef, will fix the permissions.

I'm assuming this is because the restore moves the current `/home/git/repositories/` to `/home/git/repositories.old.<timestamp>/` and then creates a new `/home/git/repositories/`. It also could be that the backup creation should be capturing the permissions acurately.

I'll look deeper and submit a PR unless someone can tell me I'm crazy or doing something wrong.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
