### ISSUE TITLE
git clone url selection doesn't work.

### ISSUE THREAD

**Issue by raphendyr** [gitlabhq/gitlabhq#6120]
What ever is done with `one_click_select` doesn't work correctly in opera or firefox.
This seems to work in chromium (and chrome probably).

What is expected:
 * When I click clone url and it selects the text, the text is in my X selection buffer.
 * If nothing is selected, that is ok too. Then I double click it and then it's correctly in my X selection buffer.

Current setup is frustrating as you think you have the url in your buffer, but you don't.

I ques problem is in js that handles elements with class `one_click_select`.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
