### ISSUE TITLE
Duplicate error message

### ISSUE THREAD

**Issue by jvanbaarsen** [gitlabhq/gitlabhq#6123]
When i try to add a user in the admin dashboard, and the e-mail is already taken, i see the notice: `Email has already been taken` twice.

**screenshot:**
![screenshot 2014-01-22 19 51 56](https://f.cloud.github.com/assets/1362793/1977303/4972c84a-8396-11e3-9a01-2e340bf99418.png)

**Steps to reproduce**
- Go to admin
- Create user with email: test@example.com
- Try to create another user with email test@example.com

**Comment by swellard** [comment]
I have done some investigation and found why the duplicate occurs which is due to the configuration in app/models/user.rb
* The first message is generated as a result of the
`devise :lockable, :async, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :confirmable, :registerable`
line (specifically the `:validatable` setting that automatically adds validation for email and password)
* The second message comes from the
`validates :email, presence: true, email: { strict_mode: true }, uniqueness: true`
line (specifically the `uniqueness` check)
So both the `devise` check and the `validates` check are do a check for `uniqueness` by email which results in 2 trips to the database and two errors
The simple fix is to remove the `uniqueness` check from `validates` making sure to add comments as to why this has been done

**Comment by Razer6** [comment]
fixed by https://github.com/gitlabhq/gitlabhq/commit/73918efb273b83b59f421557db2134973bb8eb53
