### ISSUE TITLE
Empty HTTP_REFERER handling

### ISSUE THREAD

**Issue by kevinvalk** [gitlabhq/gitlabhq#6175]
When having REFERERS disabled in your browser (thus not sending referers) gitlab fails to correctly handle this and just throws a 500 error. I would suspect a nicer way to handle this. 

 ```
Redirected to
Completed 500 Internal Server Error in 315ms

 ActionController::RedirectBackError (No HTTP_REFERER was set in the request to this action, so redirect_to :back could not be called successfully. If this is a test, make sure to specify request.env["HTTP_REFERER"].):
   app/controllers/profiles_controller.rb:25:in `block (2 levels) in update'
   app/controllers/profiles_controller.rb:24:in `update'
   app/controllers/application_controller.rb:57:in `set_current_user_for_thread'
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
