### ISSUE TITLE
Gitlab doesn't execute git during merge_action with environment PATH and GEM_PATH

### ISSUE THREAD

**Issue by dotmaster** [gitlabhq/gitlabhq#6215]
Hi,

the issue  #4299 still exists in Gitlab 6.3.1

vim  /home/git/gitlab-shell/hooks/update
changing the ruby shebang to the location ruby >1.9.1 resides helps.

kind regards

Gregor

**Comment by kevindaum** [comment]
Problem still exists in this environment:

GitLab 7.7.2
GitLab Shell 2.4.2
GitLab API v3
Ruby 2.1.2p95
Rails 4.1.1
Debian wheezy

I also made the replacement I described above in /home/git/gitlab-shell/hooks/update.

**Comment by kmetsalu** [comment]
#8555 has similar issue.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
