### ISSUE TITLE
Gitlab API REST encoding of non-ASCII characters wrong.

### ISSUE THREAD

**Issue by nudgegoonies** [gitlabhq/gitlabhq#6244]
In the Gitlab 6.3.0 the non-ASCII characters are correctly rendered by the REST Api. In Version 6.5.1 they are not.

This is the output of the branches? function of Version 6.3.0:
```
{"name":"changes_for_eclipse","commit":{"id":"XYZ","parents":[{"id":"XYZ"}],"tree":"XYZ","message":"\"Unn\u00f6tiger\" cast hinzugef\u00fcgt der f\u00fcr den ...","author":{"name":"XYZ","email":"XYZ"},"committer":{"name":"XYZ","email":"XYZ"},"authored_date":"2013-10-25T10:31:53+02:00","committed_date":"2013-10-25T10:31:53+02:00"},"protected":false}
```

This is the output of Version 6.5.1:
```
{"name":"changes_for_eclipse","commit":{"id":"XYZ","parents":[{"id":"XYZ"}],"tree":"XYZ","message":"\"UnnÃ¶tiger\" cast hinzugefÃ¼gt der fÃ¼r den ...","author":{"name":"XYZ","email":"XYZ"},"committer":{"name":"XYZ","email":"XYZ"},"authored_date":"2013-10-25T10:31:53+02:00","committed_date":"2013-10-25T10:31:53+02:00"},"protected":false},
```

My environment is:
```
System:     Debian 7.1
Current User:   git
Using RVM:  no
Ruby Version:   1.9.3p194
Gem Version:    1.8.23
Bundler Version:1.1.4
Rake Version:   10.1.0

GitLab information
Version:    6.5.1
Revision:   9c8f584
Using LDAP: no
Using Omniauth: no

GitLab Shell
Version:    1.8.0
Git:        /usr/bin/git
```
Regards,
Andreas

**Comment by UnderGreen** [comment]
I have same issue, when I try to use blame on commit with '*_ASSERT' on commit message
blame/3d4afd29972e59c3918f5d30388cbbaf184e20d5/Projects/UniSearch/BitField.h
```
Encoding::CompatibilityError (incompatible character encodings: UTF-8 and ASCII-8BIT):
  app/views/projects/blame/show.html.haml:48:in `block in _app_views_projects_blame_show_html_haml__4401936396475562449_27793120'
  app/views/projects/blame/show.html.haml:13:in `_app_views_projects_blame_show_html_haml__4401936396475562449_27793120'
```

**Comment by noamik** [comment]
The links provided above still return a 500. This is on your publicly hosted repository service. Feel free to check this yourself:
https://gitlab.com/noamik/test-project/commits/T%C3%84ST
https://gitlab.com/noamik/test-project/tags
https://gitlab.com/noamik/test-project/commits/master

**Comment by nilrebibaf** [comment]
Hi guys,

i am experiencing the same issue after converting a project using cvs2git and importing into gitlab with "gitlab-rake gitlab:import:repos" which worked fine. 
I can see all the commits and their messages. But in the commit messages all the non-ascii chars are broken. In my case it affects characters like 'ö', 'ä', 'ü', 'ß'.
For comments added using the interface, non-ascii chars work.

I am running GitLab 7.7.2 on CentOs 6.6 final 64bit, installed from Omnibus.

Did someone find a solution yet? If you need any further info please inform me about. 
Thanks in advance :)

Greetings

**Comment by noamik** [comment]
@nilrebibaf While I haven't tried your approach, I don't think it is related. When I migrated our svn, I didn't use cvs2git, because I couldn't get it to migrate everything as I would have liked to. What worked out better for me was using cvs2svn and then a svn import.

My solution was something similar to this:
```bash
cvs2svn --encoding=UTF-8 --fallback-encoding=cp1252 --svnrepos "/target-svn-repo-dir/projectA" "/cvs-root-dir/projectA"

svn checkout file:///target-svn-repo-dir/projectA/trunk /convert/svn-checkedout-root
cd svn-checkedout-root
svn log -q | awk -F '|' '/^r/ {sub("^ ", "", $2); sub(" $", "", $2); print $2" = "$2" <"$2">"}' | sort -u > /convert/authors-transform.txt

mkdir -p "/git-project/projectA"
cd "/git-project/projectA"
git svn init "file:///target-svn-repo-dir/projectA" --stdlayout --prefix=cvs/
git svn fetch -A /convert/authors-transform.txt

echo "Migrating branches"
for branch in `git branch -r | grep -v "tags/" | sed 's/  cvs\//cvs\//'`; do
  echo "git branch $branch refs/remotes/$branch"
  git branch $branch refs/remotes/$branch
done
echo "Migrating tags"
for tag in `git branch -r | grep "tags/" | sed 's/  cvs\/tags\//cvs\/tags\//'`; do
  echo "tag -a -m\"Converting SVN tags\" $tag refs/remotes/$tag"
  git tag -a -m"Converting SVN tags" $tag refs/remotes/$tag
done
```
The hole process was a bit more complicated because I needed to migrate several dozen projects at once, but you should get the idea. With this approach I was able to preserve non-ascii characters like 'ö', 'ä', 'ü', 'ß' in our comments.

**Comment by nilrebibaf** [comment]
@noamik 
thanks for sharing your approach with me. during the last couple of days i was able to solve my issue regarding the non-ascii chars in the converted repos as mentioned in the comment above.

but now i ran into another issue, which is probably related to the last one:
in new created branches that have those non-ascii chars in their name throw the following error:

Repository http://192.168.100.26/groupname/reponame

/opt/gitlab/embedded/lib/ruby/2.1.0/json/common.rb:223:in `encode': "\xC3" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /opt/gitlab/embedded/lib/ruby/2.1.0/json/common.rb:223:in `generate'
	from /opt/gitlab/embedded/lib/ruby/2.1.0/json/common.rb:223:in `generate'
	from /opt/gitlab/embedded/lib/ruby/2.1.0/json/common.rb:394:in `dump'
	from /opt/gitlab/embedded/service/gitlab-shell/lib/gitlab_post_receive.rb:25:in `update_redis'
	from /opt/gitlab/embedded/service/gitlab-shell/lib/gitlab_post_receive.rb:18:in `exec'
	from hooks/post-receive:17:in `<main>'

Does someone has any clues how to solve?

**Comment by noamik** [comment]
This is most likely the issue this bug report is about. The only work-around I know of is simply not to use non-ascii characters in tags or branches. This isn't related to your configuration at all, since you can see the same issue with the official gitlab.com repositories. I made a specific public repo to demonstrate:
https://gitlab.com/noamik/test-project/commits/T%C3%84ST
https://gitlab.com/noamik/test-project/tags
https://gitlab.com/noamik/test-project/commits/master

If you already have such a branch, the only solution I know of is to login into your server and change the branch name on the command line. You can do this by creating a new branch with a ASCII-character-only name by referencing the non-ASCII-branch. Afterwards you delete the non-ASCII-branch. Since the issue exists for more than a year now without fix, I wouldn't expect a fix anytime soon.

**Comment by nudgegoonies** [comment]
ASCII is originally based on the English alphabet. There are so much other languages and charsets in the world...

**Comment by noamik** [comment]
@nudgegoonies I know, but I can't change the technical reality that atm gitlab can't handle any of those languages in tag-names or branch-names. And nilrebibaf asked for a solution to his problem.

And then there is: http://www.ietf.org/mail-archive/web/ietf-announce/current/msg13718.html
In 2015 they still think ASCII is useful for anything ;)

**Comment by nudgegoonies** [comment]
@noamik I also know it from my work and it is always a mess to find a fix when the problem lies in a library or inside a remote service.

Unix philosophy: 5 Store data in flat text files.

http://blog.codinghorror.com/there-aint-no-such-thing-as-plain-text/ ;)

**Comment by noamik** [comment]
@nudgegoonies What really bugs me is that the original "Joelonjoftware" article about this is more than a decade old by now and people still get this wrong in software they write today ...

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
