### ISSUE TITLE
Suddenly started to get 500 error on a commit which I already added a few comments on earlier

### ISSUE THREAD

**Issue by ajay1609** [gitlabhq/gitlabhq#6338]
Hey,
 I am using Gitlab 6.0 and was doing a code review on a commit. When I reopened that commit after sometime, It started giving me an error 500, We are sorry but something went wrong ,error.. Please note that this is happening only for this particular commit and not for any other commits in the repository.

Following is the production log
-------------
....
....
...
  Rendered projects/commit/show.html.haml within layouts/projects (913.5ms)
Completed 500 Internal Server Error in 1093ms

ActionView::Template::Error (no implicit conversion of nil into String):
    1: - note = notes.first # example note
    2: -# Check if line want not changed since comment was left
    3: - if !defined?(line) || line == note.diff_line
    4:   %tr.notes_holder
    5:     %td.notes_line{ colspan: 2 }
    6:       %span.btn.disabled
  lib/gitlab/diff_parser.rb:69:in `digest'
  lib/gitlab/diff_parser.rb:69:in `hexdigest'

Please let me know what went wrong.

Regards
Ajay

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
