### ISSUE TITLE
Saving issue doesn't work sometimes

### ISSUE THREAD

**Issue by phortx** [gitlabhq/gitlabhq#6343]
I know this is a really unclear issue, but unfortunately I can't reproduce that simply ... Maybe someone has an idea.

### Summary
We had now several times the case, that we tried to open an issue in gitlab and after submitting it, gitlab jumps to another issue within the same project but the issue we tried to create was not created. Sometimes the browser back gives us the issue text back. But sometimes the typed text ist simply lost. 

### How to reproduce
I can't reproduce it simply but we (my team) have seen that issue about 5 times until now. If it happens again, I'll try to gather some informations.

### Expected bahavior
GitLab should save the issue and open that issue.

### Observed bahavior
GitLab doesn't save the issue at all and jumps to some other issue within the same project.

### Checks and Version
The check is green and everything works well. Version is `6.5.1 6f6f158`.

### Environment
Nothing special except of LDAP.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
