### ISSUE TITLE
 Avatar image relative path problem. (Network tab -> commit graph)

### ISSUE THREAD

**Issue by yms9654** [gitlabhq/gitlabhq#6354]
I set relative_url_root: /gitlab.
So I think avatar image url shoud be 'http://server-host/gitlab/uploads/user/avatar/21/minsik.jpg'.
But actual request url is 'http://server-host/uploads/user/avatar/21/minsik.jpg'.
As a result, avatar image is broken.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
