### ISSUE TITLE
Redirect loop after testing service settings

### ISSUE THREAD

**Issue by heikobornholdt** [gitlabhq/gitlabhq#6358]
When I open the edit page for GitLab CI-Service of a GitLab Project (http://example.com/foo/bar/services/gitlab_ci/edit), click to "Test settings", wait for page to refresh and click "Test settings" again, it will result in a "redirect loop".

I believe, the `redirect_to :back` instruction (https://github.com/gitlabhq/gitlabhq/blob/2ed7cbfba4ff3c6a4cf3e72515a0375544998de0/app/controllers/projects/services_controller.rb#L31) causes this problem.

Now I have dozens of pending builds on my GitLab CI :laughing:

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
