### ISSUE TITLE
File/commit preview not correctly detects cp1251

### ISSUE THREAD

**Issue by blackbass1988** [gitlabhq/gitlabhq#6362]
Summary
==========
I'm opening files/commits and see that my files in cp1251 don't correctly rendering

How to reproduce
==========

For example. Take next text: "Тагил!!!" and save this in file in cp1251 encoding.
You can use vim (:set fileencoding=cp1251)

Next you must add this file and push it to gitlab for see the result

Expected bahavior
==========

"Тагил!!!" in my file

Observed bahavior
===============
"ﾒ璢齏!!!" instead "Тагил!!!"

Relevant logs and/or screenshots
================
[screenshot](https://www.dropbox.com/s/mi92cpv5rvc3ts8/Screenshot%202014-02-21%2022.05.43.png)

Checks and Version
=============
The check is green and everything works well. 

```

GitLab information
Version:	6.5.1
Revision:	2ffa03a
Directory:	/home/git/gitlab
DB Adapter:	mysql2
URL:		https://git.drom.ru
HTTP Clone URL:	https://git.drom.ru/some-project.git
SSH Clone URL:	git@git.drom.ru:some-project.git
Using LDAP:	no
Using Omniauth:	no

```

**Comment by jvanbaarsen** [comment]
Problem still present in `7.11.0.pre 3a3f4b4`. Although GitLab is now giving an error: `--broken encoding: UTF-16BE`

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
