### ISSUE TITLE
BUG: Fork repository

### ISSUE THREAD

**Issue by fabiosammy** [gitlabhq/gitlabhq#6415]
Simplify: Owner of project cannot fork. 

Tip: Hide "fork" option or i don't know. (JK)

PS: Sorry my poor english.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
