### ISSUE TITLE
Can not set group avatar for single group

### ISSUE THREAD

**Issue by paleg** [gitlabhq/gitlabhq#6436]
Summary: Can not set group avatar for single group, named 'projects'
For all other groups avatars can be added without any problems.
Also this avatar picture can be assigned to any other group not named 'projects'.

Steps to reproduce: 
1. go to /groups/projects
2. click "Choose file..."
3. choose file 
4. click "Save group"

Expected behavior: Group avatar should be set

Observed behavior: Error 'Path is reserved' is shown

Relevant logs and/or screenshots: 
```
Started PATCH "/groups/projects" for 127.0.0.1 at 2014-02-27 19:53:03 +0200
Processing by GroupsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"dW3mvCUTSPMY1N7sc3CfdxQRste48jWZYQwc8rGfgHo=", "group"=>{"name"=>"projects", "description"=>"", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x007ff3bbd54b78 @tempfile=#<File:/tmp/RackMultipart20140227-25181-1aqdu8b>, @original_filename="pr.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"group[avatar]\"; filename=\"pr.png\"\r\nContent-Type: image/png\r\n">}, "id"=>"projects"}
  Rendered groups/edit.html.haml within layouts/group (158.2ms)
  Rendered layouts/_head.html.haml (2.1ms)
  Rendered layouts/_broadcast.html.haml (2.4ms)
  Rendered layouts/_search.html.haml (1.1ms)
  Rendered layouts/_head_panel.html.haml (7.7ms)
  Rendered layouts/_flash.html.haml (0.2ms)
  Rendered layouts/nav/_group.html.haml (10.6ms)
Completed 200 OK in 245ms (Views: 172.1ms | ActiveRecord: 51.2ms)
Started GET "/assets/no_group_avatar.png" for 127.0.0.1 at 2014-02-27 19:53:04 +0200
```
```
$ ls -al /tmp/RackMultipart20140227-25181-1aqdu8b public/uploads/tmp/1393523583-25181-9752/pr.png 
-rw------- 1 git git 10816 февр. 27 19:53 /tmp/RackMultipart20140227-25181-1aqdu8b
-rw-r--r-- 1 git git 10816 февр. 27 19:53 public/uploads/tmp/1393523583-25181-9752/pr.png
```
Results of GitLab Application Check: all are green

```
Using RVM:      no
Ruby Version:   1.9.3p194
Gem Version:    2.0.3
Bundler Version:1.3.5
Rake Version:   10.1.1

GitLab information
Version:        6.6.0
Revision:       490f99d
Directory:      /home/git/gitlab
DB Adapter:     mysql2
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.8.0
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
