### ISSUE TITLE
Incoherent search behaviour

### ISSUE THREAD

**Issue by mighe** [gitlabhq/gitlabhq#6442]
GitLab 6.6.2
GitLab Shell 1.8.0
GitLab API v3
Ruby 2.1.1p76
Rails 4.0.3
Db: postgre

Let's suppose to have a project called "My Project"

- searching "My P" it is correctly found
- searching "my" or "project" it is correctly found
- searching "my p" I got it as suggestion, but if submit the project is not shown in list

The problem is [here](https://github.com/gitlabhq/gitlabhq/blob/master/app/models/project.rb?source=c#L159): Ajax uses `search_by_title` that performs a lower case conversion, on the other hand `search` keeps input and data as they are.

Expected behaviour is having a case *insensitive* search everywhere, not only in titles

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
