### ISSUE TITLE
Gitlab Merge Issue

### ISSUE THREAD

**Issue by gerardmoroney** [gitlabhq/gitlabhq#6471]
The issue is encountered when a Merge Request is created from a fork of a project.

1. Create Merge Request with latest commit from fork master to original project master.
2. Click Submit Merge Request button.
3. Routed to error 500 page (see attached screenshot)
4. The Merge Request is created despite the error, but it is empty when viewed on GitLab.
5. When the Merge Request is pulled into the local repository of a machine you will see that it does contain a commit and is not empty.
![gitlaberror_screenshot](https://f.cloud.github.com/assets/2689643/2330810/46b9e38c-a43d-11e3-9b6f-ac2771bdc766.jpg)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
