### ISSUE TITLE
Can not access via ssh and view layout without css

### ISSUE THREAD

**Issue by poc7667** [gitlabhq/gitlabhq#6476]
Original 
`http://stackoverflow.com/questions/22218315/can-not-access-via-ssh-and-view-layout-without-css`

I set up the Gitlab in my company LAN,

Now, I can access the Gitlab server by 

`http://dqa-test`

But when I ran ` sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production`

I got `Check GitLab API access: FAILED. code: 404`

    I've change the `host:` with dqa-test, dqa-test/ , with `http://` or not

But after all the above tries, it still got the same error by running self-check

I can clone a project from via http , but no way in `ssh`

    git clone git@dqa-test:vvtk_dqa_automation_team/sandbox.git
    Cloning into 'sandbox'...
    Access denied.
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

My gitlab.yml

      ## GitLab settings
      gitlab:
        ## Web server settings (note: host is the FQDN, do not include http://)
        host: "http://dqa-test"
        port: 1987
        https: false

I have no idea why I don't have the correct layout

It doesn't work when I ran `sudo -u git -H bundle exec rake assets:clean assets:precompile cache:clear RAILS_ENV=production`
![enter image description here][1]

 ![enter image description here][2]

  [1]: http://i.stack.imgur.com/Nr0hw.png
  [2]: http://i.stack.imgur.com/KBGG1.png

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
