### ISSUE TITLE
500 Error on settings page when old issue tracker is used.

### ISSUE THREAD

**Issue by ghost** [gitlabhq/gitlabhq#6511]
Hallo developers,

in gitlab there is an option to use an alternative issue tracker like redmine. So if you have set this up in the config/gitlab.yml file, you are able to select this tracker in the "settings tab" of your project and anything works fine.

But if you now remove the external issue tracker feature from your config/gitlab.yml file, there is a problem. If you now navigate to your project issue tab it shows you the default issue system. This is right, and it is good, that gitlab detect that the extrenal tracker is locked.

BUT if you want to change any settings so you have to go to the settings tab, you get a 500 error. Why? In the database the old tracker is listed. You have to uncomment the external tracker lines so it is "activated". Then you have to change your issue system to internal. After that you can disable your old issue system.

This is complicated and may broke up setups.

It is possible to fix this?

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
