### ISSUE TITLE
Wrong base version in side-by-side diff view for merge requests

### ISSUE THREAD

**Issue by bentolor** [gitlabhq/gitlabhq#6516]
Since GitLab 6.4 a side-by-side view for diffs is available. At least for merge requests the displayed diff seems to be wrong in my opinion.

For illustration see the following screenshots. Both origin from the diff view of the *same merge requests*

The classic diff view correctly shows the difference between the file as it is in the original branch compared to the tip of our merge requests. :white_check_mark:

![mergerequest-classicdiff](https://f.cloud.github.com/assets/588260/2398755/b11ce88a-a9f8-11e3-83c9-a9be3360f1f4.png)

But the side-by-side view shows something different: In the commits of our merge requests I changed the shown file in two different commits. The side-by-side view seems to show the branch tip compared to  *any previous file commit* and **not** the merge base :x:

![mergerequest-sidebysidediff](https://f.cloud.github.com/assets/588260/2398938/63e213e0-a9fa-11e3-9964-55f17f532c9d.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
