### ISSUE TITLE
Notification settings for owned repos

### ISSUE THREAD

**Issue by enumag** [gitlabhq/gitlabhq#6540]
Hi, on the page `/profile/notifications` I can set notifications on group or even project-level. However for some reason there are only those projects that I'm actually a member of, the projects I'm just "owner" of but not a "member" of are not there.

Gitlab version: 6.6.4 (Anything else is irrelevant in my opinion.)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
