### ISSUE TITLE
It will be 500 when I put a link to the wiki

### ISSUE THREAD

**Issue by nabepon** [gitlabhq/gitlabhq#6559]
GitLab : v6.6.5

After creating the project, when it is made ​​only wiki,
It will be 500 when I put a link to the wiki.

this text created by Google Translate.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
