### ISSUE TITLE
If I leave comments in merge request commits, the comments purely remain in the fork only.

### ISSUE THREAD

**Issue by crocket** [gitlabhq/gitlabhq#6571]
Thus, the forked project doesn't get comments in commits before and after the merge request is merged.

If I just delete the fork, the comments are lost with it.

There are two ways to solve this issue.

1. Github way : Just copy the commits from the fork to the forked whenever a commit is added to the merge request, and just hide those commits in the commit tab of the forked project until the merge request is merged. As a result, comments are added to the forked repo. This way, comments and commits get to live even after the merge request is rejected and the fork is removed.
1. Copy or transfer the comments to the forked project when the merge request is merged.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
