### ISSUE TITLE
500 error on automerge_check (maybe because of core.autocrlf being set to input)

### ISSUE THREAD

**Issue by msouth** [gitlabhq/gitlabhq#6589]
1. **Summary:** When viewing a merge request, the check for automerge causes an ISE
2. **Steps to reproduce:** 
    1. Add, commit, push a crlf file from linux on a branch
    2. Create a merge request for that branch
    3. View the merge request
3. **Expected behavior:**
a message saying whether the branch can be automatically merged
4. **Observed behavior**
<img src="http://i60.tinypic.com/r0a8lc.png"/>
5. **Relevant logs and/or screenshots:**
    Completed 500 Internal Server Error in 257ms

     Grit::Git::CommandFailed (Command failed [1]: /usr/bin/git --git-dir=/home/git/gitlab-satellites/allops/machinedb/.git branch -D feature/api_logs

    error: Cannot delete the branch 'feature/api_logs' which you are currently on.

    [git@gitlabhost the_project]$ git diff > /tmp/x.diff
    warning: CRLF will be replaced by LF in public/javascripts/jquery.dump.js.

Viewing /tmp/x.diff shows a diff with every line changed from CRLF to LF

    [git@gitlabhost the_project]$ git status
    # On branch feature/api_logs
    # Changed but not updated:
    #   (use "git add <file>..." to update what will be committed)
    #   (use "git checkout -- <file>..." to discard changes in working directory)
    #
    #	modified:   public/javascripts/jquery.dump.js
    #
    no changes added to commit (use "git add" and/or "git commit -a")

6. **Output of checks**
    * Results of GitLab [Application Check](doc/install/installation.md#check-application-status) (`sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production`); we will only investigate if the tests are passing

    Git version >= 1.7.10 ? ... no
    Try fixing it:
    Update your git to a version >= 1.7.10 from 1.7.1
    Please fix the error above and rerun the checks.

(not adminning this box so I can't just do that)

    * Version of GitLab you are running;

6.1.0 82f3446
    * Add the last commit sha1 of the GitLab version you used to replicate the issue 
6.1.0 82f3446

7. **Possible fixes**: 

Issue #3982 discusses this a bit, and was resolved with 2d681c0 

I undid 2d681c0, in the satellite directory /home/git/gitlab-satellites/my_group/the_project

    [git@gitlabhost the_project]$ git config core.autocrlf false
    [git@gitlabhost the_project]$ git config core.autocrlf 
    false

Then I deleted the branch with the "change"
    [git@gitlabhost the_project]$ git checkout __parking_branch
    Switched to branch '__parking_branch'
    [git@gitlabhost the_project]$ git branch -D feature/api_logs

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
