### ISSUE TITLE
Markdown on Login page results in an error 500

### ISSUE THREAD

**Issue by spuder** [gitlabhq/gitlabhq#6611]
On gitlab 6-7-stable, you can not use mark down on the login page, or else you get an error. 

Steps to reproduce: 

In the gitlab.yml add a logo or text like so

     ## Text under sign-in page (Markdown enabled)
     # sign_in_text: |
     ![Company Logo](http://placepuppy.it/300/110)
     http://failblog.cheezburger.com

When you restart gitlab, you will get a 500 error

The production.log will show the following: 
```
Started GET "/" for 127.0.0.1 at 2014-03-24 21:25:04 +0000
Processing by DashboardController#show as HTML
  Rendered dashboard/_zero_authorized_projects.html.haml (11.3ms)
  Rendered dashboard/show.html.haml within layouts/application (14.9ms)
  Rendered layouts/_head.html.haml (8.2ms)
Completed 500 Internal Server Error in 313ms

ActionView::Template::Error (undefined method `has_key?' for "Logo](http://placepuppy.it/300/110)":String):
    24:       - if current_controller?(:issues)
    25:         = auto_discovery_link_tag(:atom, project_issues_url(@project, :atom, private_token: current_user.private_token), title: "#{@project.name} issues")
    26:
    27:   -# Go repository retrieval support.
    28:   - if controller_name == 'projects' && action_name == 'show'
    29:     %meta{name: "go-import", content: "#{@project.web_url_without_protocol} git #{@project.web_url}.git"}
  app/views/layouts/_head.html.haml:27:in `_app_views_layouts__head_html_haml__3706907333394041321_34517880'
  app/views/layouts/application.html.haml:3:in `_app_views_layouts_application_html_haml___471545202684173759_33900380'
  app/controllers/dashboard_controller.rb:27:in `show'
  app/controllers/application_controller.rb:58:in `set_current_user_for_thread'
```

This only affects 6-7-stable. All prior versions work correctly with this syntax.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
