### ISSUE TITLE
no authentication for projects of public area(push tags only).

### ISSUE THREAD

**Issue by ZhangBowen** [gitlabhq/gitlabhq#6625]
When I pushed tags with
```
git push --tags
```
to a public project,it passed without authentication.And then the author of this push is wrong(seems to be the first user of GitLab).Is it a bug?

**Comment by massimone88** [comment]
I had a problem that seem to be tha same (issue #8599). If I push with this command `git push--tags`, i can push on protected branch os the autorization is not required!

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
