### ISSUE TITLE
Branch merge issue

### ISSUE THREAD

**Issue by Petchimuthu** [gitlabhq/gitlabhq#6631]
While accepting merge request, its status marked as merged but changes not reflected in the target branch.

Merge information also displayed in the dashboard. 

If we push manually from satellite then the changes got reflected in the target branch.

We don't know the reason for this issue.

Is there any log to find the root cause?

Thanks,
Muthu

**Comment by yshahin** [comment]
Any news on this?

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
