### ISSUE TITLE
Updating a fork with changes from the original project

### ISSUE THREAD

**Issue by MBurchard** [gitlabhq/gitlabhq#6646]
How can I update an existing fork with changes, that where made on the main project.
The reason:
On the main project we only allow some developers to work. Additional developers should work in their own fork.
We tried that recently and it's quit easy to merge changes from that fork back into the main project.
But now all other forks are not up to date.
The only solution I see is deleting the other forks and recreate them.
Is there a better way?

**Comment by muckinger** [comment]
We also need this functionality, is this still not in place? We can't find anything...

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
