### ISSUE TITLE
unable restore repository in gitlab 6.5.1

### ISSUE THREAD

**Issue by SelinaDu** [gitlabhq/gitlabhq#6659]
I backup gitlab repository in GitLab 6.5.1 2ffa03a 
bundle exec rake gitlab:backup:create RAILS_ENV=production
git stash 
Saved working directory and index state WIP on 6-5-stable: 2ffa03a Replace context with service in development seed data.
HEAD is now at 2ffa03a Replace context with service in development seed data.

when restore repository in GitLab 6.5.1 6f6f158 on another server .
bundle exec rake gitlab:backup:restore RAILS_ENV=production BACKUP=1394603827
git stash :
Saved working directory and index state WIP on (no branch): 6f6f158 Version 6.5.1
HEAD is now at 6f6f158 Version 6.5.1

it shows below error :
Unpacking backup ... done
GitLab version mismatch:
  Your current HEAD differs from the HEAD in the backup!
  Please switch to the following revision and try again:
  revision: 2ffa03ab3a45fe43e3770524e3dcbfcb50e33478

I want to  backup gitlab repository in GitLab 6.5.1 2ffa03a  ,then restore repository in GitLab 6.5.1 6f6f158 ,is there any better way to complete this and try not to change anything in GitLab 6.5.1 6f6f158 ?

appreciate if you can help ,Thanks .

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
