### ISSUE TITLE
MR comments: too many mentioned-in-comments generated

### ISSUE THREAD

**Issue by fcelda** [gitlabhq/gitlabhq#6734]
Mentioning a commit in a merge request comment creates a useless *mentioned comment* in the merge request.

For example:

1. Darth Vader writes a MR comment saying: *I feel a great disturbance in the commit abcd123.*
2. A new automatic comment appears in the same MR: *Darth Vader started a discussion on commit abcd123.*
3. Under the automatic comment, a new comment appears saying: *mentioned in merge request !42*

We find the comment useless because:

* There is no direct reference to the source of the mention. You have to open the link and search the whole page to find it.
* If there are multiple mentions of the same commit in the MR, multiple comments saying *mentioned in merge request* appear.
* It creates mess on the MR page, especially for large merge requests.
* It spams involved people's mailboxes.
* With each new comment, the web interface is getting more unresponsive. And the load on our server increases.

It would be great if something can be improved in this area.

**Comment by Gnodiah** [comment]
Is this problem being solving? It really creates so many useless mentioned comments.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
