### ISSUE TITLE
editing a comment retriggers creation of all mentioned-in comments

### ISSUE THREAD

**Issue by fcelda** [gitlabhq/gitlabhq#6735]
Editing a merge request comment (and probably other comments in general), retriggers a creation of all mentioned-in comments referred by that comment.

1. Create a comment mentioning a commit. New mentioned-in comment is created.
2. Click on the Edit link, edit something except the commit ID and hit Save Changes. Another mentioned-in comment is created.

I would find more useful, if the mentioned-in comments were created more smartly, e.g.:

1. Just for newly added references.
2. Or just one *mentioned-in \<source\>* comment could exist.

(We edit the comments pretty heavily on large MR - we use them as a kind of a wiki page, which is probably unusual, but surely less cluttered than having a lot of comments.)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
