### ISSUE TITLE
The link to an user in the Dashboard page goes 404 after username changed in account settings

### ISSUE THREAD

**Issue by kfei** [gitlabhq/gitlabhq#6748]
For example, change Administrator's username to **r00t**, but the link href still **root** in the Dashboard page.

I'm using GitLab 6.7.3 f88d30f.

**Comment by Yunoske** [comment]
Hi,

I was troubled by the same issue in GitLab 7.7.2 omnibus edition and finally found the solution.
Though the fix should be applied to the GitLab source code of changing username feature, I'll show you a work around.

### Remark
Please keep in mind that the solution below will change username in original git repository. If you only want to correct link reference, please skip procedure No.1.
procedure No.1 tries to modify username appeared in "Network" and "Commits" pages in GitLab. So if you don't need to align username in those pages, you also don't need to do the dangerous task, which all contributors pertaining to the repository will be seriously impacted by the change.

### Procedure
1. Modify username in your raw git repository

  (See detail at https://help.github.com/articles/changing-author-info/)
  In my case, I directly run 'git filter-branch' command in origin repository on my GitLab server.
2. Modify username in database which holds dashboard events information
  1. Login to terminal of the GitLab server by ssh/telnet/console
  2. switch to root user<br />`$ su -`
  3. switch to gitlab-psql user<br />`$ su - gitlab-psql`
  4. Dump tables which contains username information from postgresql<br />`pg_dump --format=plain --table=events --table=merge_request_diffs --file=pgsqldmp.txt gitlabhq_production`<br />
(*pgsqldmp.txt can be anything you want to name)
  5. Replace old username string to new one in the output csv file. More precisely, replace the username string in the "COPY events..." statement and "COPY merge_request_diffs..." statement.
  6. Switch back to root user<br />`exit`
  7. Stop all but postgresql<br />`gitlab-ctl stop`<br />`gitlab-ctl start postgresql`
  8. Switch to gitlab-psql user again<br />`su - gitlab-psql`
  9. Drop modifying tables<br/>`psql gitlabhq_production -c 'DROP TABLE events'`<br />`psql gitlabhq_production -c 'DROP  TABLE merge_request_diffs'`
  10. Restore the modified dump for dropped tables.<br />`psql gitlabhq_production -f pgsqldmp.txt`
  11. Switch back to root user<br />`exit`
  12. Start GitLab<br />`gitlab-ctl start`
3. Clear GitLab cache
  1. Execute clear cache command<br />`gitlab-rake cache:clear`

When I found out that clearing GitLab cache is the essential process, I almost had my voice out in my calm company's office!

Hope this saves your precious time :)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
