### ISSUE TITLE
Graph - number of commits and additions differ

### ISSUE THREAD

**Issue by bspinner** [gitlabhq/gitlabhq#6750]
We've discovered a problem with graphs. Every time you open the graph page of a project, calculated numbers will be different compared to those calculated after selecting something from the dropdown.

Steps
=====

1. Open graph page of a project
2. Look at number of commits, additions and deletions
3. Without touching the timespan, select `Additions` in dropdown list
4. Select `Commits` again
5. Look at the numbers again. They've changed (seem to be more correct than before)

Using version 6.7.2

Screenshots
==========

**After Step 1**

![gitlab_1](https://cloud.githubusercontent.com/assets/4580497/2677755/f323c35a-c156-11e3-9419-7bebe409fa72.png)

**After Step 4**

![gitlab_2](https://cloud.githubusercontent.com/assets/4580497/2677757/f690a1ca-c156-11e3-920b-9a07e711003d.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
