### ISSUE TITLE
Commits should not be sorted by CommitDate in merge request

### ISSUE THREAD

**Issue by pfctgeorge** [gitlabhq/gitlabhq#6756]
I used GitLab 6.6.5, and I found commits in merge request are sorted by their CommitDate. When two commits' CommitDates are the same, their orders will be inaccurate.
From my sight, descendant commits should be listed after their parent commits.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues). Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
