### ISSUE TITLE
newline in table

### ISSUE THREAD

**Issue by popomore** [gitlabhq/gitlabhq#6824]
it seems not work.

```
a | b 
--- | ---
a <br> b | c
```

**Comment by mani95lisa** [comment]
+1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
