### ISSUE TITLE
Non-forgetful "To issues list"

### ISSUE THREAD

**Issue by cndreiter** [gitlabhq/gitlabhq#6841]
If I view an issue and click the "To issues list" button afterwards, instead of the previously selected "Assigned to me" issues, "Everyone's" issues are shown. This is a usability flaw that hits me at least once a day. Please fix it.

*The browser back button is not a valid workaround, because if I edited an issue before returning to the issues list, the back button click actually redirects me to the edit form and not to the issues list.*

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues). Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
