### ISSUE TITLE
Web editor doesn't work well with iPad

### ISSUE THREAD

**Issue by dblessing** [gitlabhq/gitlabhq#6852]
Previously reported in #5267 but it pre-dated "officlal" support for iPads/tablets. This is now a bug instead of a feature request.

The following do not work in the editor on an iPad:
1. There is no way to scroll the text in the web page
1. The keyboard does not appear to enter new content

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
