### ISSUE TITLE
Issue "updated xxx ago" is not accurate

### ISSUE THREAD

**Issue by diablo2man** [gitlabhq/gitlabhq#6899]
I don't understand what "updated xxx ago" refers to in current gitlab. I believe the correct logic should be the time of newest comment added/edited or main content edited.

Currently it is very difficult to see from browsing issue page that when was the newest comment for each issue. The sorting also doesn't make sense due to this. The issue with newest comment should be put to first. I think this is also the behavior for github

Thanks!

**Comment by jvanbaarsen** [comment]
The recently updated is only used for the actual content of the issue at the moment.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
