### ISSUE TITLE
Two identical deploy keys caused access denied message

### ISSUE THREAD

**Issue by sekrett** [gitlabhq/gitlabhq#6908]
I don't know which version introduced this bug, first time I noticed it on version 6.7, now I have 6.8. I had two identical keys on two different projects, but added them separately, it worked before but all of a sudden I get the 'access denied' on `git pull`. I tried to delete both keys but the key was not removed from `authorized_keys` file, so I removed the line manually and added the deploy key again. Now I added one key and on the second project I just enabled the existing key. Maybe this is not a bug anymore but I in my opinion the `authorized_keys` file should be cleaned more carefully. Just to let you know.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues). Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
