### ISSUE TITLE
Don't truncate merge request titles for email notifications

### ISSUE THREAD

**Issue by bradchoate** [gitlabhq/gitlabhq#6909]
Merge request titles for comment notification emails are truncated too aggressively. I see no reason to truncate these. Certainly, 17 characters isn't enough to help provide context for these notifications.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
