### ISSUE TITLE
Milestones Ordering

### ISSUE THREAD

**Issue by jbrooksuk** [gitlabhq/gitlabhq#6914]
The list of milestones that display on the Issues list should be ordered the other way round, so that milestones which are about to expire are at the top:

![screen shot 2014-05-02 at 08 39 02](https://cloud.githubusercontent.com/assets/246103/2860484/01cb2836-d1cd-11e3-8c31-475b334ea661.png)

I'd expect the list to look more like this:

![screen shot 2014-05-02 at 08 41 42](https://cloud.githubusercontent.com/assets/246103/2860495/4285d63c-d1cd-11e3-9c77-aa3f6d7fe792.png)

So I'd imagine the order to be:

1. Milestone expiry
2. Milestone name

**Comment by jbrooksuk** [comment]
Bump.

**Comment by xevix** [comment]
I'm for allowing to select the ordering of milestones, by:
- Name
- Due date
- Asc/Desc

Right now, every time I have to assign an issue to a milestone, it takes a bit of sifting. Even a hidden param to the milestones controller(s) to specify sorting without the accompanying UI would be welcome.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
