### ISSUE TITLE
seed-fu breaks down in installation step "Initialize Database and Activate Advanced Features"

### ISSUE THREAD

**Issue by vkcelik** [gitlabhq/gitlabhq#6919]
Hello guys. This might not be the right place to ask for help but I searched on Google and could not find a solution to my problem.

I want to use MySQL database and Apache webserver. I followed the official manual installation guide at https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md

At the step "Initialize Database and Activate Advanced Features" I run the command:
sudo -u git -H bundle exec rake gitlab:setup RAILS_ENV=production
The command returns: http://pastebin.com/UZ4TGA2A

I run Ubuntu Server 14.04 on my home server.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
