### ISSUE TITLE
when you do a push from a remote, the log only appears in the commit tab not on the home page of the project

### ISSUE THREAD

**Issue by ghost** [gitlabhq/gitlabhq#6948]
it would be nice if I get that information also on the project home page. there is a nice summary of what is going on into the project.

why should I go to the commits tab to see if I did not sky anything?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
