### ISSUE TITLE
500 Error On GitlabCi Test (Using gitlab2jenkins)

### ISSUE THREAD

**Issue by bassrock** [gitlabhq/gitlabhq#6952]
Hi All,

I recently setup gitlab2jenkins and am trying to setup one of my projects to use it. However when testing the settings I get a 500 error with the following in the log:

```
Started GET "/api/v3/projects/124/merge_requests?private_token=1bxxGXkRyi7tsrg8s56W" for 127.0.0.1 at 2014-05-08 10:25:09 -0700
Started GET "/api/v3/projects/124/merge_requests?private_token=1bxxGXkRyi7tsrg8s56W&page=2" for 127.0.0.1 at 2014-05-08 10:25:09 -0700
Started GET "/api/v3/projects/124/merge_requests?private_token=1bxxGXkRyi7tsrg8s56W&page=3" for 127.0.0.1 at 2014-05-08 10:25:09 -0700
Completed 500 Internal Server Error in 10117ms
Timeout::Error (execution expired):
app/models/web_hook.rb:36:in `execute'
app/models/project_services/gitlab_ci_service.rb:26:in `execute'
app/controllers/projects/services_controller.rb:29:in `test'
app/controllers/application_controller.rb:59:in `set_current_user_for_thread'
```

What exactly does this error mean? Do you think this is an issue in gitlab or is there a new web hook added recently that it is trying to contact on the gitlab2jenkins service that does not exist?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues). Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
