### ISSUE TITLE
Cannot change case of username

### ISSUE THREAD

**Issue by fenhl** [gitlabhq/gitlabhq#6961]
I first signed up to gitlab.com through Twitter, which assigned me the username *Fenhl* (presumably because I'm *Fenhl* on Twitter). However, I like to use the lowercase version as a username on sites like github or gitlab, so I tried to change it. The error message that the username was already taken showed up. I had to delete the account and sign up manually as *fenhl*.

I assume that the issue here is that when a user requests to change their username, the system checks whether the new username already exists on the system. Since the new username is the same as the current username when doing case-insensitive comparison, this causes the check to fail. So, to fix this, there should be an additional check if the new username is the same as the current username when doing case-insensitive comparison, and if so, allow the name change anyway.

**Comment by jvanbaarsen** [comment]
I created a fix for this here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1701

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
