### ISSUE TITLE
Cannot remove project v 6.6.5

### ISSUE THREAD

**Issue by No1zzz** [gitlabhq/gitlabhq#6964]
Hello,can't remove project:
500
We're sorry, but something went wrong.
It is empty repo.
Can't look in this repo,same error.
How can i delete it?

```
Started GET "/admin/projects/tester/tester-old" for 127.0.0.1 at 2014-05-13 15:07:12 +0400
Processing by Admin::ProjectsController#show as HTML
  Parameters: {"id"=>"tester/tester-old"}
Completed 500 Internal Server Error in 40ms

Rugged::ReferenceError (Reference 'refs/heads/master' not found):
  app/models/repository.rb:8:in `new'
  app/models/repository.rb:8:in `initialize'
  app/models/project.rb:177:in `new'
  app/models/project.rb:177:in `repository'
  app/controllers/admin/projects_controller.rb:45:in `repository'
  app/controllers/application_controller.rb:57:in `set_current_user_for_thread'


Started GET "/admin/projects/tester/tester-old" for 127.0.0.1 at 2014-05-13 15:07:13 +0400
Processing by Admin::ProjectsController#show as HTML
  Parameters: {"id"=>"tester/tester-old"}
Completed 500 Internal Server Error in 38ms

Rugged::ReferenceError (Reference 'refs/heads/master' not found):
  app/models/repository.rb:8:in `new'
  app/models/repository.rb:8:in `initialize'
  app/models/project.rb:177:in `new'
  app/models/project.rb:177:in `repository'
  app/controllers/admin/projects_controller.rb:45:in `repository'
  app/controllers/application_controller.rb:57:in `set_current_user_for_thread'
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
