### ISSUE TITLE
Jira issue id in commit message doesn't get converted to HTML link

### ISSUE THREAD

**Issue by just-a-dev** [gitlabhq/gitlabhq#6975]
I configured my gitlab.yml as indicated at https://github.com/gitlabhq/gitlabhq/blob/master/doc/integration/external-issue-tracker.md. 

I can now get issues link on projects go to Jira as well as "new issue" on project dashboard link takes to create new Jira screen.
However, I can't get the Jira issue id in commit messages to show up as link. According to the document, it should work. 

What am I missing?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues). Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
