### ISSUE TITLE
unicorn timeout on each push (second or third try will sucess)

### ISSUE THREAD

**Issue by lippoliv** [gitlabhq/gitlabhq#6978]
Hey there,
this week I updated from 6.4.3 with the Update-Script to 6.8.1, also I updated the git-shell as mentioned in the Install-Advice.

But now I can't push anymore. I can push, but I have to do it two or three times, until it will work :/

I get an "Read timeout" on client side, server logs in unicorn.stderr.log:

	I, [2014-05-14T11:30:30.320705 #12824]  INFO -- : worker=0 ready
	E, [2014-05-15T06:35:36.320349 #3324] ERROR -- : worker=0 PID:12824 timeout (61s > 60s), killing
	E, [2014-05-15T06:35:36.341969 #3324] ERROR -- : reaped #<Process::Status: pid 12824 SIGKILL (signal 9)> worker=0
	I, [2014-05-15T06:35:36.349702 #25225]  INFO -- : worker=0 ready

My gitlab runs on an vps wich is definetly big enough, there is no high traffic on the gitlab-instance.

What can I do to fix it or is it an gitlab bug?

Regards,
  Oli

**Comment by anfy2002us** [comment]
After 2 days of battle,  setiing unicorn workker_process = 2 solved my issues.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
