### ISSUE TITLE
Event list is not updated

### ISSUE THREAD

**Issue by jublo** [gitlabhq/gitlabhq#6980]
After installing GitLab on a different server and restoring with a rake backup restore, the event list on the GitLab home page (and the project event pages) is not updated. In a project's commit list, the commits show up.

When editing issues, these events get added to the event list, while pushed commits are not.

- GitLab 6.8.1
- Ubuntu 14.04 LTS
- Apache 2.4.7
- MySQL 5.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
