### ISSUE TITLE
Blame view shows wrong information

### ISSUE THREAD

**Issue by bspinner** [gitlabhq/gitlabhq#7001]
Hello folks,

For some repositories, gitlab shows wrong commits/authors in blame view. Here's a comparision between gitlab and git extensions:

edit: Look at screenshots in comment below

Unfortunately we couldn't find the reason for this, yet.

Using GitLab 6.9.1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
