### ISSUE TITLE
Browse folder with high number of files crashes browser.

### ISSUE THREAD

**Issue by alvarocnic** [gitlabhq/gitlabhq#7003]
Hi!

I have a folder on a repository with 1300 files. When I go to this folder Firefox and Chrome browsers crash.
There is a Javascript script running which crashes the browser.

I know this is something unusual, but makes my repository unusable.

Thank you!

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by alvarocnic** [comment]
That's perfect.

Thanks!
