### ISSUE TITLE
Comments in merge request commits are no longer displayed

### ISSUE THREAD

**Issue by kemenaran** [gitlabhq/gitlabhq#7006]
When commenting on a commit belonging to an MR, the comments are not displayed on the MR page. The implementation of `merge_request.rb` seems to indicate that it [should be the case](https://github.com/gitlabhq/gitlabhq/blob/master/app/models/merge_request.rb#L185-195) though.

Steps to reproduce:

* Open a new MR with some commits
* Open a commit's page, and add a comment to the commit
* Go back to the MR page

Expected results:

* The commit comment is displayed on the MR page

Actual result:

* The commit comment is not visible on the MR page

Reproduced on GitLab 6.8. May be related to #6571.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
