### ISSUE TITLE
Merge requests can not be accepted if a branch and a tag have the same name

### ISSUE THREAD

**Issue by oblique** [gitlabhq/gitlabhq#7008]
Assume that you have a branch called `foo` and a tag called `foo`, when you go to accept merge request for that branch then git can not push it from satelite to the repository.
The error is the following:
```
ERROR -> Command failed [1]: /usr/local/bin/git --git-dir=/home/git/gitlab-satellites/dev/proj/.git push origin foo
error: src refspec foo matches more than one.
error: failed to push some refs to '/home/git/repositories/dev/proj.git'
```

The solution is to use `refs/heads/foo` instead of just `foo` in the git command, so it will know that it must push the branch.

I know that it's a bad practice to have the same name for a tag and a branch but some users do that mistake.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
