### ISSUE TITLE
Keep source and dest branch when changing them

### ISSUE THREAD

**Issue by hithwen** [gitlabhq/gitlabhq#7026]
Step to reproduce (on 6.9.0)
1. Push
2. Go to gitlab, click on Create merge request
3. Dest branch defaults to master (It would be nice to have this configurable)
4. Click on "Change branches"
In new form source branch is lost (dest still points to master) I have to manually select both source and dest, and this is very annoying

**Comment by janosgyerik** [comment]
This is still the case as of 7.6.2

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
