### ISSUE TITLE
Huge resources consumption increase since 6.9

### ISSUE THREAD

**Issue by hithwen** [gitlabhq/gitlabhq#7041]
Hi, I'm using munin to monitor my dev machine (where I have gitlab and a couple of other services). Since I updated to  6.9 last 26th I've noticed a considerable increase on machine load
![cpu-week](https://cloud.githubusercontent.com/assets/611228/3116733/317e5582-e71f-11e3-9b57-744f05d44694.png)
![load-week](https://cloud.githubusercontent.com/assets/611228/3116738/3b148170-e71f-11e3-9289-7118eabccf25.png)
![vmstat-week](https://cloud.githubusercontent.com/assets/611228/3116742/44d09866-e71f-11e3-91b9-ad18174b5253.png)
![irqstats-week](https://cloud.githubusercontent.com/assets/611228/3116743/46cf9716-e71f-11e3-9de6-7c017374cdf1.png)

.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
