### ISSUE TITLE
"No authentication methods configured" text when signin is disabled but omniauth is enabled

### ISSUE THREAD

**Issue by sodabrew** [gitlabhq/gitlabhq#7045]
Following up on commit aea3712e8dd71092847eeaec6f934a426d1becc0

If standard signin is disabled but an Omniauth provider is enabled, it looks like this:
![screen shot 2014-05-29 at 2 38 31 pm](https://cloud.githubusercontent.com/assets/39406/3124099/9b6023f4-e779-11e3-922b-9d2238566dc1.png)

In this scenario, the "No authentication methods configured." and the "Did not receive confirmation email?" text should both be hidden.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
