### ISSUE TITLE
Two different merge requests are created with the same ID

### ISSUE THREAD

**Issue by visual2me** [gitlabhq/gitlabhq#7048]
Two guys from our team created merge requests from their own branches at the same time, the 2 merge requests resulted with the same ID, then we can only accepted one of them and left the other untouched. Now we even can't close them. The gitlab version we are using is 6.7.5.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
