### ISSUE TITLE
Cannot transfer project to another user or create in any other user namespace as admin

### ISSUE THREAD

**Issue by nneul** [gitlabhq/gitlabhq#7051]
Summary

Equivalent issue to closed #4737 

Using 6-9-stable: As an admin user, I'm trying to transfer and existing project (or create from scratch) to another user using the transfer option in the project's settings.

Only groups and my own user show up in the dropdown.

I haven't ever seen more than just the single userid (same as logged in) show up in the Users section of the namespace dropdown. 

Steps to reproduce

log in as admin user
try to transfer a project to another user
menu shows other groups and your own user

Expected bevahior

I want to be able to move projects around as admin or create them from scratch without having to log in as the target userid.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
