### ISSUE TITLE
404 Image Upload on Issue

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#7052]
**Summary:**
Whenever I upload an image and posted it an issue(possible even in comment), it doesn't show the image that i uploaded.

**Logs:**
```
Started GET "/uploads/nette/katana/25857b313e/rawr18.png" for 112.207.110.70 at 2014-05-31 00:00:17 +0800
Processing by GroupsController#show as HTML
Parameters: {"id"=>"uploads/nette/katana/25857b313e/rawr18.png"}
Filter chain halted as :authorize_read_group! rendered or redirected
Completed 404 Not Found in 6ms (Views: 0.7ms | ActiveRecord: 0.7ms)
```

**ScreenShot:**
![rawr20](https://cloud.githubusercontent.com/assets/4362134/3132855/afab68f6-e813-11e3-8925-6134f19f6049.png)

**Related to:**
https://groups.google.com/forum/#!topic/gitlabhq/dNgZ9_wL3GA

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
