### ISSUE TITLE
Deploy key not working

### ISSUE THREAD

**Issue by hypemedia** [gitlabhq/gitlabhq#7056]
I have a Deploy key setup for a repository. The ssh is setup correctly and all the system checks pass without errors. Normal keys for users work. The problem is only related to deployment keys.

From the gitlab-shell log i can see that the key id returns null on the API.

D, [2014-05-31T09:09:30.897891 #2968] DEBUG -- : Performing GET http://git.hype.ro//api/v3/internal/discover?key_id=33
D, [2014-05-31T09:09:30.936880 #2968] DEBUG -- : Received response 200 => <null>.
W, [2014-05-31T09:09:30.937012 #2968]  WARN -- : gitlab-shell: Access denied for git command <git-upload-pack 'root/car-replacement-leaseplan.git.'> by Anonymous.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
