### ISSUE TITLE
Group Avatar: Remove Avatar Button shows up although avatar not uploaded due to error

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#7065]
**Summary:**
even when avatar get's denied due to File-size restriction, the "Remove Avatar" button shows up

![rawr23](https://cloud.githubusercontent.com/assets/4362134/3155600/fe617044-eac5-11e3-8f2c-f23199addf85.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
