### ISSUE TITLE
Files/folders named edit not viewable

### ISSUE THREAD

**Issue by darkain** [gitlabhq/gitlabhq#7071]
If you have a folder /edit/ or a file /edit.php (or any other example) in your repository, these folders and files cannot be viewed at all within the file browser. Instead, a blank page appears.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
