### ISSUE TITLE
FlowDock Doesn't Post

### ISSUE THREAD

**Issue by bassrock** [gitlabhq/gitlabhq#7076]
The Flowdock Service is not posting when certain users push on 6.9. It also does no posting with Merge Requests.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
