### ISSUE TITLE
Markdown line break not working properly

### ISSUE THREAD

**Issue by rodvlopes** [gitlabhq/gitlabhq#7083]
"but...
This line is only separated by a single newline, so it's a separate line in the *same paragraph*."

Just check the documentation and you will notice that you can´t break the line inside a paragraph. This feature is broken.

https://github.com/gitlabhq/gitlabhq/blob/master/doc/markdown/markdown.md#line-breaks

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
