### ISSUE TITLE
Logout not working without JavaScript

### ISSUE THREAD

**Issue by CSchulz** [gitlabhq/gitlabhq#7121]
As stated here in my comment and the following ones https://github.com/gitlabhq/gitlabhq/issues/7110#issuecomment-45811086 JavaScript is needed to be able to logout.

The cause is the needed CSRF token which is given via meta tags and read by JavaScript.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
