### ISSUE TITLE
Two accounts, two different ssh keys, Git cannot access the 2nd account?

### ISSUE THREAD

**Issue by leeola** [gitlabhq/gitlabhq#7125]
# Repro Steps

1. Create 1 account, and add an ssh key to it.
2. Create a 2nd account, add a different ssh key to it.
3. Run `ssh -i ~/.ssh/key1 -T git@gitlab.com`
4. Run `ssh -i ~/.ssh/key2 -T git@gitlab.com`

# What is happening

Both steps 3 and 4 will show the same account.

# What is expected

Step 3 should return account 1, Step 4 should return account 2.

Can anyone else confirm this? *(If this is the wrong place to post this issue, please point me in the right direction)*

**Comment by bborysenko** [comment]
I have the same issue.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
