### ISSUE TITLE
Confusing UI when trying to add a diff comment without being logged in

### ISSUE THREAD

**Issue by jacob-carlborg** [gitlabhq/gitlabhq#7126]
If I have a publicly visible project in Gitlab with an open merge request. If I'm not logged in and I try to add a diff comment, the following happens:
![diff_comment](https://cloud.githubusercontent.com/assets/306980/3266993/74ff633e-f2c1-11e3-95c8-51d42f0c6623.png)
An empty white line is added. It has happened to me a couple of times and each time I get confused and think there's a bug in Gitlab, because the comment form doesn't show up. What happens is I, for some reason, have been signed out.

It would be nice if it would say I need to login to be able to comment, or provide a form to login right away.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
