### ISSUE TITLE
Milestone Link

### ISSUE THREAD

**Issue by DineshAnandan** [gitlabhq/gitlabhq#7127]
**Summary** : If i click the milestone link from issue details page. 404 page not found error occur because url ended with issue number instead of milestone number.

**Steps to reproduce** : Go to issue details page in public project without log in. Then click the milestone link in right hand side. ( Refer the attached image )

**Expected behavior**: It should go to the corresponding milestone page.

![gitlab_issue](https://cloud.githubusercontent.com/assets/1436774/3267208/bee46db4-f2c6-11e3-814b-667a5c0d4546.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
