### ISSUE TITLE
Can't login through api (and gitlab-ci) using omniauth != LDAP

### ISSUE THREAD

**Issue by dpasqualin** [gitlabhq/gitlabhq#7128]
I've installed gitlab-ci, which (as you know) can integrate with Gitlab users database through the api, but this feature doesn't seem to work with omniauth authentication (kerberos).

What I've found out so far:

When I first log in through kerberos, gitlab creates an internal account for the new user with a random password. Afterwards, I'm able to log in using my kerberos login/password in the Gitlab login page, and completely ignore the random password generated, as expected.

But if I try to log in through the api, instead of looking for my kerberos login/password, the api checks only for my Gitlab account information, and the random generated password, which I don't possess.

I've tried to track the login process at the code and it seems to me that the problem is in the lib/gitlab/auth.rb file, which tries to log in using either the Gitlab or LDAP account, but not any other omniauth provider.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
