### ISSUE TITLE
Huge memory leak in latest Google Chrome

### ISSUE THREAD

**Issue by JakeDOD** [gitlabhq/gitlabhq#7129]
Gitlab has a very large memory leak in the latest stable version of Google Chrome (35.0.1916.153) 

When viewing gitlab in an open Google Chrome tab, you can watch the memory usage ramp up to close to a gigabyte in size in a relatively short period of time. Closing the tab fixes the issue (obviously), but with multiple tabs open this is a major issue because it doesn't take long for gitlab pages to suck up a lot of memory.

This was seen on both version 6.8 and the current 6.9.2. 

The memory leak does not exist in IE, and I have not tested Firefox. 
![image](https://cloud.githubusercontent.com/assets/3977749/3273738/cf5f260a-f327-11e3-85d4-4f69353230d2.png)
The ramp up of memory use ramps from having only one tab open, to having two tabs open. The first drop is the tab being closed and the then the second is the second gitlab tab being closed. My computer has 4 gigs of memory and with two tabs open I reach about a total of 2.3 GB of memory. 

A 1.5 min recording of heap allocations of the help page:
![image](https://cloud.githubusercontent.com/assets/3977749/3273839/20709794-f329-11e3-9d9d-01db736b7ced.png)

I don't have any easy way to upload snapshot data, but it is easy enough to do this yourself.

It would be awesome if this could be fixed! I can't keep gitlab open all the time because it slows my computer down to much :cry:

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
