### ISSUE TITLE
gitlab keeps sending project create system hooks after the first

### ISSUE THREAD

**Issue by pkpp1233** [gitlabhq/gitlabhq#7144]
I use the gitlab api to create projects. and i have a single system hook for my node server.

however, every time i create a project via the gitlab api, i start receiving a constant stream of system updates that the project is created. anyone know why this is happening? i'm on the 6.9 version that's available on Digital Ocean.

I try and build 30 repositories at once and it stalls after 6. Is this happening to anyone else?

**Comment by rw355** [comment]
Similar issue here, mine is recurring project create and project delete. I'm thinking is the hook response matter with gitlab's behavior? I guess there is a timeout that gitlab will resend request when it ends, is it true?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
