### ISSUE TITLE
Couldn't create new repo. Sidekiq.log says nothing unusual.

### ISSUE THREAD

**Issue by blueabysm** [gitlabhq/gitlabhq#7155]
Hi all,

I ran into an issue which I googled for a long while but got nothing. I cannot clone my repo after creation. 
Sidekiq runs normally:
````ps aux | grep sidekiq````
````git      26270  1.8  3.4 2657440 237864 ?      Sl   17:07   0:36 sidekiq 2.17.0 gitlab [0 of 25 busy]````
````501      29438  0.0  0.0 103200   780 pts/0    S+   17:40   0:00 grep sidekiq````

And here is the last piece of ````sidekiq.log````:
````2014-06-19T09:32:17Z 26270 TID-oxcfn4gy4 GitlabShellWorker JID-555f7bcc695c4005c8d385c3 INFO: start
2014-06-19T09:32:17Z 26270 TID-oxcfn4gy4 GitlabShellWorker JID-555f7bcc695c4005c8d385c3 INFO: done: 0.009 sec
2014-06-19T09:32:31Z 26270 TID-oxcfn4gy4 Sidekiq::Extensions::DelayedMailer JID-259569c646b2ab39a489f00f INFO: start
2014-06-19T09:32:31Z 26270 TID-oxcfn4gy4 Sidekiq::Extensions::DelayedMailer JID-259569c646b2ab39a489f00f INFO: done: 0.061 sec```

Everything seems to be fine.

But I checked the ````repositories```` dir: ````/home/git/repositories/[user name]/````, nothing happened.

I could create new user, and it will appear in this directory, so I guess it may not be a privilege issue.

Thanks for any of your help!

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by blueabysm** [comment]
Thank you!
