### ISSUE TITLE
Percent characters in filenames aren't properly URL encoded

### ISSUE THREAD

**Issue by Romke-vd-Meulen** [gitlabhq/gitlabhq#7157]
If I try to navigate to a file that has a percent character in the name, the URL is:

`http://gitlab/root/myproject/commits/master/path/%gconf.xml`

However, this causes nginx to return 400 Bad Request, since the percent character [isn't properly encoded](https://www.ruby-forum.com/topic/2573586). Manually going to

`http://gitlab/root/myproject/commits/master/path/%25gconf.xml`

works fine. Gitlab should encode the file URLs so that this is done by default.

**Comment by outring** [comment]
+1 here for the folder names too

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
