### ISSUE TITLE
Adding LDAP users w/o Login

### ISSUE THREAD

**Issue by badmadrad** [gitlabhq/gitlabhq#7158]
In the past I have used git management software that allows users to be added from the ldap without needing to login or have knowledge of the user's password.

Does that functionality exist in Gitlab? I have configured the ldap and I am able to see users if they login but I am unable to add any users that haven't logged in.

The reason I ask is because I am attempting to use Gitlab in large enterprise environment and want to have admins responsible for adding users. If this functionality doesn't exist are there any workarounds?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
