### ISSUE TITLE
git push fails over HTTP transport

### ISSUE THREAD

**Issue by theofidry** [gitlabhq/gitlabhq#7186]
Hi,

I recently tried to install GitLab (**GitLab 6.9.2**) on my server (**debian7**, **MySQL 5.5**, **Nginx 1.2**). No peculiar problem on the install itself and it's always a pleasure to see a great doc.

However when I tried to create a project and then push some local files into it, it fails. I properly initialized the git repo and set the url (given by the gitlab interface), and when I try to push, it once asked for my login and then the following appear:

    Counting objects: 255, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (251/251), done.
    Writing objects: 100% (255/255), 1006.81 KiB | 0 bytes/s, done.
    Total 255 (delta 73), reused 0 (delta 0)

and then... nothing, it stays like that forever and nothing happens. I tried to check the logs and all I get is:

    Started POST "/staff/myrepo.git/git-receive-pack" for 109.1.100.153 at 2014-06-23 20:37:53 +0200

If anyone could help please.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
