### ISSUE TITLE
Oauth fail

### ISSUE THREAD

**Issue by alexbagirov** [gitlabhq/gitlabhq#7203]
If I add, for example, GitHub to my account, I can log in using it later. 
If I will add Google after that, it will connect to my account but disconnect GitHub. 
If I add GitHub again, it disconnects Google.
So, I can't connect my account with all providers at one time.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
