### ISSUE TITLE
Former ldap user can not login

### ISSUE THREAD

**Issue by jcockhren** [gitlabhq/gitlabhq#7213]
When a user has ldap credentials, the system attempts to access the ldap server even if the ldap authentication is disabled in the config. The following error appears:

```
Net::LDAP::LdapError (No such address or other socket error.):
  lib/gitlab/ldap/adapter.rb:7:in `open'
  lib/gitlab/ldap/access.rb:7:in `open'
  app/controllers/application_controller.rb:203:in `gitlab_ldap_access'
  app/controllers/application_controller.rb:184:in `ldap_security_check'
```

This issue existed as #6188 before the merge with the gitlab EE codebase and was resolved with #6189.

Given the merge of the codebases, the issue resurfaced given the difference in approaches to authentication.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
