### ISSUE TITLE
Moving a repo to an «empty» namespace

### ISSUE THREAD

**Issue by MrBogomips** [gitlabhq/gitlabhq#7235]
Moving a repository to a user that have never created a repo (i.e. without a local directory on gitlab server) doesn't work… and you don't either get an error.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
