### ISSUE TITLE
500 error searching a specific repository

### ISSUE THREAD

**Issue by fearlsgroove** [gitlabhq/gitlabhq#7245]
When trying to search a specific repository, or any forks of that repository, I get a 500 error. It appears to be when trying to pass `search_files` to the repository_raw in `method_missing`. I'm fairly certain it's something amiss in my repo. How can I find out what command it's trying to run? Thanks!

From production.log:

```
Started GET "/search?group_id=&project_id=9&repository_ref=&search=foo&search_code=true&utf8=%E2%9C%93" for 127.0.0.1 at 2014-07-02 10:57:55 -0400
Processing by SearchController#show as HTML
  Parameters: {"group_id"=>"", "project_id"=>"9", "repository_ref"=>"", "search"=>"foo", "search_code"=>"true", "utf8"=>"✓"}
Completed 500 Internal Server Error in 281ms

Grit::Git::GitTimeout (Grit::Git::GitTimeout):
  app/models/repository.rb:146:in `method_missing'
  app/services/search/project_service.rb:15:in `execute'
  app/controllers/search_controller.rb:11:in `show'
```

gitlab:env:info:

```
System information
System:		Ubuntu 14.04
Current User:	git
Using RVM:	no
Ruby Version:	2.0.0p481
Gem Version:	2.0.14
Bundler Version:1.6.3
Rake Version:	10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:	7.0.0
Revision:	de9bf7d
Directory:	/home/git/gitlab
DB Adapter:	postgresql
URL:		http://gitlab.moki.lan
HTTP Clone URL:	http://gitlab.moki.lan/some-project.git
SSH Clone URL:	git@gitlab.moki.lan:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	1.9.6
Repositories:	/mnt/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git
```

Checks are all passing as well but I'd rather not include all my repository names.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
