### ISSUE TITLE
change primary email when using LDAP

### ISSUE THREAD

**Issue by waspinator** [gitlabhq/gitlabhq#7248]
When using LDAP to authenticate users, the email field of a user is automatically set to the user's UPN (user principle name - which sometimes is not a real email address). 

Adding an additional email only allows the user to be identified for commits, but notifications and avatar detection does not work. 

Is there a way to set an additional email to receive notifications and be used for avatar detection instead of the LDAP UPN?

**Comment by jampy** [comment]
Same problem here. Any suggestions?

**Comment by reillysiemens** [comment]
I'm also keenly interested in having the option for LDAP users to set their primary email. Any word on this?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
