### ISSUE TITLE
tasks: Not all projects considered

### ISSUE THREAD

**Issue by paulepanter** [gitlabhq/gitlabhq#7254]
Version: 6.2.1 (code looks the same in later versions though)

Running the Rake task `gitlab:check` not all projects are checked for correct namespace or existing satellites.

    $ sudo -u $GITLAB_USER -H bundle exec rake gitlab:check RAILS_ENV=production

Running the Rake task `gitlab:satellites:create` a satellite is also only created for a subset of the projects.

The `admin/projects` index view says there are 28 projects, while running `Project.count` in the Rails console (production environment) returns 10.

The view uses `@projects` (`@projects.total_count` from Kaminari, I guess).

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
