### ISSUE TITLE
Wrong URL for Avatar Icon on Dashboard

### ISSUE THREAD

**Issue by the-holger** [gitlabhq/gitlabhq#7261]
Hi all!

I upgraded today from 6.9.0 to 7.0.0 via the Omnibus package. Upgrade worked pretty well, but I ran into a tiny issue:
My user avatar on the dashboard (and just for my activities) is linked to as: ```https://gitlab.example.com/uploads/user/avatar/2/Owl_small.png```, which of course is not my url.
edit: This is only true for all activities that occurred before the upgrade. I just pushed something to a repo and the avatar is fine for that.

I guess it's a result of me forgetting to change that value in ```/etc/gitlab/gitlab.rb``` before I ran ```gitlab-ctl reconfigure```. 
After I noticed that I fixed ```/etc/gitlab/gitlab.rb``` accordingly (i.e. it now says ```external_url 'https://git.myrealdomain.com'```), I also added to correct options to enable https. Ran ```gitlab-ctl reconfigure``` again and no change in the avatar URLs.

Cheers!
Holger

PS: Issue is easily fixed by removing and re-adding an avatar. Was just not expecting that behaviour when changing the external_url parameter

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
