### ISSUE TITLE
Issue tracker filter panel disappears on narrow screen

### ISSUE THREAD

**Issue by thw0rted** [gitlabhq/gitlabhq#7269]
When viewing the issue tracker, if the browser is resized under about 1000px wide, the left sidebar just vanishes.  There's no apparent way to view it, or to change the current filters.  Until it occurred to me to try widening the browser, I thought there was no way to view closed issues!

If the sidebar must be hidden to accomodate a smaller width, it should either be moved above or below the content, or at least given a button to allow it to "pop over" the main content.  (I think we're running v6.8, in case that matters)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
