### ISSUE TITLE
Invalid permissions on created <repo>/objects/* folders

### ISSUE THREAD

**Issue by r-ku** [gitlabhq/gitlabhq#7284]
When i try to push via ssh folders created in /home/git/repositories/&lt;user>/&lt;repo>/objects/* are created with 660 permissions. This is clearly wrong. Umask is 0022. I even put explicit umask 022 setting to /home/git/{.profile,.bashrc}. As a result pushing fails with access error. However pushing via https transport works, folders are created with expected permissions.

This is on gitlab v7.0 (stable)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
