### ISSUE TITLE
permissions denied after failed import

### ISSUE THREAD

**Issue by koebi001** [gitlabhq/gitlabhq#7294]
During importing while creating a new repository a timeout accoutered which leads to a damaged repository.

Create a new repository and add a URL to a large repository for import. The time to import is limited. After some time a message appears about a timeout with the suggestion to clone the repository add the new one as a remote site and use the push command. Put righter pushing via ssh or https is working. Always returns permission denied. To solve the problem it is necessary to delete the repository and recreate it without to use the import function. After that it is possible to use the git push command without problems.
The repository I used has only one commit with about 350MB.

I suspect that after the timeout a damaged repository exists on the server which should get removed after the timeout occurs.

System: debian wheezy virtual machine with 2 cores and 2GB ram. Gitlab installed using the deb packlage 7.0.0-omnibus-1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
