### ISSUE TITLE
Encoding gets lost along the way

### ISSUE THREAD

**Issue by mikew** [gitlabhq/gitlabhq#7296]
We use some UTF-8 characters in our app, and they display fine in development but once passed through GitLab they are converted into random characters.

What we see:
![screen shot 2014-07-11 at 3 46 15 pm](https://cloud.githubusercontent.com/assets/4729/3557126/fb0d4e7a-092b-11e4-98f2-178f5cb11fab.png)
![screen shot 2014-07-11 at 3 46 46 pm](https://cloud.githubusercontent.com/assets/4729/3557127/fb0d7f6c-092b-11e4-90c7-07d65094c564.png)

What GitLab gives:
![screen shot 2014-07-11 at 3 46 23 pm](https://cloud.githubusercontent.com/assets/4729/3557134/0bd93a0c-092c-11e4-9f37-d69d0e212ca1.png)
![screen shot 2014-07-11 at 3 46 59 pm](https://cloud.githubusercontent.com/assets/4729/3557135/0bda0dce-092c-11e4-83df-f8e283db2be0.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
