### ISSUE TITLE
No "access to project was granted" mails for projects in group namespace

### ISSUE THREAD

**Issue by m-a-r-c-o** [gitlabhq/gitlabhq#7299]
1. Summary: I noticed that the email notification upon new project creation in group namespace is not sent.

2. Steps to reproduce: Create a new project in group namespace.

3. Expected behaviour: I would expect a notification email sent to all group members gaining access to the new project.

4. Observed behaviour: No email is sent.

Is this a bug or the wanted behaviour?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
