### ISSUE TITLE
"Resend Confirmation" Error Message Security

### ISSUE THREAD

**Issue by raacoon** [gitlabhq/gitlabhq#7301]
The "Resend Confirmation" should never confirm if an email address is present in the system or not. Instead it should always "confirm" that the email address was successfully found and the confirmation mail was sent.

Right now gitlab prompts an error like this: "Email was already confirmed, please try signing in". So an attacker can "guess" emails by pure brute force.

Here is what Troy Hunt has written about that topic:

"This practice also opens up the risk of “username enumeration” where an entire collection of usernames or email addresses can be validated for existence on the website simply by batching requests and looking at the responses. Got a list of everyone’s email address from the office and a few spare minutes to do some scripting? You can see the problem!"

Source: http://www.troyhunt.com/2012/05/everything-you-ever-wanted-to-know.html

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
