### ISSUE TITLE
Top-Level code search fails

### ISSUE THREAD

**Issue by Philzen** [gitlabhq/gitlabhq#7309]
The Search button at the very top of the screen is a real killer feature - unfortunately for me it only works within a project.

So if there is `any` selected in the Project dropdown, the code snippet i am looking for is not found.

Expected behaviour would be that it searches all projects' code - or inform the user that repository code search is only possible within a selected project (if that is the case - although this would be a serious limitation of the usefulness of the search feature)

Tested and confirmed on two separate installations:

Environment 1:
```
Gentoo 3.4.34
Gitlab 6.9.2
MySql 5.1.67
```

Environment 2:
```
FreeBsd 9.2-STABLE
Gitlab 7.0.0
PostgreSql 9.3.4
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
