### ISSUE TITLE
[diff] Last line of diff of a file fails to highlight inner line byte changes.

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#7335]
Normally, byte changes are highlighted darker by `Diffy`.

However, if it's the last line of the file, bytes changes are not highlighted.

E.g.:

![screenshot from 2014-07-19 12 06 14 gitlab diff last line both](https://cloud.githubusercontent.com/assets/1429315/3634423/6bf09bb4-0f2c-11e4-97d2-c90ff9827bd5.png)

Note how: `E` is highlighted, but `K` is not.

Live at: https://gitlab.com/cirosantilli/test0/commit/7cceb3affea757e7fe74fb861282fff83d8015b5

The highlighting  `%span.idiff` was not added.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
