### ISSUE TITLE
Milestone is never 100% despite all issues and merge requests closed Gitlab CE 7.0.0

### ISSUE THREAD

**Issue by agjmills** [gitlabhq/gitlabhq#7339]
![screenshot from 2014-07-21 09 23 12](https://cloud.githubusercontent.com/assets/1158289/3641234/9aee0a5c-10b0-11e4-8485-99dab5d31843.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
