### ISSUE TITLE
Commits from wrong user in gitlab repository (hosted online)

### ISSUE THREAD

**Issue by lucacerone** [gitlabhq/gitlabhq#7351]
I have a project I have worked on using a git repository in the last couple of years,
it contains commits I made from different computers (e.g. mine at work, mine at home),
and sometimes commits of files I modified using the web interfaces of git host services (e.g. Bitbucket). Up to now I have been the only contributor to this project.

I now have to work on this project and share it with a few collaborators. I have decided to host this project on Gitlab (https://gitlab.com), so that we can work on it privately.

I pushed my repository to Gitlab and to my surprise I discovered that some of the commits are shown to have been done by some other Gitlab user (you can see this marked in red
in the attached screenshot).

I think the issue might be do to the fact that in Gitlab there is an user with the same username I used for some commits from my laptop (it is simply my name, which was
for long how my commits appeared when I started). 

This seems a pretty serious bug to me.

First I would like to know is there a quick and dirty fix for this?
(like rewriting all the history to force use a different name).

I would like to fix this before sharing it with my collaborators.

![screenshot](https://cloud.githubusercontent.com/assets/754360/3659001/c01f6cb8-11a9-11e4-8b3a-b851428004a4.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
