### ISSUE TITLE
InvalidGitRepositoryError when submitting merge request to upstream

### ISSUE THREAD

**Issue by adrianandreias** [gitlabhq/gitlabhq#7353]
Regarding this error https://github.com/gitlabhq/gitlabhq/issues/6124#issuecomment-49605771 I've ran the "sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production" command and got all messages as green.

The first line of the output looks like this though:
Instance method "lock!" is already defined in ActiveRecord::Base, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
