### ISSUE TITLE
[v7.0.0] Namespace creation fails for LDAP user with blank space

### ISSUE THREAD

**Issue by jf1603** [gitlabhq/gitlabhq#7356]
LDAP users with sAMAccount name in format "firstname lastname" (yes, blank space) are unable to login for the first time. Existing users (created with version 6.7) still can login.

I think I narrowed the problem down to the namespace creation.

![ldap auth path problem](https://cloud.githubusercontent.com/assets/2341433/3662371/0caf9ace-11ca-11e4-8410-94b0154cf49b.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
