### ISSUE TITLE
Merge request can't be merged sometimes

### ISSUE THREAD

**Issue by randaalex** [gitlabhq/gitlabhq#7359]
Sometimes (in random periods) gitlab can't merge all MergeRequests (Merge button inactive). 
In log we have the following error:
```
July 23, 2014 10:16 -> ERROR -> Command failed [1]: /usr/bin/git --git-dir=/home/git/gitlab-satellites/activebilling/core/.git checkout -b master origin/master

error: The following untracked working tree files would be overwritten by checkout:
        db/migrate/20140721135259_add_account_id_to_notes.rb
        db/migrate/20140722075207_add_allow_subdomain_to_dns_domains.rb
        db/migrate/20140722081127_add_attachment_to_notes.rb
        db/migrate/20140722081319_drop_note_attachments.rb
        vendor/assets/javascripts/ng-upload.js
Please move or remove them before you can switch branches.
Aborting
```
```
Our environment is:
Ubuntu 12.04.3 LTS
GitLab 6.8.1
GitLab Shell 1.9.3
GitLab API v3
Ruby 2.0.0p353
Rails 4.0.3
```

Currently we resolve this issue by rebuilding satellites and reopen each MR. 
Any ideas how to fix this problem?

This issue also copied to https://gitlab.com/gitlab-org/gitlab-ce/issues/442

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
