### ISSUE TITLE
branch deletion after merge request not working, however manual branch deletion does

### ISSUE THREAD

**Issue by djdevin** [gitlabhq/gitlabhq#7367]
See https://github.com/gitlabhq/gitlabhq/issues/4293#issuecomment-50038323 for steps and also some output from the logs.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
