### ISSUE TITLE
Missing some projects in list project API

### ISSUE THREAD

**Issue by changyuheng** [gitlabhq/gitlabhq#7388]
We have more than 1,000 projects hosting by GitLab 7.0. I owned about 400.

I want to protect all branches named master of projects in a specific group. There's not any API to list all projects in a group so I simply list all projects page by page and compare the group id by myself.

I found that the number of projects I want is correct but some project IDs are the same. According to pigeonhole principle, we missed some projects. I checkout the raw data from browser, and then confirmed this issue.

This is interesting because the amount of the project is right.

GitLab version: 7.0
PostgreSQL: 9.1.13
Nginx: 1.1.19
Ubuntu Server 12.04 x86 64-bit

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
