### ISSUE TITLE
Side-by-side diff displays added lines as removed lines

### ISSUE THREAD

**Issue by jameshfisher** [gitlabhq/gitlabhq#7396]
I have a merge request on our instance of GitLab for which one hunk of the diff looks like:

    -<div class="container" role="main" id="page" ng-view> </div>
    +<div class="container -form" role="main" id="page" ng-view> </div>

This displays correctly in the "Inline Diff" viewer. However, in the "Side-by-side Diff" viewer, this displays like so.

Left-hand-side; i.e. removed lines:

    <div class="container -form" role="main" id="page" ng-view> </div>

Right-hand-side; i.e. added lines:

    <div class="container -form" role="main" id="page" ng-view> </div>

Notice that the left-hand-side is incorrect! It is displaying the added line as a removed line.

A separate hunk in this change is:

    -images_dir = "images"
    -javascripts_dir = "javascripts"
    +images_dir = "static/img"
    +javascripts_dir = "target/static/js"
    +cache_path = "target/.tmp/.sass-cache"

but this displays in "Side-by-side Diff" view as:

Left-hand-side:

    images_dir = "static/img"
    javascripts_dir = "target/static/js"

Right-hand-side:

    images_dir = "static/img"
    javascripts_dir = "target/static/js"
    cache_path = "target/.tmp/.sass-cache"

Again, notice that the left-hand-side is incorrect: those lines are added lines, not removed lines.

We are running GitLab commit `de9bf7d`.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
