### ISSUE TITLE
Underline links on hover

### ISSUE THREAD

**Issue by robbytaylor** [gitlabhq/gitlabhq#7408]
WCAG 2.0 requires that link hover / focus states have a non-colour designator (see http://www.w3.org/TR/2008/NOTE-WCAG20-TECHS-20081211/G183).

This would be an easy change to implement to improve usability for people who have problems perceiving changes in colour. It looks like all that would be required would be to remove lines 43 and 57 of typography.scss.

However, since the text decoration has been deliberately disabled I wanted to check that a pull request would be accepted before doing it.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
