### ISSUE TITLE
404 and 502 etc. files should use href="static.css" for subdirectory support

### ISSUE THREAD

**Issue by fire** [gitlabhq/gitlabhq#7418]
When loading gitlab under a subdirectory, if Gitlab used "static.css" instead of "/static.css" the stylesheets would load for the error pages. Normally the static.css would at the same level as the `404.html` etc. document so both cases should work.

    <link href="/static.css" media="screen" rel="stylesheet" type="text/css" />

becomes

    <link href="static.css" media="screen" rel="stylesheet" type="text/css" />

https://gitlab.com/gitlab-org/gitlab-ce/tree/master/public

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
