### ISSUE TITLE
UI improvement for Create project / Github cloning

### ISSUE THREAD

**Issue by RopoMen** [gitlabhq/gitlabhq#7435]
Hi,

I just had my Gitlab installed and created my first repository from one Github repository. I entered all required details and added my own project description, etc.

The "problem" was that I didn't have any SSH keys added to my profile and almost immediately when I pressed "Create project" button I got "errors" that I didn't have any SSH keys added so I could not push/pull. That happened because Github project was so small and it got cloned fast.

When I pressed "Create project" only thing that I wanted to know was that "Is that Github repository cloned?" -> Was that project created successfully? Well, it was, but because the first view on project was empty (Activity) I tought that something went wrong (Didn't realize to check under the Files).

So I was like WTF, do I need SSH keys to clone that Github repository :D 

I know that when I wan't to push/pull from my own repository I need ssh keys to make things easy.

So If you could just add notification for the user like "External repository was cloned successfullly, please create SSH keys to push/pull your own repository" and everything would have been very clear =)

That's all, great job!

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
