### ISSUE TITLE
Strange inline diff output when multiple lines start with asterisks

### ISSUE THREAD

**Issue by xelan** [gitlabhq/gitlabhq#7448]
Summary:
Inline Diff shows strange output when multiple consecutive lines start with asterisks. Side-by-side Diff works correctly.

Steps to reproduce:
* Add a text file which contains multiple lines starting with asterisks (markdown file in my case)
```
Example
-------

Here comes the list
* entry one
* entry two
* entry three
```
* Commit
* Push to server
* View the commit in Gitlab

Expected behavior:
All lines should be marked with "+", followed by the line text

Observed behavior:
The first line starting with an asterisk is shown correctly, the next lines are not. The line numbers are also incorrect (see enclosed screenshots)

System:
Gitlab 7.1.1

Thanks

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
