### ISSUE TITLE
Disabling default login with LDAP not working

### ISSUE THREAD

**Issue by Th3Dan** [gitlabhq/gitlabhq#7449]
I'm using gitlab with LDAP and so I want to disable the default git login by adding

gitlab_rails['gitlab_signin_enabled'] = false

to /etc/gitlab/gitlab.rb
After that I run "gitlab-ctl reconfigure" to update the changes in all gitlab files. But I still get both login tabs. 

I found out that this can be solved by making any changes to the login-template:
1. Set gitlab_rails['gitlab_signin_enabled'] = false in /etc/gitlab/gitlab.rb
2. Run gitlab-ctl reconfigure
3. Open /opt/gitlab/embedded/service/gitlab-rails/app/views/devise/sessions/new.html.haml and append some random text at the beginning (e.g. "Test")
4. Run gitlab-ctl reconfigure again, now the default login is disabled as it should.

It looks like that something with the file cache went wrong. When I make changes to the template above and run gitlab-ctl reconfigure, it has no effect. They only have when I make changes to the template AND to the /etc/gitlab/gitlab.rb config file and then reconfigure gitlab.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
