### ISSUE TITLE
records repeat

### ISSUE THREAD

**Issue by bingeh** [gitlabhq/gitlabhq#7451]
Please look at attach image, when I visit any project activity page, the records will repeat, if I refresh this page, it will show right, no repeat inofs. It often appears(more than 90%).

On latest chrome(Version 36.0.1985.125) on OSX 10.10.
![screen shot 2014-08-07 at 12 17 51](https://cloud.githubusercontent.com/assets/535675/3837310/e31e8c92-1dea-11e4-96c8-7cbd4addeb7e.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
