### ISSUE TITLE
Tag page doesn't show tags on

### ISSUE THREAD

**Issue by rodrigozrusso** [gitlabhq/gitlabhq#7453]
Hi,

If I create a new project and push code from a existing git repository, I can't see any tag on TAG Page.
This problem is on GitLab 7.0.0 d1e424b

Step-by-step to simulate the problem:
1) Using UI, access New Project page (http://gitlab.qa.ci.vmcommerce.intra/projects/new)
2) Fill fields:
* Project Name
* Visibility Level = private
3) Is a existing repository, so as indicated I execute the commands inside the git folder
    git remote add origin git@<mygitlab_url>:<my_user>/<my-project>.git
    git push -u origin master
4) Go to Tag Page (http://<my-gitlab-url>/<my-user>/<my-project>/tags
*Number of Tags 0 (zero)
5) Push tags
    git push --tags
6) Refresh Tag Page and on the TAB appears the number of tags, but on the but there isn't any tag.

Work around to see the tags
-------------
If I create a new tag with button "New Tag", after that, all tags began to appear on the Tag Page.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by lexkastro** [comment]
Please, could someone tell me which version or commit correct that?  I've got the same problem in v7.13.5.
