### ISSUE TITLE
Email is not sent for comment where a user is mentioned

### ISSUE THREAD

**Issue by blicksky** [gitlabhq/gitlabhq#7460]
I mentioned another user (using the @username syntax) in a merge request comment, and they did not receive an email about that particular commit. However, they were added to the merge request such that they received an email for every subsequent comment.

The use case here was that I wanted this other user's input for that particular comment thread. This behavior did not serve our use case because they were not made aware of the comment. It also had the annoying side effect of them being spammed with emails related to other comments that they did not need to see.

In the very least, a user should receive an email about a comment in which they were mentioned.

Additionally, it would be nice if they were not also added to the merge request such that they receive notifications about everything from that point on. Ideally, there would be another interface for adding and removing users to and from the merge request.

Our help page reports that we are running "GitLab 7.1.1 facfec4".

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
