### ISSUE TITLE
Admin should be able to create project in any group

### ISSUE THREAD

**Issue by mcfedr** [gitlabhq/gitlabhq#7469]
When going via the admin area, it should be possible to make a new project in any group, not just groups that the admin is a member of.

At the moment only the admins own groups shows.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
