### ISSUE TITLE
Newly pushed branch does not show up during creating merge request

### ISSUE THREAD

**Issue by rtnpro** [gitlabhq/gitlabhq#7491]
Pushing a new branch in Gitlab 7.1 reflects under branches: /<namespace>/<repo>/branches but does not show up during creating a new merge request until we clean the cache manually. Please help us work around this issue.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
