### ISSUE TITLE
"Accept merge Request" Error

### ISSUE THREAD

**Issue by anrizal** [gitlabhq/gitlabhq#7543]
Hello,

I have problem Accepting merge request via web ui.

The error log says

August 19, 2014 11:50 -> ERROR -> Command failed [1]: /usr/local/bin/git --git-dir=/home/git/gitlab-satellites/rizal/test/.git push origin master

remote: GitLab: You are not allowed to access master!
remote: error: hook declined to update refs/heads/master
To /home/git/repositories/rizal/test.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to '/home/git/repositories/rizal/test.git'

after a quick digging, the error cause by the following check in /home/git/gitlab-shell/lib/gitlab_update.rb

if api.allowed?('git-receive-pack', @repo_name, @actor, @ref_name, @oldrev, @newrev)

this check is define in /home/git/gitlab-shell/lib/gitlab_net.rb

But I was not sure how the code is actually doing the check, since I am not taht familiar with openssh. does it involves public key in authorized_key file?

also, if I comment out the  - api.allowed?('git-receive-pack', @repo_name, @actor, @ref_name, @oldrev, @newrev) - the error does not happen. But I am not sure whether it will messed up other stuff.

Any hint and help would be apreciated. Thank you

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
