### ISSUE TITLE
CentOS git push Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

### ISSUE THREAD

**Issue by enira** [gitlabhq/gitlabhq#7546]
I am getting the following error when trying to push to GitLab:

Pushing to git@<ip>:<group>/<project>.git
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Followed procedure:
Clean install:
wget https://downloads-packages.s3.amazonaws.com/centos-6.5/gitlab-7.1.1_omnibus-1.el6.x86_64.rpm
sudo yum install openssh-server
sudo yum install postfix # Select 'Internet Site', using sendmail instead also works, exim has problems
sudo rpm -i gitlab-7.1.1_omnibus-1.el6.x86_64.rpm

sudo nano /etc/gitlab/gitlab.rb # changed host

sudo gitlab-ctl reconfigure
sudo lokkit -s http -s ssh

Inside GitLab: group, added project push to provided url and added SSH key to user pushing.

What is wrong?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
