### ISSUE TITLE
Gitlab projects disappeared, can't push to repo anymore

### ISSUE THREAD

**Issue by ncornu** [gitlabhq/gitlabhq#7566]
I have some projects in my gitlab.
I was able to push to it.

I did try to push to it and got:

Access denied.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I don't see the projects on Gitlab anymore. The git repositories still exist in /home/git/repositories

Post on SO
http://stackoverflow.com/questions/25416664/gitlab-projects-disappeared-cant-push-to-repo-anymore?noredirect=1#comment39654581_25416664

**Comment by Murazaki** [comment]
I have a similar issue. I installed gitlab on my apache server through passenger, and sometimes I see that the repo are empty.
When checking the content of my "repositories" folder, the folder is clearly empty...

I'm using Gitlab 7.5 stable.

**Comment by Murazaki** [comment]
It's been three or four times now. My repository is cleaned from any projects. The rest of my site remains untouched. I'm wondering if gitlab-shell is not cleaning them ?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
