### ISSUE TITLE
Filter issues by labels bug in 7.2

### ISSUE THREAD

**Issue by fonica** [gitlabhq/gitlabhq#7605]
Probably caused by the labels rewrite. 
7.1 was working as expected.

To reproduce just go to the issue list and use the label filter from the left sidebar. Add more than 1 label to the filter.

**Expected behavior:**
I should get only the issues that have **all** the selected labels.

**Observed behavior:**
I'm getting the issues that have **any** of the selected labels.
Every time I add a new label to the filter the number of results will increase.

[Old code](https://github.com/gitlabhq/gitlabhq/blob/v7.1.1/app/finders/base_finder.rb#L128) was using the tagged_with method from the acts-as-taggable-on gem.

[New code](https://github.com/gitlabhq/gitlabhq/blob/2c7e08745b8ed4361b9560439a721e5647973ad7/app/finders/base_finder.rb#L131) uses `IN` which is basically like multiple ORs.

**Comment by daschatten** [comment]
:+1:

**Comment by theag3nt** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
