### ISSUE TITLE
[UI] Maintain page height on merge request Discussion Changes tab switch on first load.

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#7608]
1. Open `/namespace/project/merge_requests/1`
2. Move "Discussion" to the middle of the screen height
3. Click "Changes"

Expected outcome: either of:

1. "Discussion" and "Changes" are at the same height as before
2. they are at the top of the page (if there is enough content to show)

Actual outcome: "Discussion" is at the bottom of the page: we got moved to the top.

Why it happens: on the first change to "Changes", it gets Ajax loaded, "Discussion" tab contents get replaced by the loader image which is very small, and that forces the page to go up because there is not enough content to show.

The bug is made worse by the fact that this only happens on the first tab load: when the tab is loaded the small loader does not appear, and heights don't change anymore, so it feels inconsistent.

If we chose expected solution 2., it suffices to add one ID to the div that holds all the tabs and link to it.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
