### ISSUE TITLE
Gitlab Crashes when clicking merge requests (error 500)

### ISSUE THREAD

**Issue by spuder** [gitlabhq/gitlabhq#7618]
When a user attempts to make a merge request, gitlab returns an error 500

Looking at the log, it shows the following error

```
Started POST "/main/builder/merge_requests" for 127.0.0.1 at 2014-08-27 11:25:23 -0600
Processing by Projects::MergeRequestsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxxxxxxxxxx", "merge_request"=>{"title"=>"Develop", "description"=>"testing merge requests", "assignee_id"=>"", "milestone_id"=>"", "source_project_id"=>"79", "target_project_id"=>"79", "target_branch"=>"master", "source_branch"=>"develop"}, "project_id"=>"main/builder"}
Completed 500 Internal Server Error in 760ms

RuntimeError (expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS):
  app/models/merge_request_diff.rb:146:in `reload_diffs'
  app/models/merge_request_diff.rb:44:in `reload_content'
  app/services/merge_requests/create_service.rb:9:in `execute'
  app/controllers/projects/merge_requests_controller.rb:96:in `create'
  app/controllers/application_controller.rb:59:in `set_current_user_for_thread'
```

This is reproducable everytime, It only happens on 1 project. 

I won't paste the output of the rake tests, however everything looks correct. 

    cd /home/git/gitlab/ && sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production
    cd /home/git/gitlab/ && sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production

I've verified that the repositories directory is clean, the gitlab-satellites directory is clean. 

Running gitlab 6.9. What else can I check? 

```
root@gitlab:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production

System information
System:		Ubuntu 12.04
Current User:	git
Using RVM:	no
Ruby Version:	1.9.3p0
Gem Version:	2.4.1
Bundler Version:1.5.3
Rake Version:	10.3.1
Sidekiq Version:2.17.0

GitLab information
Version:	6.9.2
Revision:	8759577
Directory:	/home/git/gitlab
DB Adapter:	mysql2
URL:		https://gitlab.foobar.com
HTTP Clone URL:	https://gitlab.foobar.com/some-project.git
SSH Clone URL:	git@gitlab.foobar.com:some-project.git
Using LDAP:	yes
Using Omniauth:	no

GitLab Shell
Version:	1.9.4
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
