### ISSUE TITLE
Snippet leading and trailing whitespace not rendering, not present in snippet edit.

### ISSUE THREAD

**Issue by bushong1** [gitlabhq/gitlabhq#7637]
When I create a snippet with leading or trailing whitespace like:

```javascript




asdf




```

The rendering of it seems to remove the whitespace, and it's not present on the edit page.

Image 1: Creating the snippet
![selection_011](https://cloud.githubusercontent.com/assets/236700/4091989/219192a8-2f8e-11e4-953f-1560fbee206e.png)

Image 2: After save, it looks like this:
![selection_012](https://cloud.githubusercontent.com/assets/236700/4091988/218cd0c4-2f8e-11e4-938f-c51556e57adb.png)

Image 3: If I go to edit it, the whitespace is removed entirely.
![selection_013](https://cloud.githubusercontent.com/assets/236700/4091990/2191d24a-2f8e-11e4-87f9-0560a5e6417e.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by bushong1** [comment]
@Razer6 it looks like half of the issue has been fixed, but if you go to edit a snippet, the in-browser editor still chomps the leading and trailing whitespace entirely.

Additionally, if you go to search for a snippet ("asdf", for example), the whitespace surrounding a result throws off the search results like bonkers.

**Comment by Razer6** [comment]
You are right, it's not fully resolved. Opening again,

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
