### ISSUE TITLE
namespace/project_name API requiring uri-encoded / causes unnecessary complications

### ISSUE THREAD

**Issue by davidfraser** [gitlabhq/gitlabhq#7644]
The documentation for the API implies that `/api/v3/projects/namespace%2fproject_name` should be a valid way of referring to the project. However, in our system, a request like this ends up being logged as:

    Started GET "/api/v3/projects/root%252Ftest?private_token=...

On the other hand, not uri-encoding the `/` is not supported. The above problem may well be caused by our web proxy, but illustrates that this is a slightly complicated URI scheme to support. Using another character as the namespace-project_name separator would be simpler to implement without having to worry about URL encoding.

**Comment by rhymoid** [comment]
Another issue, identified in #8290, is that [Apache should be configured with `AllowEncodedSlashes NoDecode`](https://github.com/gitlabhq/gitlabhq/issues/8290#issuecomment-88355554). Apache's default, [`AllowEncodedSlashes Off`](http://httpd.apache.org/docs/2.2/mod/core.html#allowencodedslashes), causes 404s when such URLs are requested.

Personally, I think it's pretty ridiculous that a separator character is used, while designing API paths that make sense would have been *so much better*.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
