### ISSUE TITLE
[502] Limit / truncate the number of files shown on tree view. 

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#7649]
At 100,000 files it does 502 or Firefox times out.

At 10,000, it responds but Firefox dies while viewing it.

GitHub truncates at 1000, probably a good size.

- https://github.com/cirosantilli/test-diff-many-files
- https://gitlab.com/cirosantilli/test-diff-many-files/tree/master

The funny thing is, GitHub dies on the commit view because of the huge diff, but GiLab truncates it properly (after a long loading time): https://gitlab.com/cirosantilli/test-diff-many-files/commit/9ab0f32010eb98d667c73a3b46bc6485d513e098#

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
