### ISSUE TITLE
logrotate error caused by directory permissions

### ISSUE THREAD

**Issue by m-a-r-c-o** [gitlabhq/gitlabhq#7651]
Yesterday I saw multiple errors of the following form produced by logrotate when called with the gitlab configuration file:

```
error: skipping "/home/git/gitlab/log/puma.stderr.log" because parent directory has insecure
permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file
to tell logrotate which user/group should be used for rotation.
```

Because of this error logrotate is not rotating the gitlab log files.

Is there anyone else having this issue?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
