### ISSUE TITLE
rendering performance on big diff

### ISSUE THREAD

**Issue by luthur** [gitlabhq/gitlabhq#7656]
when it come to 100+ file changes, it takes too much time to render page even chrome may want to kill this page.

I install gitlab through docker.

Is there any settings to fit my request?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
