### ISSUE TITLE
Activity of dashboard not update

### ISSUE THREAD

**Issue by pacolotero** [gitlabhq/gitlabhq#7680]
After updating gitlab 6.0 to 7.2 not update activity in the dashboard, always show the same.

**Comment by jpsandiego** [comment]
I found I have this issue with a repo I imported into Gitlab - probably via gitlab-shell. I'm pretty sure I did the import before 7.4.3 upgrade, but I did not notice the activity stream was missing details until recently.

The fix to add the symlinks works for me. Maybe there could be a gitlab command/task added to fix this ("reset pre/post hooks")

I found in another repository that I think was created within Gitlab directly (and probably used the import function) has pre/post hooks are actually directly copied into the repository, vs being symlinked. It also had a bin directory and a lib that were copies of the files within the gitlab-shell directory... weird, but it's working for now...

I created a new repo as a test and the hooks directory is getting created as a symlink back to /path-to-gitlab-shell/hooks/ and there is actually a "hooks.old.1420649473" being created with 9 sample hooks.. odd but perhaps needed to enable per-repo services?

**Comment by func0der** [comment]
Okay this is what helped me.

I assume that all symlinks are correctly said like mentioned above. "Correct" does not mean linking single files, but the whole hooks folder. You can achieve that by running the command `gitlab-shell-dir/bin/create-hooks` mentioned by @qhgongzi 

After this has been all set up correctly, check your init.d script. 
Some of you even posted that the `app:check` rake job showed them that it is broken, but maybe have ignored it.
This may have had different reasons. One could be, that you are running Gitlab via Apache instead of using the forced variant of unicorn.
In that case, you have to simple take the current init.d script from `path-to-gitlab/lib/support/init.d/gitlab` and comment out all occurrences of the web server being started or checked.

The main problem with all of this was, that *sidekiq* was not running all the time. Sidekiq handles all the post commit hooks and stuff like that. If reddis has worked the whole time old activities should be worked from the queue. With the wrong timestamp though, but better than nothing.

I find the source of the error by trying to get the status of the current gitlab instance running `/etc/init.d/gitlab status`.
It gave me something like this (only here for SEO):

```
● gitlab.service - LSB: GitLab git repository management
   Loaded: loaded (/etc/init.d/gitlab)
   Active: active (exited) since Mon 2015-10-05 21:50:40 CEST; 13min ago
  Process: 18405 ExecStop=/etc/init.d/gitlab stop (code=exited, status=0/SUCCESS)
  Process: 18421 ExecStart=/etc/init.d/gitlab start (code=exited, status=0/SUCCESS)

Oct 05 21:50:38 random_hostname sudo[18422]: root : TTY=unknown ; PWD=/ ; USER=git ; COMMAND=/bin/bash -c /etc/init.d/gitlab start
Oct 05 21:50:38 random_hostname sudo[18422]: pam_unix(sudo:session): session opened for user git by (uid=0)
Oct 05 21:50:38 random_hostname gitlab[18421]: Starting the GitLab Sidekiq event dispatcher...
Oct 05 21:50:38 random_hostname gitlab[18421]: /etc/init.d/gitlab: 139: /etc/init.d/gitlab: script/background_jobs: not found
Oct 05 21:50:40 random_hostname gitlab[18421]: GitLab is not running.
Oct 05 21:50:40 random_hostname sudo[18422]: pam_unix(sudo:session): session closed for user git
Oct 05 21:50:40 random_hostname systemd[1]: Started LSB: GitLab git repository management.
```

So, try that out, please. It helped me, maybe it does the trick for you, two.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
