### ISSUE TITLE
Group page：activity is blank,and show wrong projects count

### ISSUE THREAD

**Issue by surmountli** [gitlabhq/gitlabhq#7687]
1.some groups‘s projects count is right,some groups is wrong;
2.in group page,projects is 2,but in group settings-->projects is 4. Or projects show is 0,but there is 13 projects in group.
3.in admin/group/group_name page, the count of projects is right. 

check log ,no error.

for example:

Production environment is 6.0. The test environment is 7-2-stable .All of them are so

![image](https://cloud.githubusercontent.com/assets/4261642/4147010/1e01b7f6-3413-11e4-90ca-5b848653eaca.png)

![image](https://cloud.githubusercontent.com/assets/4261642/4147018/3fe779c8-3413-11e4-9099-9a435503caa7.png)

![image](https://cloud.githubusercontent.com/assets/4261642/4147029/613fe592-3413-11e4-9820-be525ad628ab.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
