### ISSUE TITLE
Case-sensitive search or not?

### ISSUE THREAD

**Issue by mieciu** [gitlabhq/gitlabhq#7688]
Hello,

I'm facing such a situation, which may somehow relate to https://github.com/gitlabhq/gitlabhq/issues/3108 :
When entering some text in a search bar I immediately get some matches (not case sensivitve, so that's cool), but after hitting Enter I'm redirected to a 'search results' page on which search results ARE case sensitive.

I think it's a bit confusing, because after displaying some matching projects and hitting enter people just expect to see the same results on the results page after redirection.

But please correct me if it's intentional behaviour of the app.

I'm running Postgres 9.1.13, GitLab 7.2.1.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
