### ISSUE TITLE
LDAP users that don't pass the filter get the account created anyway.

### ISSUE THREAD

**Issue by wsouto** [gitlabhq/gitlabhq#7690]
So I have this situation where a user that don't match the filter condition on my ```user_filter``` parameter for LDAP in the ```gitlab.yml``` (```gitlab:check``` correctly don't list the user) get the account created as a valid user.

He cannot login as expected tho but the account is there...

Is that behavior expected?

**Comment by thajek** [comment]
Issue seems to still be present on GitLab 7.8.1 e2d785c CE.

**Comment by jonakarl** [comment]
A side effect of this is that if you create a local user that has a email adress in the ldap catalog but are filtered out by the ldap filter, eg a student that should have acces to a "staff" gitlab installation (under the assumption that both students and staff are in the same ldap catalog)

If this user by mistake try to log on via the "ldap tab" the accounts will be linked and the user can after this not log on as he/she is filtered in the ldap filter. The only solution (as I know) to solve this is to remove the account and create a new account for this user.

**Comment by thajek** [comment]
Issue seems to still be there for GitLab 7.10.0 5dd1deb CE.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
