### ISSUE TITLE
"mentioned in commit" is not shown for tags

### ISSUE THREAD

**Issue by simonzack** [gitlabhq/gitlabhq#7701]
If I push a tag that's not on a branch, then "mentioned in commit" is not shown.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
