### ISSUE TITLE
LDAP authentication over SSL

### ISSUE THREAD

**Issue by cdenneen** [gitlabhq/gitlabhq#7703]
Currently I am able to do LDAP authentication over plain non-SSL.
I am able to do an ldapsearch however using ldaps:// without problem.

"Could not authorize you from LDAP because "Ssl connect returned=1 errno=0 state=sslv3 read server certificate b: certificate verify failed".

Any help would be greatly appreciated.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
