### ISSUE TITLE
Removing and pushing to branch with existing MR makes it out of changes

### ISSUE THREAD

**Issue by zxqfox** [gitlabhq/gitlabhq#7715]
How to reproduce:
- Push something to a branch `test`
- Create MR for branch `test`
- `git push origin :test`
- `git push origin test`
- Open MR again

After rebasing branch, we removing it and pushing again. It makes existing MR empty.
It still contains old commits but `Changes` tab shows 0 changes.

How to force gitlab to refresh branch?
Probably branch removes should trigger branch cache drop or something else?

Version 7.1 community

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
