### ISSUE TITLE
Web edit file,502 error

### ISSUE THREAD

**Issue by surmountli** [gitlabhq/gitlabhq#7722]
GitLab 7.2.1 ,Redhat 6.3
Firefox,Chrome is ok, file changed,no error.
IE 9、IE10 ,when edit file on web,error 502 ,or "Your changes could not be committed, because the file has been changed" . in fact ,file changed, events has 2

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
