### ISSUE TITLE
404 after sign-in after wrong sign-in attempt

### ISSUE THREAD

**Issue by rnveach** [gitlabhq/gitlabhq#7740]
Summary: When I try to login through http://host/gitlab/ with 1 failed attempt, the successful attempt redirects me to a 404 error page.

Steps to reproduce:
1) Open browser to http://host/gitlab/ and be prompted to signin on http://host/gitlab/users/sign_in.
2) Attempt to signin but put in the wrong username. Gitlab returns "Invalid email or Password".
3) Attempt to signin again, but with the right username and password this time.

What I expect:
4) Since i started with the main page, I expected GitLab to stay on the main page at "http://host/gitlab/" and see the "Activity" status.

What actually happened:
4) Gitlab returned a 404 error with the url being "http://host/gitlab/gitlab/users/sign_in". When I manually go back to http://host/gitlab/ I am logged in and I see what I was originally expecting to see.

System information:
System: Ubuntu 12.04
Current User: git
Using RVM: no
Ruby Version: 2.0.0p353
Gem Version: 2.0.14
Bundler Version:1.6.2
Rake Version: 10.3.2
Sidekiq Version:2.17.0

GitLab information
Version: 7.1.1
Revision: facfec4

GitLab Shell
Version: 1.9.6

Gitlab is set to work in the directory /gitlab and not on the base of the domain.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
