### ISSUE TITLE
Commits should be shown in commit order, not date order, in merge request

### ISSUE THREAD

**Issue by jameshfisher** [gitlabhq/gitlabhq#7746]
Steps to reproduce:

1. git checkout m
1. git checkout -b b
1. create two new commits c1 and c2, where c1 is parent of c2, and b now points to c2, and date of c2 is older date than commit c1
1. create a merge request for b

Expected behavior: commits shown in order: c2 then c1 (reverse commit order)

Actual behavior: commits shown in order: c1 then c2 (reverse date order)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
