### ISSUE TITLE
Redmine as issue tracker - theme problem

### ISSUE THREAD

**Issue by BerndSchneider** [gitlabhq/gitlabhq#7747]
Hello,

I have added redmine as issue tracker, and it is almost working as expected. But there is one problem - after pressing "Issues", the redmine-project page is loaded, but without showing the theme. I have to reload the page, to load it correctly.

What may be the problem?

Thanks

**Comment by darkstar42** [comment]
+1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
