### ISSUE TITLE
4.2->7.1: Issue.updated_at incorrectly set to time of upgrade

### ISSUE THREAD

**Issue by bbodenmiller** [gitlabhq/gitlabhq#7750]
Sometime during the upgrade process from 4.2 to 7.1 the `updated_at` on all issues was reset to the current time as all of my issues now show as having been recently updated. A migration should be created to reset the `updated_at` time to the time of the last comment or other tracked event (like milestone addition/removal or label addition/removal). I imagine merge requests are also affected.

/cc @randx @dosire I belive this and https://github.com/gitlabhq/gitlabhq/issues/7599 should be higher priority stability fixes than new features.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
