### ISSUE TITLE
console and applicaition authentication failed some users

### ISSUE THREAD

**Issue by edib** [gitlabhq/gitlabhq#7757]
gitlab works with AD authentication. after upgrade from 6.2 to 6.9 and then 7.0. while some user with turkish capital letters in their AD ldap uid try to do console git operation it says "fatal: Authentication failed for 'http://<git.server>/repo/repo.git'. Web login works but console git ops do not work.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
