### ISSUE TITLE
Bad highlighting of search result

### ISSUE THREAD

**Issue by frenzymadness** [gitlabhq/gitlabhq#7761]
Hi.

I have self-hosted GitLab version 7.2.1 ff1633f.

I have project with configuration of network devices. When I search for some IP address in configuration, I get correct results with correct line highlited.
![screen1](https://cloud.githubusercontent.com/assets/5688939/4301504/eb3e4d56-3e4f-11e4-8d02-6c322f8b03be.png)

But when I click to file name to see search result in better context, I see that highlited line is two lines above previous highlited line and doesn't match previous search result.
![screen2](https://cloud.githubusercontent.com/assets/5688939/4301510/fb6ffbca-3e4f-11e4-989e-509a03c75616.png)

I tested this behavior on chromium and firefox - both on Linux desktop.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
