### ISSUE TITLE
Non-ascii file names aren't shown in commit view

### ISSUE THREAD

**Issue by sjbog** [gitlabhq/gitlabhq#7794]
When non-ascii characters are present in the filename of commit, that file isn't displayed. No http 50x errors.
File content, when contains non-ascii, can't be displayed.

Commit messages with non-ascii chars are ok.

Version : GitLab 7.2.1 ff1633f

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
