### ISSUE TITLE
Wiki Homepage: 500

### ISSUE THREAD

**Issue by psugand** [gitlabhq/gitlabhq#7796]
I have just upgraded to the latest version of Gitlab and I'm experiencing issues trying to get the Wiki pages to function correctly.

The error is as follows:

Started GET "/mobivate/documentation/wikis/home" for 127.0.0.1 at 2014-09-19 14:29:55 +0000
Processing by Projects::WikisController#show as HTML
  Parameters: {"project_id"=>"project/documentation", "id"=>"home"}
Completed 500 Internal Server Error in 42ms

Grit::GitRuby::Internal::LooseObjectError (object file too small):
  app/models/project_wiki.rb:68:in `find_page'
  app/controllers/projects/wikis_controller.rb:14:in `show'

I have tried looking at both the files in question and tried to locate the Grit:: but cannot seem to find anything.

Is anyone else experiencing this issue? Has anyone managed to solve it?

System information
System:		Ubuntu 13.10
Current User:	git
Using RVM:	no
Ruby Version:	2.1.2p95
Gem Version:	2.2.2
Bundler Version:1.7.3
Rake Version:	10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:	7.2.2
Revision:	3a4ad05
Directory:	/home/git/gitlab
DB Adapter:	mysql2
URL:		http://gitlab.mobivate.com
HTTP Clone URL:	http://gitlab.mobivate.com/some-project.git
SSH Clone URL:	git@gitlab.mobivate.com:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	1.9.8
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git

**Comment by conradjones** [comment]
I am getting the same error. On gitlab 7.6.2 16f0968

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
