### ISSUE TITLE
gitlab web-ui not show all files changes

### ISSUE THREAD

**Issue by lexeress** [gitlabhq/gitlabhq#7799]
When i open commit i see
Showing 3 changed files with 145 additions and 134 deletions 

This is not binary files, just css/js files, but i see only 2 diff, no error in logs files, not see add comment form (only if files in commit <2).  6.1 6.2 7.1 7.2 version tested. 

In log file i see

````
Started GET "/aa/test/notes?target_id=3929c77e946236a025913a3211c7f384c3b0dad9&target_type=commit&last_fetched_at=1411167235" for 0.0.0.0 at 2014-09-19 22:54:09 +0000
Processing by Projects::NotesController#index as JSON
  Parameters: {"target_id"=>"3929c77e946236a025913a3211c7f384c3b0dad9", "target_type"=>"commit", "last_fetched_at"=>"1411167235", "project_id"=>"aa/test"}
Completed 200 OK in 53ms (Views: 0.5ms | ActiveRecord: 3.9ms)
Started GET "/aa/test/blob/4167460b9b51ae5a61c194293881733364587e0e/client/app-test-store/src/main/client-script/app/data/Response.js" for 0.0.0.0 at 2014-09-19 22:54:15 +0000
Processing by Projects::BlobController#show as HTML
  Parameters: {"project_id"=>"aa/test", "id"=>"4167460b9b51ae5a61c194293881733364587e0e/client/app-test-store/src/main/client-script/app/data/Response.js"}
Completed 200 OK in 186ms (Views: 115.4ms | ActiveRecord: 6.1ms)
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
