### ISSUE TITLE
Comment API improvement

### ISSUE THREAD

**Issue by zlx** [gitlabhq/gitlabhq#7813]
Hi, Guys

I'm work on a project to automatically review code syntax, like [hound](https://github.com/thoughtbot/hound) did, but for gitlab project. now I have meet some problems:

***I want to add some comments on special line in a MR.!!***
And I find an API `POST /projects/:id/merge_request/:merge_request_id/comments`, but it do not support assign line and line_path.

Thanks [Jeroen Jacobs](https://gitlab.com/u/jeroenj), with the patch https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/137, I can add some commets with line and line_path to special commit.

but things seems more complex than that, if I use the new API(comment on special commit), I need to know which commit does the change file belongs to, I can not find any API can provide this.

maybe I'm missing somethings. Can anybody help me?

**Comment by giedriusr** [comment]
:+1: this is exactly what I've been looking for today! :)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
