### ISSUE TITLE
Regression of "GitLab should use 'git log --follow'"

### ISSUE THREAD

**Issue by CSchulz** [gitlabhq/gitlabhq#7832]
I think it is better to open an new issue for this bug, see #1954.

This bug can be found in 7.2 and 7.3 again.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
