### ISSUE TITLE
Poorly styled code blocks

### ISSUE THREAD

**Issue by jbrooksuk** [gitlabhq/gitlabhq#7840]
Since 7.4, inline code blocks are barely differential between the code and the message.

![image](https://cloud.githubusercontent.com/assets/246103/4386349/75e01618-43cf-11e4-9255-2689b4491032.png)

Just removing the override color of `#555` is good enough.

https://github.com/gitlabhq/gitlabhq/blob/79a4da907dbeb0ba868baa092ef3ca0c01d638e9/app/assets/stylesheets/main/mixins.scss#L111

**Comment by okdana** [comment]
A related side-effect of this rule for `p > code` is that in-line code looks different depending on whether it's within a `p` tag or not. Something that i see very commonly in documents on our server is a list with a `code` tag preceded/followed immediately by a paragraph with a `code` tag, with the two having different font colours/sizes despite being in the same document right next to each other:

![screen shot 2015-01-19 at 04 15 54](https://cloud.githubusercontent.com/assets/122095/5798943/7fb63838-9f92-11e4-983c-691fb589e2df.png)

I can't see any good reason to have totally different styling for `p > code` than for `code` in any other document context.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
