### ISSUE TITLE
No error provided when attempting to move forked repo to group when project w/ same repository path exists

### ISSUE THREAD

**Issue by srepetsk** [gitlabhq/gitlabhq#7842]
**Summary**: Running Gitlab 7.3.0, I have a forked repository that was moved into a group. When attempting to fork the same original repository and moving it in to the same group, I get the "Saving project" loading page, which never ends. Gitlab should provide an error or refuse to perform this action if a repository in the group already exists with the same repository path as the second one attempting to be moved in.

**Steps to reproduce**: Create a repository and fork it into a group. Create a second fork of the same original repository and attempt to move it into the same group as the previous fork.

**Expected behavior**: An error or something to indicate that the attempted action will not succeed.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
