### ISSUE TITLE
Large horizontal table breaks UI header.

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#7872]
To me the main problem is that the header  stops and the page goes on (top right of screenshot). If the header were infinite that would be better.

![screenshot from 2014-09-27 09 22 09 huge table gitlab](https://cloud.githubusercontent.com/assets/1429315/4430026/3b3d5ddc-4617-11e4-835e-9e497a1a52a0.png)

GitHub is OK as it wraps the table, buts this makes it impossible to see large tables, so I'm not sure if it's the best behavior:
![screenshot from 2014-09-27 09 22 28 huge table github](https://cloud.githubusercontent.com/assets/1429315/4430027/4526ad4e-4617-11e4-839e-9f4557beb253.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
