### ISSUE TITLE
project hooks Test buttons send incorrect data

### ISSUE THREAD

**Issue by wyllys66** [gitlabhq/gitlabhq#7899]
All of the project-level hook "test" buttons (used to test a hook) send the same notification (push format). The "Issues" 'test' button should send sample data representing an 'issues' message, for example.  This does not happen.

**Comment by koglinjg** [comment]
+1, If you create a webhook that only notifies for merge request or issue or tag push and you click test hook, it will always send the json in the object format of push events.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
