### ISSUE TITLE
How to override code preview theme stylesheet

### ISSUE THREAD

**Issue by demisx** [gitlabhq/gitlabhq#7908]
Currently, in `white` code preview theme the code snippets written inside tripple backticks show comments in green color set by https://github.com/gitlabhq/gitlabhq/blob/8ebe769f267647110846a976e5f0d8fb77cd4abb/app/assets/stylesheets/highlight/white.scss#L28

I want all comments to be grayed out. What would be the recommended way to override this stylesheet, so it's compatible with future releases? Thx.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
