### ISSUE TITLE
Graph is smoothed out over months with no commits

### ISSUE THREAD

**Issue by simonzack** [gitlabhq/gitlabhq#7955]
The graph is smoothed out using the peaks over months with no commits, which is rather confusing. I think the smoothing factor should be much lower than it is now, or there can be a way of adjusting it, with no smoothing for showing raw data.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
