### ISSUE TITLE
Must delete "Hooks" to push origin master

### ISSUE THREAD

**Issue by infinityartworx** [gitlabhq/gitlabhq#7968]
When i create new project i add a remote origin ( must enter the full path to the repo, strange )
git remote add origin git@git.user1.com:/home/git/repositories/user1/test.git
Then the Gitlab worker creates /home/git/repositories/user1/test.git
i am forced to delete /home/git/repositories/user1/test.git/hooks
in order to push. This is what i get:

Counting objects: 2240, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2198/2198), done.
Writing objects: 100% (2240/2240), 5.64 MiB | 4.51 MiB/s, done.
Total 2240 (delta 251), reused 0 (delta 0)
remote: GitLab: You are not allowed to access master!
remote: error: hook declined to update refs/heads/master
To git@git.user1.com:/home/git/repositories/user1/test.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'git@git.user1.com:/home/git/repositories/user1/test.git'

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
