### ISSUE TITLE
500 on blob show if filename has .atom extension

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#7996]
Live: https://gitlab.com/cirosantilli/test0/blob/8649cbaaae92ee2c5e42811897f710d5ce7ffc19/a.atom

Routing bug.

Reminds me of: https://github.com/gitlabhq/gitlabhq/pull/7977

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
