### ISSUE TITLE
remote: hooks/update:11:in `require_relative': cannot load such file

### ISSUE THREAD

**Issue by huangxinms** [gitlabhq/gitlabhq#7997]
my version of gitlab is 7.3.1

when I push a file to the server, The error is 

Counting objects: 5, done.
Writing objects: 100% (3/3), 278 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: hooks/update:11:in `require_relative': cannot load such file -- /home/git/repositories/huangxin/helloworld.git/lib/gitlab_update (LoadError)
remote: 	from hooks/update:11:in `<main>'
remote: error: hook declined to update refs/heads/master
To http://10.10.121.47/huangxin/helloworld.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'http://10.10.121.47/huangxin/helloworld.git'

And then I open the folder "/home/git/repositories/huangxin/helloworld.git",  but the "lib" folder is not exist.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
