### ISSUE TITLE
[UI] Header anchor link on rendered markdown issue description jumps over border

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#8002]
Looks bad IMHO, the link should fall entirely inside the description area (gree border in screenshot)

Live: https://gitlab.com/cirosantilli/test0/issues/9

![screenshot from 2014-10-09 14 42 59 header link jumps out of issue border](https://cloud.githubusercontent.com/assets/1429315/4576309/f7e0b8e6-4fb1-11e4-8009-e203fbf7e0c8.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
