### ISSUE TITLE
Commit date show doesn't handle timezone settings

### ISSUE THREAD

**Issue by Soullivaneuh** [gitlabhq/gitlabhq#8014]
If you change timezone on application.rg (e.g. 'Europe/Paris'), time showing are changed except to the commit list.

Every commit just show date and time based on Git repositories information which set his own timezone.

A dirty fix would be on `app/views/projects/commits/_commit.haml`:
```ruby
#{time_ago_with_tooltip(commit.committed_date.getutc.in_time_zone('Europe/Paris'))} &nbsp;
```
Replace `Europe/Paris` by the config TimeZone.

I think it would be the same for every date coming from git repositories data.

How can we do a proper fix ?

**Comment by TurkeyMan** [comment]
I can't believe this issue exists. This should be marked critical.
The commit history shows times in UTC (which is a long way from my timezone), and also the commit graphs seem to show our engineers to their best work at 3am ;)

I set timezone = EST in gitlab.rb before I configured, but it doesn't seem to have made any difference.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
