### ISSUE TITLE
Gitlab-Shell doesnt support a https: gitlab_url with SNI enabled

### ISSUE THREAD

**Issue by Vespasian** [gitlabhq/gitlabhq#8018]
SSH login using gitlab-shell will fail if the server specified at gitlab_url has https and SNI enabled.
For a gitlab at the same host this can be fixed by using the http://127.0.0.1:8080

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
