### ISSUE TITLE
'New Issue' button misplaced

### ISSUE THREAD

**Issue by ajh17** [gitlabhq/gitlabhq#8022]
Browser: Safari 8.0 (10600.1.25)
Computer: Retina Macbook Pro
OS: OS X Yosemite

Hi,

The new issue button is misplaced as shown in the attachment. It seems to be Safari (8.0 only?) specific as both Firefox and Chrome display it correctly. Yes, both the browser and the OS are in the beta stages but have entered the 'GM candidate' stage, so I thought it would be a good idea to report this now.

![misplaced](https://cloud.githubusercontent.com/assets/1159146/4608632/24924c44-5285-11e4-9e57-93cba4c0e055.png)

-- Akshay.

**Comment by kkoudev** [comment]
I'm too.
Also it occurs in the same way merge request page. (v7.10.3)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
