### ISSUE TITLE
add redis requirepass  sidekiq.log appear:ERROR: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by geekwolf** [gitlabhq/gitlabhq#8049]
1. add redis requirepass  geekwolf,
2. then vim  gitlab-shell/config.yml
redis:<br>
bin: /usr/bin/redis-cli <br>
host: 127.0.0.1<br>
port: 6379<br>
pass: geekwolf # Allows you to specify the password for Redis<br>
database: 0<br>
socket: /var/run/redis/redis.sock # Comment out this line if you want to use TCP<br>
namespace: resque:gitlab<br>

3.service gitlab restart
4.the  sidekiq.log appear:ERROR: NOAUTH Authentication required. and  code 500

But when cancel the requirepass  , the gitlab runs well!  how to solve the problem? thx

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
