### ISSUE TITLE
Gitlab shows 500 when searching project names that been deleted

### ISSUE THREAD

**Issue by sqander** [gitlabhq/gitlabhq#8050]
Hi,

I noticed that when I do searches for names that happened to be removed project names, 500 shows. Is this a bug or is there a solution. I have 6.9 installed. Can you confirm this?

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
