### ISSUE TITLE
revert GitLab update instructions incomplete

### ISSUE THREAD

**Issue by bbodenmiller** [gitlabhq/gitlabhq#8057]
Following https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/6.x-or-7.x-to-7.3.md#things-went-south-revert-to-previous-version-60 or https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/7.2-to-7.3.md#things-went-south-revert-to-previous-version-72 won't work as there is no revert instructions for the changes made on Redis to use sockets.

**Comment by aubinlorieux** [comment]
Got the same issue and I can't revert. So I'm waiting for a response on the issue #8817

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
