### ISSUE TITLE
422 page comes out when trying to sign in

### ISSUE THREAD

**Issue by LeeDhu** [gitlabhq/gitlabhq#8089]
![image](https://cloud.githubusercontent.com/assets/5831299/4692401/f7232b26-5760-11e4-85fa-2f3013f46e82.png)

then i try logging, 422 page comes out

![image](https://cloud.githubusercontent.com/assets/5831299/4692408/017382e2-5761-11e4-8be1-d91eba5d61d0.png)

however, i used to sign in and create project successfully .and i can clone and push normally eventhough cannot logging in.it suddenly goes wrong and before the worst,nothing has been changed.

can anyone help me ,thank you!

**Comment by txgruppi** [comment]
Same problem here

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
