### ISSUE TITLE
Unable to transfer existing project to group

### ISSUE THREAD

**Issue by tkambler** [gitlabhq/gitlabhq#8104]
GitLab 7.3.2 f092e53

I am the owner of "Herp" group. When I attempt to transfer an existing, private project (which I also own) to that group, the "Saving project." spinner is shown and nothing ever happens.

**Comment by doublerebel** [comment]
I am still experiencing this problem on current 7.6.2.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
