### ISSUE TITLE
git repository not created when a project is added

### ISSUE THREAD

**Issue by aspyct** [gitlabhq/gitlabhq#8132]
Hi,

I just installed a fresh gitlab on a fresh debian system.
```
Debian GNU/Linux 7
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2 x86_64 GNU/Linux
```

Followed the installation procedure on https://about.gitlab.com/downloads/ for Debian 7.
```
https://downloads-packages.s3.amazonaws.com/debian-7.6/gitlab_7.3.2-omnibus-1_amd64.deb
```
It all started smoothly.

But then I created a project, and tried to push source to the repository.
Turns out it didn't work. I kept getting "repository not found" messages.

I found the problem, eventually: while the `<project>.wiki.git` repository was created, no `<project>.git` was created. Actually sometimes it was created, but most of the time not.

So I can "fix" that by manually creating the repository. But that's not a long term solution. I don't want to have to dig into ssh every time anybody here creates a new project.

Is there any known fix for this issue?

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
