### ISSUE TITLE
Relative markdown links with double .. in rendered blobs are broken.

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#8134]
On gitlab-test create a file `files/markdown/rel.md` containing `[rel](../../README.md)`.

The rendered blob links to `gitlab-org/gitlab-test/README.md` (no branch) and breaks.

Live: https://gitlab.com/gitlab-org/gitlab-ce/blob/d0296fc9151024ef7cc43ca6906b46cb9cd9c7f9/doc/install/structure.md "keep a backup"

Whoever fixes this please add tests.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
