### ISSUE TITLE
GET raw with PRIVATE-TOKEN in header

### ISSUE THREAD

**Issue by VertigoRay** [gitlabhq/gitlabhq#8137]
# Components:
```
GitLab 7.3.2
GitLab Shell 2.0.1
GitLab API v3
Ruby 2.1.2p95
Rails 4.1.1
```

# Issue

Per the help docs, this works in the API:

```
GET http://example.com/api/v3/projects?private_token=QVy1PB7sTxfy4pqfZM1U
```

And this curl method works:

```
curl --header "PRIVATE-TOKEN: QVy1PB7sTxfy4pqfZM1U" --header "SUDO: username" "http://example.com/api/v3/projects"
```

I've tested this and this works:

```
GET http://example.com/group/project/raw/master/foo.py?private_token=QVy1PB7sTxfy4pqfZM1U
```

This does **NOT** work:

```
curl --header "PRIVATE-TOKEN: QVy1PB7sTxfy4pqfZM1U" --header "SUDO: username" "http://example.com/group/project/raw/master/foo.py"
```

I would like it to ...

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
