### ISSUE TITLE
Can't clone with HTTPS on LDAP-connected 7.4 (upgraded from 7.3)

### ISSUE THREAD

**Issue by alitheg** [gitlabhq/gitlabhq#8160]
Having got around the LDAP existing session issue, we now can't clone using HTTPS. The log shows:

```
ArgumentError (host,port,method,uid or filter,base MUST be provided):
lib/gitlab/ldap/authentication.rb:45:in `new'
lib/gitlab/ldap/authentication.rb:45:in `adapter'
lib/gitlab/ldap/authentication.rb:37:in `login'
lib/gitlab/ldap/authentication.rb:18:in `block in login'
lib/gitlab/ldap/authentication.rb:16:in `each'
lib/gitlab/ldap/authentication.rb:16:in `find'
lib/gitlab/ldap/authentication.rb:16:in `login'
lib/gitlab/auth.rb:12:in `find'
lib/gitlab/backend/grack_auth.rb:76:in `authenticate_user'
lib/gitlab/backend/grack_auth.rb:47:in `auth!'
lib/gitlab/backend/grack_auth.rb:26:in `call'
```

But we've migrated the LDAP config to the new structure and have been able to log in and out successfully on the web UI.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
