### ISSUE TITLE
Internal issue tracker is available when an external issue tracker is enabled

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#8171]
In gitlab 7.4.2 I have configured an external issue tracker and enabled. When I navigate to `http://gitlab.tld/user/project/issues/new` the New Issue form in gitlab is displayed.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
