### ISSUE TITLE
`require': No such file to load -- addressable/uri (LoadError) (upgrade 7.4.2 -> 7.4.3)

### ISSUE THREAD

**Issue by Icehunter** [gitlabhq/gitlabhq#8221]
**System Information:**
Ubuntu 12.04
GitLab 7.4.2

**Errors:**
```
==> /var/log/gitlab/unicorn/unicorn_stderr.log <==
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require': No such file to load -- addressable/uri (LoadError)

==> /var/log/gitlab/sidekiq/current <==
2014-11-01_19:28:09.90192 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require': No such file to load -- addressable/uri (LoadError)
```

**Result:**
Unicorn/sidekiq get in a failed bootloop.

**Code Reference:**

It appears that a few days ago this was merged in:

https://github.com/gitlabhq/gitlabhq/blob/8431db3326b77eab21d11ce3f4eab2636a032c07/app/models/project_services/buildbox_service.rb#L15

I don't have an issue using GitLab from source however the server I have now is omnibus based. I followed the standard upgrade doc.

Please let me know if there's more detailed info you need me to provide. Thanks!

**Comment by Icehunter** [comment]
I'll be upgrading from 7.4.2 to latest very soon. I'm sorry for the late response but I will let know know.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
