### ISSUE TITLE
User avatar can't display correctly under multi ip address

### ISSUE THREAD

**Issue by elliot-xu** [gitlabhq/gitlabhq#8226]
I got a gitlab server with multi ip address(172.16.x.x and 192.168.x.x)

When I visit 172.16.x.x and upload my avatar, avatar displays just fine, but if i visit 192.168.x.x, avatar can't display.(avatar src_path is 172.16.x.x//uploads/user/....)

Join gitlab_config.url with avatar.url maybe not a good idea. Or this could be just spec.

Life will be good if fixed.

Thanks a lot.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
