### ISSUE TITLE
Requesting to add DB revert steps in the upgrade script while reverting

### ISSUE THREAD

**Issue by lokeshkumar** [gitlabhq/gitlabhq#8227]
Hi,

We are getting a lot of issues after downgraded from 7.4.2 to 7.3.4, when analysed througn the issues we found the problems are related to the 7.4 database migration changes.

We didn't have the steps to revert the database migration changes, so i am requesting to add the steps to revert database migrations in the upgrade guide or even a separate guide for downgrade.

Regards,
Lokesh

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
