### ISSUE TITLE
[IMPRV] Clarify 'SSH keys required message'

### ISSUE THREAD

**Issue by danielsokolowski** [gitlabhq/gitlabhq#8247]
The message "You won't be able to pull or push project code via SSH until you add an SSH key to your profile" should include information that pushing using HTTPS does NOT require setting up SSH keys. 

This was not obvious to me and so also might not be to others. In my situation the implication that over 30+ users would have go through this setup process was negatively impacting our review.

How about, making the HTTPS be the default option and when user clicks on SSH the message then appears. (below the repo links) - just my humble observation.

![suggested improvement for SSH keys setup needed](https://cloud.githubusercontent.com/assets/273413/4902747/8b29170e-643b-11e4-81c4-9cb4b98d7131.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
