### ISSUE TITLE
Can't disable highlighting for specific projects or file types.

### ISSUE THREAD

**Issue by MTecknology** [gitlabhq/gitlabhq#8250]
I have some very large files and gitlab times out when trying to render them. I made the files as small as possible, but they're still going to become too large for gitlab to display. Increasing the timeout isn't a workable option either since that just delays viewing files that don't need syntax highlighting anyway.

I haven't been able to find a way to disable syntax highlighting for either a specific repository or specific file extensions. It seems both should be available, but either would do. If I'm missing it, then I need help finding it. Otherwise, this is a feature that needs to be available.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
