### ISSUE TITLE
Tags that points to non-commit objects show links to 404 and 500 on UI

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#8266]
Live: https://gitlab.com/cirosantilli/test/tags

Go for `tag-empty-blob`, which points to an empty blob:

- the tag name or tar.gz download give 404
- zip download gives 500: bug reported at: https://github.com/gitlabhq/gitlabhq/issues/8265

GitHub simply does not show such tags https://github.com/cirosantilli/test/tags I propose we don't either, or remove the broken links.

**Comment by twk3** [comment]
Tagging a tag, even from the UI, also creates a blog tag, which promptly breaks things.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
