### ISSUE TITLE
Pagination not working as expected in branches API

### ISSUE THREAD

**Issue by Batons0** [gitlabhq/gitlabhq#8270]
Changing pages in API doesn't change returned content. As far as i can see, error occurs only in branches API.

```
http://demo.gitlab.com/api/v3/projects/2/repository/branches?private_token=CPcomi7q3qyREs8wkpQz&page=1
```
```
http://demo.gitlab.com/api/v3/projects/2/repository/branches?private_token=CPcomi7q3qyREs8wkpQz&page=100
```

As you can see, results are same for both requests.

**Comment by yoelb** [comment]
There is also a bug with projects API.

api/v3/projects?private_token=...&page=1
api/v3/projects?private_token=...&page=2

these two call return common project.
I have to fill another issue?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
