### ISSUE TITLE
Editing group guest permissions.

### ISSUE THREAD

**Issue by FezVrasta** [gitlabhq/gitlabhq#8272]
I'm trying to allowing the guests of any group to create new projects.

I've edited `/opt/gitlab/embedded/service/gitlab-rails/app/models/ability.rb:191`  
replacing `rules = []` with `rules = [ :create_projects ]`.

Then I've edited `/opt/gitlab/embedded/service/gitlab-rails/app/helpers/namespaces_helper.rb:3`  
replacing the row with `groups = current_user.authorized_groups`.

And finally I've edited `/opt/gitlab/embedded/service/gitlab-rails/app/models/user.rb:379`
appending ` || authorized_groups.any?`.

In this way now guests of the groups can create new projects with the namespaces of the groups.

The problem is that they are not set as owners of the repository they create, how can I fix this last problem? Any idea?

*Disclaimer: I'm doing this because I need to allow the group members to create their own repositories, I've choosen the guest role just because it was the one with less permissions on repositories of others. I'd loved to create a specific role for it but GitLab does not support custom roles :(*

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
