### ISSUE TITLE
Too many deploy keys crashes Firefox

### ISSUE THREAD

**Issue by agjmills** [gitlabhq/gitlabhq#8275]
GitLab 7.3.2 CE makes Firefox 33.0 on Fedora 20 crash when navigating to Settings -> Deploy keys when there are lots fo deploy keys

We have around 300 deploy keys

First you get a javascript message stating "a slow script is running, do you want to stop script or continue" then Firefox says 'Wait' or 'Force Quit'

**Comment by jjanusch** [comment]
A little old, but we are having the same issues. We have roughly 200 deploy keys and navigating to the Deploy Key page takes 10-20s and occasionally doesn't work at all (especially in Firefox, it seems, but it happens in Chrome as well).

There is a feature suggestion for [pagination](http://feedback.gitlab.com/forums/176466-general/suggestions/6606940-paginate-and-search-deploy-keys) that would hopefully help this issue.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
