### ISSUE TITLE
UI for comparing branches and merge request does not have a consistent ordering

### ISSUE THREAD

**Issue by Heliosmaster** [gitlabhq/gitlabhq#8284]
If i create a merge request, the screen which allows me to select branches looks like this:

Source branch -- Target branch

When looking at "Commits" > "Compare" then the views changes to a "from" "to", which actually represent

target branch -- source branch

It is very confusing that stuff is moved around and not consistent.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
