### ISSUE TITLE
Green "Accept merge request" is dangerous

### ISSUE THREAD

**Issue by coder-hugo** [gitlabhq/gitlabhq#8286]
Since a few months we are using GitLab at work to mange our projects. For reviewing the code we use the merge request feature which is very helpful. But it happened more than once that the reviewer hit accidentally the button "Accept merge request" after modifying the assignee or the milestone. This happens because of several UX issues.
1. You won't get notified that your changes regarding the assignee or the milestone have been saved automatically.
2. There is no confirmation dialog before performing the auto-merge.
3. The color of button is green. As the action behind this button usually will modify your master the button should be red or similar to give the user a fair waring that the action of this button is "dangerous".

IMHO the easiest solution for this issues would be the color change of the button. But I think that a confirmation dialog for such an action should be essential.

**Comment by Brunozrk** [comment]
@rumpelsepp +1

A simple confirmation should save much time!

**Comment by randx** [comment]
Coloring button based on CI status makes sense for me

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
