### ISSUE TITLE
Merge requests from forked projects to original project even if in original project merge requests is disabled

### ISSUE THREAD

**Issue by BupycHuk** [gitlabhq/gitlabhq#8287]
In original project merge requests is disabled, but user still can choose original project as target project/branch in merge request creating page.
User can create merge requests from forked projects to parent project. 
After merge request creating user will be redirected to merge request page, but will see 404 error page.

Also user can see created merge request in "Merge requests" page with filter "Created by me".
If user would try to open created merge request he would see 404 error page.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
