### ISSUE TITLE
Explicit Paths in Configuration Files Are Problematic

### ISSUE THREAD

**Issue by u550ccer** [gitlabhq/gitlabhq#8303]
In several of the gitlab configuration files, /home/git is explicitly referenced.  However, for some systems, the users' home directories are not in /home, but mapped elsewhere.  So, every time an upgrade is performed, those config files need to be updated.

The configuration files could instead use the tilde shorthand reference and eliminate this issue.  So, for example in /etc/init.d/gitlab, instead of:
 app_root="/home/$app_user/gitlab"
you could have:
 app_root="~$app_user/gitlab"

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
