### ISSUE TITLE
Issue webhook not triggering when mass updating issues

### ISSUE THREAD

**Issue by pbendersky** [gitlabhq/gitlabhq#8311]
On the issues list, if you tick one or more issues and do any edit, like changing the milestone, webhooks are not called for these issues.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
