### ISSUE TITLE
Issue titles don't escape valid entities: &lt; shows as <

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#8328]
When I write:

    &lt;

On the issue title, I expect it to render as:

    &amp;lt;

but it currently renders:

    &lt;

This only happens for valid entities, e.g. `&asdf;` renders as `&amp;asdf;` as expected: I think the problem is with the `escape_once` at: https://github.com/gitlabhq/gitlabhq/pull/8329. Couldn't we use `html_escape` instead?

The best behaviour in fact would be to have no markdown magic like references nor emoji on titles because it is not possible to escape them like it is on normal markdown.

**Comment by csware** [comment]
Related: issue #7115

**Comment by csware** [comment]
Also related: issue #6549

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
