### ISSUE TITLE
Error pages not following baseurl

### ISSUE THREAD

**Issue by ninja-** [gitlabhq/gitlabhq#8333]
Example error page:
```html
<!DOCTYPE html>
<html>
<head>
  <title>The change you wanted was rejected (422)</title>
  <link href="**BASE URL SHOULD GO HERE**/static.css" media="screen" rel="stylesheet" type="text/css" />
</head>

<body>
  <!-- This file lives in public/422.html -->
  <h1>422</h1>
  <div>
    <h2>The change you wanted was rejected.</h2>
    <p>Maybe you tried to change something you didn't have access to.</p>
  </div>
</body>
</html>
```
Small bug...
/static.css doesn't follow baseurl, causing not found error.

Not sure if baseurl is even supported with pure gitlab?
I am running gitlab via docker and was redirected with this bug to upstream from https://github.com/sameersbn/docker-gitlab/issues/205

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
