### ISSUE TITLE
Issue and MR small screen filter menu overlaps at around 800px [UI]

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#8346]
Issue: overlaps with the button before joining:

![screenshot from 2014-11-18 17 05 34 issue break](https://cloud.githubusercontent.com/assets/1429315/5090897/85a65b42-6f45-11e4-92d8-35365239f304.png)

MR: overlaps with dropdown:

![screenshot from 2014-11-18 17 05 47 mr break](https://cloud.githubusercontent.com/assets/1429315/5090905/934ae088-6f45-11e4-86a2-defb3afb3fa7.png)

MR + top icon small screen menu open:

![screenshot from 2014-11-18 17 10 57 small screen](https://cloud.githubusercontent.com/assets/1429315/5090967/fa073614-6f45-11e4-9258-b6de30e09464.png)

Also why not use the same icon for both?

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
