### ISSUE TITLE
Header icons overlap with project name and show scrollbar on small screen [UI]

### ISSUE THREAD

**Issue by cirosantilli** [gitlabhq/gitlabhq#8347]
Icon half cut:

![screenshot from 2014-11-18 17 15 49 half cut](https://cloud.githubusercontent.com/assets/1429315/5091076/c85c1b42-6f46-11e4-942d-4de9f37f159d.png)

This also implies that the hidden icons and their functionality becomes unreachable.

Scrollbars:

![screenshot from 2014-11-18 17 17 12](https://cloud.githubusercontent.com/assets/1429315/5091088/db2d9408-6f46-11e4-9efb-a830eced7fc2.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
