### ISSUE TITLE
Lines not aligned in side-by-side diff view.

### ISSUE THREAD

**Issue by yuyichao** [gitlabhq/gitlabhq#8358]
When there are more than two continuous lines that are different, the side-by-side diff view always align the first one of those lines on the right to the last one on the left. To the least, the side-by-side view should align the first line changed. (highlighting the different part in the line would also be appreciated but that's a different issue.)

![screenshot](https://cloud.githubusercontent.com/assets/712232/5119501/c824f572-7040-11e4-8651-d3a00d756d3d.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
