### ISSUE TITLE
Links to comments for outdated diffs should show the diff

### ISSUE THREAD

**Issue by jacob-carlborg** [gitlabhq/gitlabhq#8360]
Currently links in email notifications for a comment will go to the correct page and scroll down to the correct comment, using HTML anchors. This doesn't work if the comment is hidden, i.e. attached to an outdated diff. It would be nice, in that case, if the outdated diff could be shown and scroll the page down to the correct comment. I assume this would require some JavaScript.

**Comment by percyhanna** [comment]
:+1: * :100: ^ :100:

**Comment by qwrrty** [comment]
+1 -- I'm surprised there hasn't been more activity on this request. The difficulty in finding outdated diff comments from email notifications is one of my biggest UI complaints with Github.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
