### ISSUE TITLE
[BUG] Can not move project never completes

### ISSUE THREAD

**Issue by danielsokolowski** [gitlabhq/gitlabhq#8371]
Trying to move project from one group to the next on gitlab.com - so feel free to log into my account. I humbly want to point out this is a second basic usability issue (https://github.com/gitlabhq/gitlabhq/issues/8248) that negatively reflects my perception about the readiness of gitlab for prime time.

![image](https://cloud.githubusercontent.com/assets/273413/5148417/ef7d5b80-718c-11e4-8c6f-ef189aa75818.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
