### ISSUE TITLE
Issue links from commit page links to local hostname

### ISSUE THREAD

**Issue by mike-csis** [gitlabhq/gitlabhq#8373]
If I link to an issue in my commit comments, I can write "#5" f.ex. But the resulting link on the Commit view page, links to the servers local hostname f.ex. "scm.local", rather than it's actual url.

My installation is behind a reverse proxy, but all other links work fine. The image below shows the comment in the commit log has a link to "#7". That specific link goes to "scm.local" rather than "scm.mbwarez.dk".

![image](https://cloud.githubusercontent.com/assets/5907292/5155931/abf82c40-72a0-11e4-9f66-ee77043e2cf2.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
