### ISSUE TITLE
Merge request API documentation is incomplete

### ISSUE THREAD

**Issue by dachary** [gitlabhq/gitlabhq#8377]
There are a number of fields that are undocumented in https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/merge_requests.md

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
