### ISSUE TITLE
[BUG] "mentioned in commit" is not added for tags not belonging to branches

### ISSUE THREAD

**Issue by simonzack** [gitlabhq/gitlabhq#8379]
If a commit is created which belongs to a tag but not a branch, then no "mentioned in commit" note will be added to the issue tracker, despite the tag being pushed to the repository.

Tags which don't belong to branches can happen when archiving commits by referencing them with a tag and deleting a branch.

Affects gitlab 7.4.2.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
