### ISSUE TITLE
Starting nginx: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)

### ISSUE THREAD

**Issue by robertd** [gitlabhq/gitlabhq#8386]
I've updated the nginx config and the only thing I changed was ssl certificate location, but i'm getting this error.

I have tried [this solution](https://rtcamp.com/tutorials/nginx/troubleshooting/emerg-bind-failed-98-address-already-in-use/) but no luck.

```
robertd@gitlab:/etc/nginx/sites-available$ sudo service nginx stop
Stopping nginx: nginx.
robertd@gitlab:/etc/nginx/sites-available$ sudo service nginx start
Starting nginx: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)
nginx: [emerg] still could not bind()
nginx.

```

I had to revert gitlab-ssl config to 25ee53c3aea763f commit (7.3-stable) and everything started working again.

Any ideas?

**Comment by robertd** [comment]
@oschwede Worked like a charm. PR #8395 looks good.

**Comment by topdown** [comment]
This issue was back following the upgrade instructions here
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/6.x-or-7.x-to-7.10.md
Where it says the 
```/etc/nginx/sites-available/gitlab```
Needs to look like https://gitlab.com/gitlab-org/gitlab-ce/blob/7-10-stable/lib/support/nginx/gitlab
So it seems this line is wrong yet https://gitlab.com/gitlab-org/gitlab-ce/blob/7-10-stable/lib/support/nginx/gitlab#L38

Added the fix
```listen [::]:80 ipv6only=on default_server;```
And all was good.
