### ISSUE TITLE
Dashboard comments trimmed

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#8390]
**Information:**
whenever a comment such as "LOL.. that's funny" when viewed on dashboard the message get's trimmed..

**Screenshot:**

**IssuePage**
![image](https://cloud.githubusercontent.com/assets/4362134/5185319/7f28a36a-74f9-11e4-980b-b60fabc0331c.png)

**Dashboard**
![image](https://cloud.githubusercontent.com/assets/4362134/5185359/d057ecaa-74f9-11e4-839b-541580811542.png)

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
