### ISSUE TITLE
<br/> doesn't work in wiki?

### ISSUE THREAD

**Issue by alexeyr** [gitlabhq/gitlabhq#8399]
Documentation says

> You can also use raw HTML in your Markdown, and it'll mostly work pretty well.

However, using `<br>` or `<br/>` doesn't seem to work; "View source" shows they aren't rendered.

**Comment by mani95lisa** [comment]
+1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
