### ISSUE TITLE
Broadcast Message

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#8409]
Is it me or it's useless to have multiple `broadcast_messages`?
cause I tried on creating 2.
The first one showed up.
after creating the second one.
the first one was gone already..
even after refreshing multiple times, it doesn't show the first message i just created.

**Suggestion:**
make broadcast_message rotating broadcast_message. Like whenever i refresh it.. it changes the broadcast_message when you have multiple one.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by dallinwilcox** [comment]
See https://gitlab.com/gitlab-org/gitlab-ce/issues/13336# for GitLab issue tracking this.
