### ISSUE TITLE
git clone problem

### ISSUE THREAD

**Issue by tianzhiqing** [gitlabhq/gitlabhq#8412]
According to the document are no problem, but the 'git clone git@gitlab.modhb.com:modhb/phpcode.git' encountered two problems
1, to enter the password,
2, when the input password, must in the 'modhb' before 'repositories' to clone local
This method is solved?

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
