### ISSUE TITLE
Deploy Keys ' Fingerprint or Key' | 'already taken' 

### ISSUE THREAD

**Issue by offlinehoster** [gitlabhq/gitlabhq#8413]
Hi Guys,

i just tried to add a new deploykey for a project, but after insert the key and setting the name, i only see

```
Key has already been taken
Fingerprint has already been taken
```

But this key is not in use at this time, because it's a new one.

How can i find out where this fingerprint is already used?

Any ideas?

Cheers
Christian

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by chengweiv5** [comment]
+1 for this though it was closed.

Seems there isn't anyway to finger out where the deadly key been added.
