### ISSUE TITLE
gitlab freezes firefox whenever I try to open a new MR

### ISSUE THREAD

**Issue by Lacrymology** [gitlabhq/gitlabhq#8418]
It takes the whole browser out, sometimes for minutes at a time. I'm running under firefox 30

**Comment by thomaslevesque** [comment]
For me it happens not only on a merge request; any time I open the homepage of a project, Firefox 35 freezes for several seconds. It seems to happen only when Firefox has been running for a while; if I restart it, Gitlab works normally again, but not for long.

**Comment by vamega** [comment]
This continues to be an issue for me and the company I work for.
(Gitlab Community Edition 7.12)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
