### ISSUE TITLE
Gitlab relative URL under apache proxy pass

### ISSUE THREAD

**Issue by sandipsahani** [gitlabhq/gitlabhq#8421]
I am running gitlab inside a docker which is mapped to post 8880 on my localhost. So I can access it using the URL
http://localhost:8880/

But I have used apache proxy pass to create following mapping
http://localhost:8880/ ------> http://localhost/gitlab

So that my users can access gitlab through http://localhost/gitlab.
Everything seems to be working fine but the problem arises when the page is rendered. All the link in the page generated by Gitlab uses relative url like

/assets/favicon-baaa14bade1248aa6165e9d34e7d83c0.ico
/assets/application-296ff8a0c87574e522a2911224b5350b.css
/assets/print-1df3ea9b8ff148a6745321899e0cb213.css

This causes apache to redirect them to http://localhost/assets/.... which results in 404 Error which is obvious. The link should have generated as /gitlab/assets/.... so that apache can map them correctly
to http://localhost/gitlab/assets....

I have tried using the Apache rewrite module, Nginx rewrite module but none of them worked. Is there anyway I can change the relative URL generated by gitlab?

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
