### ISSUE TITLE
Namespace ID ambiguous as it isn't clear if is a user ID or a group ID

### ISSUE THREAD

**Issue by CCTJNII** [gitlabhq/gitlabhq#8443]
I'm attempting to categorize projects via the API and I cannot seem to determine a clear way to tell if a project is in a user namespace or a group namespace.  Looking at the example given on https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/projects.md:

```json
   "namespace": {
      "created_at": "2013-09-30T13: 46: 02Z",
      "description": "",
      "id": 3,
      "name": "Diaspora",
      "owner_id": 1,
      "path": "diaspora",
      "updated_at": "2013-09-30T13: 46: 02Z"
    },
```

An id is given for the namespace, but it isn't clear if that namespace belongs to a user or a group.  Via trial and error against our gitlab it appears the IDs are not unique between users and groups, so a simple lookup doesn't suffice.  I have been unable to determine any user/group signatures for namespace that appear reliable.

For resolution I believe we should add a field that shows what kind of id 'id' is, or clarify the namespace documentation so unseasoned users don't chase their tails on this.  Thanks.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
