### ISSUE TITLE
When 'Create new label' for an issue is chosen, issue title and description are lost

### ISSUE THREAD

**Issue by alexandreleroux** [gitlabhq/gitlabhq#8454]
When creating a new issue, if we chose 'Create new label', then we can't go back to the issue, the title and description are lost and we have to start a new issue.

Expected behavior: being able to go back to the previous state of the issue after creating a new label.

**Comment by alexandreleroux** [comment]
Thanks dblessing for the followup. I confirm that in GitLab 7.5.2 57d0209 , the link to create a new label does not open in a new window or tab. Furthermore, as you pointed out, such as new label must be made available to the current issue being written without losing its content. Thanks

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
