### ISSUE TITLE
Checking Sidekiq failed but Sidekiq is running

### ISSUE THREAD

**Issue by e11it** [gitlabhq/gitlabhq#8456]
OS: FreeBSD. Ruby 2.1 Gitlab 7.5.3

```sh
Checking Sidekiq ...
Running? ... no
```
but
```sh
root@gitlab:/home/git/gitlab # sudo -u git -H ps ux | grep -i sidekiq 
git  44052  0.0 17.9 443920 183008  -  SsJ  12:16AM 0:07.18 ruby21: sidekiq 2.17.0 gitlab [0 of 25 busy] (ruby21)
```

File: gitlab/lib/tasks/gitlab/check.rake(line 650)
Value of `ps_ux`( `ps_ux, _ = Gitlab::Popen.popen(%W(ps ux))`) is:
```
USER   PID %CPU %MEM    VSZ    RSS TT  STAT STARTED    TIME COMMAND
git  44419 89.0 16.6 354028 169600  1  S+J  12:34AM 0:05.72 ruby21 /usr/home/gi
git  43801  0.0 10.1 372284 103844  -  IJ   12:06AM 0:06.36 ruby21: unicorn_rai
git  43805  0.0  9.8 390808 100220  -  IJ   12:06AM 0:00.86 ruby21: unicorn_rai
git  43806  0.0 12.0 378540 122468  -  IJ   12:06AM 0:00.39 ruby21: unicorn_rai
git  44052  0.0 17.9 443920 182900  -  SsJ  12:16AM 0:06.74 ruby21: sidekiq 2.1
```
So line is stripped. As a result pattern not match( `/sidekiq \d+\.\d+\.\d+/`)

Changing ps_ux to get output from cmd `ps ax`(lines length are shorter) fix this issue.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
