### ISSUE TITLE
Limit for projects

### ISSUE THREAD

**Issue by waghanza** [gitlabhq/gitlabhq#8471]
Hi,

I'm a gitlab user :
* `v7.4.3`
* debian `7.6`
* mariadb `10.1.2`

While I try to create a user, I meet a 500 error page.

I have the following error
`Mysql2::Error: Out of range value for column 'projects_limit'`

This error is because project limit number is too high, but is there a way to define non-creators users (only for project in theire namespaces) ?

Regards,

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
