### ISSUE TITLE
Can't push : 401 Unauthorized

### ISSUE THREAD

**Issue by rigober44** [gitlabhq/gitlabhq#8476]
Hi,

I followed this tutorial to install and configure gitlab on redhat 6.4 (https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md). 
I use mysql, thin server and nginx as reverse proxy. I don't why but it doesn't work with unicorn (it doesn't matter we already use thin for an other application). I can connect to gitlab, create projects and users.  
I start the application with these commands :
-> bundle exec sidekiq -q post_receive -q mailer -q system_hook -q project_web_hook -q gitlab_shell -q common -q default -e production -P tmp/pids/sidekiq.pid &

-> bundle exec thin start -C /etc/thin/gitlab.yml

Now, I try to push some content in a project but i can't. If i try from the server i get this error  : 
git push -u origine master
error: The requested URL returned error: 401 Unauthorized while accessing http://localhost/gitlab/root/git-example.git/info/refs

and from a git client in windows 
/usr/local/lib/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout 

Do i forget to parameter something ?

Any help would be welcome.

Thanks in advance.

**Comment by donnykurnia** [comment]
Same issue even in the gitlab 7.7. I had to restart the gitlab service to make things works well again. So anoyying...

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
