### ISSUE TITLE
init script - stop() function conflict

### ISSUE THREAD

**Issue by krzaczek** [gitlabhq/gitlabhq#8480]
On SunOS gitlab 5.11 joyent_20130814T090215Z i86pc i386 i86pc Solaris

Init scripts ./bin/web and ./bin/background_jobs fail to stop services on smartOS with error

Usage: kill [-l] [-n signum] [-s signame] job ...
Or: kill [ options ] -l [arg ...]

This is because stop function name. Changing it to something else eg. stop_web fixes the problem.

see https://github.com/gitlabhq/gitlabhq/pull/5879

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
