### ISSUE TITLE
Gitlab Omnibus for Ubuntu 14.04 doesn't work

### ISSUE THREAD

**Issue by alexbagirov** [gitlabhq/gitlabhq#8493]
Hello!

I've tried to install GitLab with Omnibus package. Currently I have Ubuntu 14.04. I get an error that my system is i386. What can I do?

**Comment by sivatumma** [comment]
I am currently facing this issue. a ```uname -m``` says ```i686```, though

**Comment by alexbagirov** [comment]
@sivatumma, I don't actually remember what have I done, but maybe I just deleted all bad packages and all other trash and reinstalled it. What error do you receive durng the installation?

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
