### ISSUE TITLE
Mentioning users at the end of a sentence fails

### ISSUE THREAD

**Issue by disenchant** [gitlabhq/gitlabhq#8507]
When mentioning a user in an issue (e.g. ``@disenchant``) this works perfectly but when using it at the end of a sentence, it won't be recognized (and therefor won't be converted into a link) by GitLab because of the period. See the following example:

Works in GitLab:
@disenchant can provide more information on this issue.

Doesn't work in GitLab:
The one who can provide more information on this issue is @disenchant.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
