### ISSUE TITLE
Unassign issue through API won't work

### ISSUE THREAD

**Issue by marcovanest** [gitlabhq/gitlabhq#8529]
It seems that the functionality to unassigne a issue through the API is broken. The assignee property has the value null after 

    PUT /projects/:id/issues/:issue_id 

with in the body the property assignee_id : null
But the issue UI shows something different in the assignee dropdown:
![schermafbeelding 2015-01-02 om 16 15 58](https://cloud.githubusercontent.com/assets/2694109/5596975/acc6473c-929a-11e4-9a1d-e62dea4c24b5.png)

It should look like this:
![schermafbeelding 2015-01-02 om 16 15 49](https://cloud.githubusercontent.com/assets/2694109/5596976/ace753e6-929a-11e4-937a-20152348ae08.png)

The issue stays open and assigned because of this

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
