### ISSUE TITLE
Avatar not showing in network graph for commits with non-primary email address

### ISSUE THREAD

**Issue by EmteZogaf** [gitlabhq/gitlabhq#8541]
I changed my primary email address and added the old one as secondary email address.
![gitlab_change_primary_to_secondary_email](https://cloud.githubusercontent.com/assets/1272656/5627341/202e5ae4-9597-11e4-87a5-66abcf9366ee.png)

Now my uploaded avatar is not displayed in the network graph anymore. It's replaced by a standard avatar image. For these commits i used the secondary email address.
![gitlab_no_avatar_in_network_gaph](https://cloud.githubusercontent.com/assets/1272656/5627348/29cfe608-9597-11e4-8da8-ab3fc20d9966.png)

Anywhere else my avatar is shown for these commits.

Gitlab version: 7.6.2 (Community Edition)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
