### ISSUE TITLE
Delete and create project with same name via API does not remove files 

### ISSUE THREAD

**Issue by jpiulac** [gitlabhq/gitlabhq#8549]
Using API v3 via curl to:
 
1) delete existing project 
2) create project (using the same name) 

Fails to create a new empty project and instead creates a project containing the files from previously deleted project. 

I was doing this under a group/namespace and have not tested using default (user) namespace.

steps to reproduce: 
curl -X DELETE http://gitlabserver.com/api/v3/projects/:id?private_token=:token
curl -H "Content-Type:application/json" http://gitlabserver.com/api/v3/projects?private_token=:token -d "{ \"name\": \"$1\", \"namespace_id\": \"$2\" }"

**Comment by nils-werner** [comment]
I have noticed something similar when trying to use Drone.io with GitLab: It appears that calls to the API (adding deploy keys and webhooks) always returns a 404 when:

 - the repository has existed before
 - was deleted
 - has been created using the exact same name

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
