### ISSUE TITLE
Can't delete merge request after removing the associated branch

### ISSUE THREAD

**Issue by jonathonross** [gitlabhq/gitlabhq#8566]
I accidentally deleted the branch I was attempting to merge with gitlab, and now the merge request is stuck there and I can't access it to delete it. Whenever I click on the merge request, I get a 500 error:

![screen shot 2015-01-12 at 4 22 25 pm 2](https://cloud.githubusercontent.com/assets/9285487/5713994/8de611be-9a77-11e4-848a-87dd4090fab2.png)
![screen shot 2015-01-12 at 4 22 38 pm 2](https://cloud.githubusercontent.com/assets/9285487/5713995/8de61b78-9a77-11e4-9202-15df152694bc.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
