### ISSUE TITLE
Could not read from remote repository.

### ISSUE THREAD

**Issue by offlinehoster** [gitlabhq/gitlabhq#8578]
Hi,

every few days we have this  "Could not read from remote repository." issue after create a new repo and try to clone/push this repo.

1.) User is creating a new private project called "example" with access for group "Employees"
2.) User is trying to clone this repo
3.) Error "Could not read from remote repository." appears on the user shell
4.) deleting project "example" by gitlab webinterface
5.) re-creating the project "example"
6.) User is trying to clone this repo again
7.) Error "Could not read from remote repository." appears on the user shell
8.) the admin, me, is deleting the repo "example" by gitlab webinterface
9.) the admin, me, is deleting the remaining files for this repo "example" on the filesystem by shell
10.) the admin, me, is doing "gitlab-rake gitlab:shell:setup" and "gitlab-ctl restart"
11.) the user can now create the repo "example" again and have access to this repo and can clone/push everything to this repo.

We're running the following version:
* GitLab 7.5.1
* GitLab Shell 2.2.0
* GitLab API v3
* Ruby 2.1.4p265
* Rails 4.1.1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
