### ISSUE TITLE
Gitlab 5.4.0 ssh key error

### ISSUE THREAD

**Issue by kgoedert** [gitlabhq/gitlabhq#8595]
I am using gitlab 5.4.0 on a ubuntu server and when I try to add an ssh key to a user I get a 500 error.

In the production log this appears:

Parameters: {"utf8"=>"✓", "authenticity_token"=>"D4nNa6W9W7qNxD2k48EoJ1jv7NqqtILgnESei2OmU84=", "key"=>{"title"=>"vm249", "key"=>"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4XByjO42Ygr2FKKd3NTnqUkH0ft4C2ayT/7UTsaGdOrS+tzvj7NeKYtxGqInXpII9jz92zc2tWobyg+vVz0GNhOvQerLlb+BDO4fjxbxE25OkkB+FVTS8X1q1zN2o6I3vE+....}}
Completed 500 Internal Server Error in 6ms

TypeError (no implicit conversion of Symbol into Integer):
  app/models/key.rb:37:in `new'
  app/models/key.rb:37:in `fingerprintable_key'
  app/controllers/keys_controller.rb:21:in `create'

Can anyone help?

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
