### ISSUE TITLE
Lots of 500 due to Google Bot

### ISSUE THREAD

**Issue by Phyks** [gitlabhq/gitlabhq#8612]
Hi,

I have lots of 500 errors due to Google bot crawling my gitlab instance.

```
IP - - [19/Jan/2015:07:01:32 +0100] "GET /user/repo/commit/3c7b4f496d6679373c9e4a6dbf2214e2f4333bba.diff HTTP/1.1" 500 349 "-" "Mozilla/5.0 (compatible;
Googlebot/2.1; +http://www.google.com/bot.html)"
```

How can I fix this? Running Omnibus up-to-date.

Thanks

EDIT: This is actually due to the "Download as" option in the dropdown menu, in the detailed view of a commit , which fails with a 500.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
