### ISSUE TITLE
Parts of a code block mistakenly treated as issue mentions

### ISSUE THREAD

**Issue by bchretien** [gitlabhq/gitlabhq#8613]
I noticed that after copying a `gdb` backtrace inside a code block to a comment as follows:

```sh
Program received signal SIGFPE, Arithmetic exception.
0x00007ffff6109895 in ?? () from /usr/lib/libcuda.so
(cuda-gdb) bt
#0 0x00007ffff6109895 in ?? () from /usr/lib/libcuda.so
#1 0x00007ffff610b309 in ?? () from /usr/lib/libcuda.so
#2 0x00007ffff610c832 in ?? () from /usr/lib/libcuda.so
#3 0x00007ffff60a958c in ?? () from /usr/lib/libcuda.so
#4 0x00007ffff609fb8e in ?? () from /usr/lib/libcuda.so
#5 0x00007ffff5f4364f in ?? () from /usr/lib/libcuda.so
#6 0x00007ffff5ff8829 in ?? () from /usr/lib/libcuda.so
#7 0x00007ffff7b97976 in ?? () from /opt/cuda/lib64/libcudart.so.5.0
#8 0x00007ffff7b9cbe0 in ?? () from /opt/cuda/lib64/libcudart.so.5.0
#9 0x00007ffff7b9545b in ?? () from /opt/cuda/lib64/libcudart.so.5.0
#10 0x00007ffff7b9e4ac in ?? () from /opt/cuda/lib64/libcudart.so.5.0
#11 0x00007ffff7ba1ffa in ?? () from /opt/cuda/lib64/libcudart.so.5.0
#12 0x00007ffff7b9b323 in ?? () from /opt/cuda/lib64/libcudart.so.5.0
#13 0x00007ffff7b8b759 in ?? () from /opt/cuda/lib64/libcudart.so.5.0
#14 0x00007ffff7bb0f2a in cudaMalloc () from /opt/cuda/lib64/libcudart.so.5.0
#15 0x000000000040093f in main () at texture.cu:14
```
The issue where this comment was made is now referenced in issues 1 to 15 (`mentioned in issue #...`). I guess that code blocks should be ignored when checking for such references.

This was observed with `GitLab 7.4.2 (477743a)`, so it may have been fixed since then, but I haven't been able to find any mentions on this bug in the issue tracker (looking up "issue", "mention", "reference" and so on makes it hard to find relevant issues).

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
