### ISSUE TITLE
(GitLab API) Response for commits request doesn`t contain pagination header

### ISSUE THREAD

**Issue by anshakov** [gitlabhq/gitlabhq#8631]
When I request this path:

/api/v3/projects/57/repository/commits?page=1&per_page=5

I expect to recieve pagination header like this:

<pre>Link: &lt;https://somehost/api/v3/projects/57/repository/commits?page=2&per_page=5&gt;; rel="next", &lt;https://somehost/api/v3/projects/57/repository/commits?page=1&per_page=5&gt; rel="first", &lt;https://somehost/api/v3/projects/57/repository/commits?page=11&per_page=5&gt;; rel="last"</pre>

though I see no pagination header in response.

I use GitLab 7.5.3

**Comment by EvAlex** [comment]
:+1: Same issue

**Comment by beniwtv** [comment]
Same problem here, 7.10.4

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
