### ISSUE TITLE
Documentation out of date for Projects API Calls: GET /projects/:id

### ISSUE THREAD

**Issue by StephenOTT** [gitlabhq/gitlabhq#8653]
The "Get Single Project" section is out of date:
http://doc.gitlab.com/ce/api/projects.html

The Single Project section still references that you can use Namespace/project_name is still accepted.  But this should be removed.  only :id is currently accepted.

**Comment by rhymoid** [comment]
Is this related to [https://github.com/gitlabhq/gitlabhq/issues/8290#issuecomment-88355554 the issue where Apache's default settings break the GitLab API]?

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
