### ISSUE TITLE
GitHub import does not work as expected

### ISSUE THREAD

**Issue by patschi** [gitlabhq/gitlabhq#8664]
Hello.

When I'm try to import a project from GitHub I just get redirected to the main page with exactly this URL: 
<pre>https:/git.domain.tld/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch</pre>

Yes, the same error is twice in the URL. How I could get this fixed? The import doesn't even work at all. But I guess, that is just a strange error/fault of my side.

Thanks for any help!

**Comment by Razer6** [comment]
@vsizov Can you take a look?

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
