### ISSUE TITLE
Push webhook - wrong rev-list count?

### ISSUE THREAD

**Issue by gaui** [gitlabhq/gitlabhq#8665]
I would like to get someones opinion on this. We have a push webhook that posts messages to Slack. Everytime we were pushing new feature-branches, we would always get a sky-high commit count. Like we were pushing 420 commits, but it was a brand new branch.

I think the push webhook property `total_commits_count` is getting a wrong count, because of a wrong `rev-list` logic.

Let's say there are 420 commits between `master` and `dev`, so when I branch off of `dev` and push that branch, the `total_commits_count` is `420` but it really should be `0` - right?

I think the webhook is always checking diff count from `master` branch (judging frome screenshot below), when it should be checking diff count from **parent** branch.

![Wrong vs. right](http://i.imgur.com/9Ka57Gd.png)

	$ git rev-list master...feature/SWSA-567 --count
	420

	$ git rev-list dev...feature/SWSA-567 --count
	0

**Comment by Hrafnkellos** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
