### ISSUE TITLE
check_init_script_exists in lib/tasks/gitlab/check.rake assumes /etc/init.d exists.

### ISSUE THREAD

**Issue by crocket** [gitlabhq/gitlabhq#8668]
Ubuntu has /etc/init.d, but other linux distributions don't have it.

On archlinux, gitlab is an AUR package. https://aur.archlinux.org/packages/gitlab
The AUR package install init scripts in `/usr/lib/systemd/system`.

I think check_init_script_exists should expand its assumptions.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
