### ISSUE TITLE
Project fork to my workspace

### ISSUE THREAD

**Issue by letiagoalves** [gitlabhq/gitlabhq#8674]
If I don't have already created one project in my workspace, **I can't automatically fork** using the project GitLab page.

**The error is the following:**
*You tried to fork group / some-project but it failed for the following reason:
– Fork transaction failed.*

However **after I create an empty project in my workspace** I was able then to fork any project.

GitLab version: 7.1.1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
