### ISSUE TITLE
Expanding diff of added file duplicates the first line

### ISSUE THREAD

**Issue by mishak87** [gitlabhq/gitlabhq#8679]
**Reproduce:**

* commit new text file
* view commit in detail (in GitLab)
* click on top `... | ...` in diff to expand further

**Expected:** no other lines are shown
**Given:** ![image](https://cloud.githubusercontent.com/assets/276500/5956888/cca530d6-a7b2-11e4-94b2-3e8c8b2493f9.png)

Also would be nice to not display expansion dots for diffs that are fully shown.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
