### ISSUE TITLE
LDAP login is not clear, provide info text and allow domain prefix login.

### ISSUE THREAD

**Issue by ssbarnea** [gitlabhq/gitlabhq#8691]
You may be surprised about the number of people that are trying to login using the `DOMAIN\username` approach instead of just `username`.

Please allow us to add some custom informational text on the LDAP login page and eventually allowing to strip the domain name from the username,  otherwise we do encounter many users that are not able to login, just because they do not know how to write their credentials.

An extra feature would be to allow them to login with their email, even on LDAP mode. But this would require the server to recognize that it is an email, and to translate it to an username before doing the authentication.

**Comment by sanju1010** [comment]
I am not able to log in to https://gitlab.citrite.net using my citrite credentials.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
