### ISSUE TITLE
In milestone view for a project group, would it be possible to list the due date? (screenshot included)

### ISSUE THREAD

**Issue by exabrial** [gitlabhq/gitlabhq#8695]
Summary: If you navigate to, http://gitlab_server_name/your_group_name/milestones you can see an incredibly useful overview of all the milestones currently open for a project group. It would be nice if the due date for each milestone were listed in this view:

Example:

![image](https://cloud.githubusercontent.com/assets/1392297/5980928/fcc5c604-a87a-11e4-9358-047df442da1c.png)

**Comment by exabrial** [comment]
If anyone could point me to where possibly I could make this change myself, that would also be greatly appreciated!

**Comment by exabrial** [comment]
Can anyone help me figure out why the build is failing? :(

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
