### ISSUE TITLE
Large snippet leads to high cpu load and ultimately timeout

### ISSUE THREAD

**Issue by fenrasa** [gitlabhq/gitlabhq#8699]
Hello,

I saved a 1.7 MB assembler file as a public snippet. Now whenever someone opens the snippet's URL the server hogs the CPU until gilt shows error 502.
I cannot delete the large snippet anymore. Is there a way to manually delete it?

Cheers

GitLab 7.7.0
GitLab Shell 2.4.1
GitLab API v3
Ruby 2.1.4p265
Rails 4.1.1

==> /var/log/gitlab/unicorn/unicorn_stderr.log <==
E, [2015-01-30T23:18:29.635465 #12011] ERROR -- : worker=1 PID:12333 timeout (61s > 60s), killing
E, [2015-01-30T23:18:29.657546 #12011] ERROR -- : reaped #<Process::Status: pid 12333 SIGKILL (signal 9)> worker=1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
