### ISSUE TITLE
Reasoning for Project Search not supporting "namespace/project name"???

### ISSUE THREAD

**Issue by StephenOTT** [gitlabhq/gitlabhq#8704]
According to the docs: http://doc.gitlab.com/ce/api/projects.html#search-for-projects-by-name

You cannot search for Projects by "Namespace/project Name".  You have to search by project name, and then filter by namespace from the returned results.

What is the reasoning for this?  It seems to go against the standard user expectation for the ability to search for a project by namespace and project name as there are many cases of duplicate project names.

At a API level this becomes even more complicated for the integration because it is an extra level of detail API calls required to get the project ID number.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
