### ISSUE TITLE
Blob VS Raw View

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#8708]
**Information:**
I just noticed that the blob view and raw view are different. The blob view shows the file content with wrong formatting on it while raw view shows the correct format.

**Screenshots:**

**Blob View:**
![Raw](http://cdn.img42.com/316cc36c02eb974a14251d6e50730b8e.jpeg)
**Raw View:**
![Blob](http://cdn.img42.com/038d5c0115cda19d4aab6a7efbe2350e.jpeg)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
