### ISSUE TITLE
Admin can't create projects on groups he's not a member of

### ISSUE THREAD

**Issue by dserodio** [gitlabhq/gitlabhq#8713]
According to the [documentation](http://doc.gitlab.com/ce/permissions/permissions.html):
> If a user is a GitLab administrator they receive all permissions.

I'm an admin of my GitLab install, but I can only create new project in groups I'm a member.
My knowledge of Rails is very limited, but it seems the problem is in [NamespacesHelper.namespaces_options](https://github.com/gitlabhq/gitlabhq/blob/master/app/helpers/namespaces_helper.rb#L2), which doesn't consider whether the user is an admin.

I'm using GitLab 7.7.0

**Comment by dosire** [comment]
Also reported in https://groups.google.com/forum/#!msg/gitlabhq/OIDER6wjpGo/ZINvXYIQ6fsJ

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
