### ISSUE TITLE
Exception when non-logged in users view merge request

### ISSUE THREAD

**Issue by jasonblanchard** [gitlabhq/gitlabhq#8714]
Steps to reproduce:
1. Sign in and create a merge request
2. Visit the `Projects::MergeRequestsController#show` page for the merge request as a non-logged in user.

Looks like the `Gitlab::GitAccess.can_push_to_branch?` is not guarding against a nil user:

![screen shot 2015-02-02 at 6 11 29 pm](https://cloud.githubusercontent.com/assets/1238532/6011208/4606dbda-ab07-11e4-92f0-de6ea24dbca0.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
