### ISSUE TITLE
LDAP User Not Found

### ISSUE THREAD

**Issue by timothynode** [gitlabhq/gitlabhq#8716]
Gitlab used ldap path to find user, which could be a problem, if user's ou had been changed.
Please change to ObjectID or sAMAccountName....

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
