### ISSUE TITLE
Integrate pdf viewer for files view.

### ISSUE THREAD

**Issue by helgrind** [gitlabhq/gitlabhq#8724]
I have added pdf.js functionality into the files viewer to render pdfs. This is really helpful if using gitlab for collaborating on publications. However, I am moving the code from an old abandoned gem into the main code base as it's very slim. Couple of qs:

* What is the gitlab way to convert the css.erb sheet into scss? It uses background-images and the asset path currently. Would I need to convert to defining all the images in the view?
* I'm going to add a view for it - should it be in blob or shared as it is reuseable?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
