### ISSUE TITLE
Slack links miss the server port

### ISSUE THREAD

**Issue by crazyjul** [gitlabhq/gitlabhq#8725]
All the links in the snippet posted to Slack does not include the port of the server.

This shows up in version 7.7.1

**Comment by crazyjul** [comment]
My bad, 

While trying to fix the issue, I discover my gitlab.yml was not properly configured.

Is there a way to test the port specified there is the right one in one of the rake test task?

Thanks, and sorry for the noise

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
