### ISSUE TITLE
500 error when displaying milestones under group (not under project)

### ISSUE THREAD

**Issue by gzpbx** [gitlabhq/gitlabhq#8731]
Gitlab 7.6.2

I see there are "Checking Environment " logs in other issues, I don't know how to get the logs ... 

==========================================
Started GET "/groups/mygroupname/milestones" for 127.0.0.1 at 2015-02-04 12:09:54 +0800
Processing by Groups::MilestonesController#index as HTML
  Parameters: {"group_id"=>"mygroupname"}
Completed 500 Internal Server Error in 191ms

ActionView::Template::Error (No route matches {:action=>"show", :controller=>"groups/milestones", :format=>nil, :group_id=>#<Group id: 3, name: "mygroupname"
, path: "mygroupname", owner_id: nil, created_at: "2015-01-21 17:06:49", updated_at: "2015-01-21 17:07:00", type: "Group", description: "<E6><B0>my group descp", avatar: "WOT_logo_84x84.png">, :id=>"", :milestone=>{:state_event=>:close}, :title=>"<E8>
<A7><A3><E8>my group title"} missing required keys: [:id]):
    28:                   - if milestone.closed?
    29:                     = link_to 'Reopen Milestone', group_milestone_path(@group, milestone.safe_title, title: milestone.title, milestone: {state_event: 
:activate }), method: :put, class: "btn btn-small btn-grouped btn-reopen"
    30:                   - else
    31:                     = link_to 'Close Milestone', group_milestone_path(@group, milestone.safe_title, title: milestone.title, milestone: {state_event: :
close }), method: :put, class: "btn btn-small btn-close"
    32:               %h4
    33:                 = link_to_gfm truncate(milestone.title, length: 100), group_milestone_path(@group, milestone.safe_title, title: milestone.title)
    34:               %div
  app/views/groups/milestones/index.html.haml:31:in `block in _app_views_groups_milestones_index_html_haml__4310615663744662143_41675940'
  app/views/groups/milestones/index.html.haml:24:in `each'
  app/views/groups/milestones/index.html.haml:24:in `_app_views_groups_milestones_index_html_haml__4310615663744662143_41675940'

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
