### ISSUE TITLE
Indefinite loading of commit data in .dot directories

### ISSUE THREAD

**Issue by jbbr** [gitlabhq/gitlabhq#8763]
Gitlab does not show commit information (last updated / last commit) for directories whose name begins with "."
Instead the loading indicator (Loading commit data...) is visible indefinitely.

The ajax request for the commit data fails with an error 404. The requested url is something like https://gitlab.com/user/project/refs/master/logs_tree/.idea?_=1423501669010

The problem occurs in the latest Gitlab 7.7.2. Also with the official gitlab instance on https://gitlab.com

Steps to reproduce:
- Add and push directory ".anything" with some files in it to a gitlab repository
- List directory ".anything" in the web interface

![gitlab_loading](https://cloud.githubusercontent.com/assets/682607/6111249/be7923cc-b087-11e4-9184-768a2967209a.png)

**Comment by jbbr** [comment]
The problem still exists with Gitlab 8.0.4 - Also on gitlab.com.

It's not a blocker but definitively irritating. Is there anything I can do to help fixing it?

**Comment by stanhu** [comment]
It looks like the Ajax call for the commit data is returning a 404. The issue is that `logs_tree` in  `RefsController` is never being called due to some issue with the regex matching in `db/routes.rb`:

```ruby
          member do
            # tree viewer logs
            get 'logs_tree', constraints: { id: Gitlab::Regex.git_reference_regex }
            get 'logs_tree/*path' => 'refs#logs_tree', as: :logs_file, constraints: {
              id: Gitlab::Regex.git_reference_regex,
              path: /.*/
            }
          end
```

It looks like if you remove the line `id: Gitlab::Regex.git_reference_regex`, everything works as it should. The regular expression is derived [from this page](https://www.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html).

My guess is that the regular expression for `id` is somehow matching `master/logs_tree/.idea` and thus rejecting it as an invalid ref name.

**Comment by stanhu** [comment]
Fix here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1574

**Comment by jbbr** [comment]
Thanks, that was fast :)
