### ISSUE TITLE
urlencode files containing a percent sign

### ISSUE THREAD

**Issue by toaomatis** [gitlabhq/gitlabhq#8766]
Some of the files on our gitlab server contain a percent sign in the file name. When trying to view the files through the web interface of gitlab, *nginx* gives me a **400 Bad Request**. This is the result of the following URI:

http://example.com/mirrors/poky/blob/daisy/meta-yocto/recipes-core/busybox/busybox_%.bbappend

When I manually adapt the URI to the following:

http://example.com/mirrors/poky/blob/daisy/meta-yocto/recipes-core/busybox/busybox_%25.bbappend

The file is shown in the web interface like it should.

Components:
* GitLab 7.6.2
* GitLab Shell 2.4.0
* GitLab API v3
* Ruby 2.1.4p265
* Rails 4.1.1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
