### ISSUE TITLE
wiki pages output consistency with Gollum

### ISSUE THREAD

**Issue by fcelda** [gitlabhq/gitlabhq#8771]
The wiki pages generated by GitLab ofen differ from the pages generated by standalone Gollum (described in the instructions on *Git Access* tab in a project wiki). We are using GitLab 7.7.

For example, using a code blocks within ordered list doesn't work in GitLab. I.e., when the code blocks are indented by a few spaces under the list item, Gollum puts the code block inside the `<li>` tag. However GitLab terminates the list, puts the code block at the root level, and starts a new list.

Input:

<pre>
1. step one

   ```
   code block
   ```

2. step two
</pre>

Gollum output:

<pre>
1. step one

   code block

2. step two
</pre>

GitLab output:

<pre>
1. step one

code block

1. step two
</pre>

This is probably not the only one problem with wiki rendering. I remember encountering some invalid new line wrapping in GitLab output, but that might been have already fixed.

I have no idea, where the cause is. If someone can point me to the right direction, I can try to resolve the rendering issues by myself and send a PR.

**Comment by axilleas** [comment]
I believe wikis are rendered using GitLab's markdown which differentiates in some places from standard wiki markup.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
