### ISSUE TITLE
Git Zombies

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#8773]
I often see git zombies in htop. What can I do to provide more information on this?
![screenshot from 2015-02-10 21 16 54](https://cloud.githubusercontent.com/assets/1961699/6135588/41051822-b16a-11e4-8c6b-7810116c348e.png)

**Comment by Wachiwi** [comment]
:+1:

**Comment by apazdnikov** [comment]
+1

**Comment by offlinehoster** [comment]
Hi Guys,

same issue here since 2-3 Weeks.

Today an employee did a 
``` git commit -m "bla" ```
he committed 2 javascript files. That's it.

The other one was a simple modification inside a repo from developer to master and afterwards a git pull/push by the new master.

Does anyone have more information or a sample for reproducing this issue?

Cheers
Christian

**Comment by apazdnikov** [comment]
Have some ERRORs (~30) in gitlhost.log
February 11, 2015 14:28 -> ERROR -> Grit::Git::GitTimeout

**Comment by apazdnikov** [comment]
and some errors in githost.log with git command FAILED
February 10, 2015 14:06 -> ERROR -> Command failed [1]: /usr/bin/git --git-dir=/home/git/gitlab-satellites/siem/rester/.git --work-tree=/home/git/gitlab-satellites/siem/rester merge --no-ff -mMerge branch 'feature/2-syslog-tcp' into 'develop' source/feature/2-syslog-tcp

**Comment by offlinehoster** [comment]
Any ideas howto reproduce this issue constantly?

**Comment by offlinehoster** [comment]
Do you @apazdnikov  and @rumpelsepp run your gitlab on bare metal or in an virtual env?

**Comment by rumpelsepp** [comment]
@offlinehoster I use Arch linux, using this pkgbuid I wrote with @hunger: https://github.com/rumpelsepp/gitlab-pkgbuilds

```
$ pacman -Q ruby
ruby 2.1.5-1

$ pacman -Q postgresql
postgresql 9.3.6-1

$ pacman -Q git
git 2.3.0-1

$ pacman -Q redis
redis 2.8.19-1

$ pacman -Q linux-lts
linux-lts 3.14.32-1
```

**Comment by apazdnikov** [comment]
all on vSphere.
one under ubuntu 12.04 , another under debian 7.6

**Comment by apazdnikov** [comment]
is it possible to log every execution of git with pid and cmdline?
then we can find where zombies comes from.
Thank you.

**Comment by offlinehoster** [comment]
That sounds good to me…the "log everything" thing.

We're running our gitlab instance inside an openVZ container on a CentOS release 6.6 (Final).

We should find out how to increase the loglevel to be more verbose.

**Comment by apazdnikov** [comment]
it maybe a simple patch

**Comment by morsik** [comment]
I have the same problem. CentOS 6, since GitLab 7.0. I'm updating all the time, and zombies are still here. Running with config from documentation (unicorn).

I was doing `service gitlab restart` all the time I got this. Now I moved to uwsgi when I set workers restart after some time and it prevents too many zombies (dirty hack…).

**Comment by dmaslakov** [comment]
Have the same issue on Ubuntu 14.04, GitLab 7.8.1.

It happens after some time (several days) of normal work. Then it happens that merge requests can't be accepted, merge hangs. `gitlab-ctl restart` does not help.

**Comment by jacobvosmaer** [comment]
See 635f62be67a0a0e7cb02df40317e1c58c78738fb and eca214a671fcbe0a30a643bcaf4691fd7130f6a9

There should be no zombies anymore in 7.14.

**Comment by Razer6** [comment]
:heart:  Let's close it
