### ISSUE TITLE
Error 502 when rendering big commits

### ISSUE THREAD

**Issue by apazdnikov** [gitlabhq/gitlabhq#8784]
Hello. 

First of all - Thank you very much for such a great product Gitlab is.

Have faced with a 502 timeout problem when looking diffs after upgrading from 7.0 -> 7.7.
1. big diffs
2. diffs with submodule promotion to another commit

Have made an example commit of a big file at a public test project on gitlb.com
https://gitlab.com/apazdnikov/test-very-slow-rendering/commit/576ec96bbce1db759a517d429569d2883c243b63

It renders about a minute. At mine installation it fails with 502 error with increased timeouts in unicorn up to 290 seconds.

How can help investigate and solve this problem?

Thank you.

**Comment by Leibniz137** [comment]
I've also encountered this issue. Try increasing the git timeout value in gitlab.yml from the default 10s.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
