### ISSUE TITLE
Segmentation Fault when try to render one commit

### ISSUE THREAD

**Issue by godambrosio** [gitlabhq/gitlabhq#8786]
This is the info in my logs

- This is from gitlab_error.log in my /etc/nginx directory

Proveedores/commit/18258bb6505c9fc7dca7682d5b024781d93d909b HTTP/1.1", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/root/GestionProveedores/commit/18258bb6505c9fc7dca7682d5b0247
81d93d909b", host: "172.16.5.218", referrer: "http://172.16.5.218/"

-This is from unicorn_stderr.log

home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab-linguist-3.0.0/lib/linguist/blob_helper.rb:120: [BUG] Segmentation fault at 0x00000000000000
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

Please let me know if I have to add Information 

Thanks for your time

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
