### ISSUE TITLE
API requires object ID, but impossible to resolve IID to ID effectively

### ISSUE THREAD

**Issue by dmaslakov** [gitlabhq/gitlabhq#8789]
My use case: webhook parses commit messages to find out merge request reference (`!123`), then webhook needs author of merge request.

The problem here is `123` which is merge request IID, while API calls require ID.

To find IID of merge request I see the only way -- do iterate over all merge requests (using `GET /projects/:id/merge_requests`). But this is far from being effective.

I propose the following options:

1. Do not use ID in calls, because `GET /projects/:id/merge_request/:merge_request_id` already assumes the object under particular project and it's OK to identify merge request in scope of the project, i.e. use IID. Unfortunately it breaks backward compatibility.
2. Create new method that will resolve IID to ID and vice versa for any object type.
3. Extend existing methods to take both IID and ID. For example, extend method `GET /projects/:id/merge_request/:merge_request_id` so that it accepts IID like `GET /projects/:id/merge_request/:merge_request_IID?local=true`.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
