### ISSUE TITLE
Web Editor should show custom hook output when comit was rejected

### ISSUE THREAD

**Issue by iakovgan** [gitlabhq/gitlabhq#8795]
When a custom hook failes the commit for some reason, user of Web Editor, get's a message:

> "Your changes could not be committed. Maybe the file was changed by another process or there was nothing to commit?"
> https://github.com/gitlabhq/gitlabhq/blob/master/app/services/files/update_service.rb#L32

It would be nice to provide a error message that explains why commit was rejected. This can be an output from custom hook avaliable here: 
https://github.com/gitlabhq/gitlabhq/blob/master/lib/gitlab/satellite/files/edit_file_action.rb

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
