### ISSUE TITLE
LDAP users cannot login if their LDAP uids has changed

### ISSUE THREAD

**Issue by HofmeisterAn** [gitlabhq/gitlabhq#8804]
In our environment (`GitLab 7.7.2 bd98290`) the ldap user is not able login after he was moved to a different OU. The `extern_uid field` in `identities` won’t be updated.

Currently I use following workaround:
```
su - gitlab-psql
/opt/gitlab/embedded/bin/psql gitlabhq_production
UPDATE identities SET extern_uid = 'NEW LDAP UID' WHERE id = x;
```

**Comment by jsumners** [comment]
My organization likes to change department names as well. So this is affecting me, too.

**Comment by codereflection** [comment]
+1

**Comment by shumushin** [comment]
+1

**Comment by akuznecov** [comment]
+1

**Comment by ridius** [comment]
+1

**Comment by gzpbx** [comment]
+1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
