### ISSUE TITLE
Browsing history back not working when viewing commit from merge request

### ISSUE THREAD

**Issue by per-garden** [gitlabhq/gitlabhq#8815]
Going from merge request

![merge_request](https://cloud.githubusercontent.com/assets/1906176/6253024/be7b18e4-b79e-11e4-9860-7b411ee8ba9f.png)

to associated commit

![merge_request1](https://cloud.githubusercontent.com/assets/1906176/6253035/d842b8fe-b79e-11e4-8818-47093812a05b.png)

Clicking browsing back button takes us nowhere. (Second click takes us two steps back in history).

Affected browsers: Chromium, Firefox. Works in Konqueror.

**Comment by per-garden** [comment]
Gitlab version 7.7.1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
