### ISSUE TITLE
unexpected behavior on MR reviews

### ISSUE THREAD

**Issue by esion** [gitlabhq/gitlabhq#8821]
On a MR I added multiple comments on a single line,

the problems: 
* comments disapear from bottom of discussion and stack earlier
* comments are invisible in diff

I'm not sure how to reproduce

1. developer push commits & create MR
2. I added a comment
3. developer push another commit
4. developer rebase the branch & push force
5. I reload the whole page
6. I add a comment on same line
7. I change tab to discussion and I see a new entry at bottom of discussion but it's mark "outdated diff" 
8. I reload the whole page, the entry disapear ... actually it is stacked earlier in the discussion & hidden

I reproduce 3 times points 5 to 8 (cf. screenshot)

![gitlab_bug_review](https://cloud.githubusercontent.com/assets/65737/6265124/f56214ac-b82a-11e4-84a9-cc1f20a5df54.png)

Let me know if you need more info.

* gitlab version 7.7.2

_note for myself MR320_

**Comment by Mandragora2** [comment]
+1 i have the problem also.
I post a comment in an outdated diff and I must refresh the page to see it :(

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
