### ISSUE TITLE
LDAP email field not updated

### ISSUE THREAD

**Issue by Trefex** [gitlabhq/gitlabhq#8822]
I successfully logged in with a new user via LDAP on gitlab 7.7.2 and it took the _mail_ attribute from the LDAP to populate the email in gitlab. 

However, upon changing the email address in LDAP, the change is not reflected to the gitlab account.

Is this expected behavior?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
