### ISSUE TITLE
[API] MIMEType text/plain instead of application/pdf is sent when requesting a blob

### ISSUE THREAD

**Issue by valeriomazzeo** [gitlabhq/gitlabhq#8826]
**Summary:** MIMEType `text/plain` instead of `application/pdf` is sent when requesting a blob
**Steps to reproduce:** **GET** `projects/:projectID/repository/commits/:commitSHA/blob?filepath=filename.pdf&private_token=youtToken`
**Expected behavior:** MIMEType should be `application/pdf`
**Observed behavior:** MIMEType `text/plain` is returned
**Possible fixes:** change the MIMEType to `application/pdf` for pdf files

**Comment by sadortun** [comment]
+1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
