### ISSUE TITLE
Unable to clear description field on an issue using API calls

### ISSUE THREAD

**Issue by pbendersky** [gitlabhq/gitlabhq#8832]
When using the API, if I send an empty string for the `description` field, GitLab fails to update it.

I reported this on gitlab-ruby first (see https://github.com/NARKOZ/gitlab/issues/110) but it appears the issue is GitLab's.

The following solution was proposed:

> I think I found it: https://github.com/gitlabhq/gitlabhq/blob/master/lib/api/helpers.rb#L126.
>
> If I change if params[key].present? to if params[key] I can pass in an empty string via the API and the description get cleared.

**Comment by asedge** [comment]
I'm not certain that this is the correct solution.  I was just pointing out that making this change on my test instance allowed me to clear the value by passing an empty string via the API.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
