### ISSUE TITLE
Stop GitLabs from adding .git extension to tarballs / zips

### ISSUE THREAD

**Issue by zanematthew** [gitlabhq/gitlabhq#8835]
I've looked into this on previous issues. Currently when you download a tarball, the contents contain my-repo.git, is there a reason the .git extension is added? As I'd like to have it removed. If this is in fact customizable, what is the best way to modify this without impacting core functionality?

https://github.com/gitlabhq/gitlabhq/pull/1526

**Comment by zanematthew** [comment]
And just curious as to what the reasoning is to append `.git` as a file extension?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
