### ISSUE TITLE
API tries to verify CSRF token authenticity

### ISSUE THREAD

**Issue by dorra** [gitlabhq/gitlabhq#8836]
The API tries to verify CSRF token authenticity; should not do that.

Started GET "/admin/projects" for 93.196.90.124 at 2015-02-20 20:55:58 +0100
Processing by Admin::ProjectsController#index as HTML
Completed 200 OK in 92ms (Views: 71.7ms | ActiveRecord: 10.8ms)
Started POST "/projects" for 93.196.90.124 at 2015-02-20 20:56:08 +0100
Processing by ProjectsController#create as HTML
Parameters: {"name"=>"example"}
Can't verify CSRF token authenticity
Completed 422 Unprocessable Entity in 2ms

**Comment by thalesfsp** [comment]
I'm having the same problem, with non-HTTPs external URL :(

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
