### ISSUE TITLE
Gitlab 7.8 web editor broken

### ISSUE THREAD

**Issue by saschagrunert** [gitlabhq/gitlabhq#8845]
When trying to commit via the web interface the applications says that it's not possible to commit.
If I have a look into the githost.log:

```
February 23, 2015 18:33 -> ERROR -> Command failed [1]: /usr/local/bin/git --git-dir=/usr/home/git/gitlab-satellites/namespace/repo/.git --work-tree=/usr/home/git/gitlab-satellites/namespace/repo commit -a -m Add newline
February 23, 2015 18:35 -> ERROR -> Grit::Git::GitTimeout
February 23, 2015 18:43 -> ERROR -> Grit::Git::GitTimeout
February 23, 2015 18:44 -> ERROR -> Grit::Git::GitTimeout
```

Is it possible that this is related to the not quoted commit message?

My gitlab config:
```
System information
System:		
Current User:	git
Using RVM:	no
Ruby Version:	2.1.5p273
Gem Version:	2.4.6
Bundler Version:1.8.2
Rake Version:	10.3.2
Sidekiq Version:3.3.0

GitLab information
Version:	7.8.0
Revision:	825919a
Directory:	/usr/home/git/gitlab
DB Adapter:	mysql2
URL:		https://saschagrunert.de
HTTP Clone URL:	https://saschagrunert.de/some-project.git
SSH Clone URL:	git@saschagrunert.de:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	2.5.3
Repositories:	/usr/home/git/repositories/
Hooks:		/usr/home/git/gitlab-shell/hooks/
Git:		/usr/local/bin/git
```

**Comment by Razer6** [comment]
I linked this to the [regression issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/1100)

**Comment by vsizov** [comment]
weird. I can't reproduce on master.

**Comment by maxlazio** [comment]
I cannot reproduce on gitlab.com which is running 7.8.0 .

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
