### ISSUE TITLE
Side-by-side diff has problems detecting related blocks in some cases

### ISSUE THREAD

**Issue by TurkeyMan** [gitlabhq/gitlabhq#8848]
I commented a block of code, so the change was a bunch of '//' added to the start of a series of lines.
The side-by-side diff doesn't illustrate those blocks side-by-side, with only 2 characters on each line having changed, it rather sees it as the first block removed, and the second block added, which is illustrated below the removed block.

Eg:
```
1  code                                   
2  more code                     
3  even more code               1  //code
                                2  //more code
                                3  //even more code
```

Expect:
```
1  code                         1  //code  
2  more code                    2  //more code
3  even more code               3  //even more code
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
