### ISSUE TITLE
Can't push and %2F on projects urls

### ISSUE THREAD

**Issue by akorti** [gitlabhq/gitlabhq#8853]
Hello after upgrading I have many issues 
The projects urls have %2F instead of slashes and i can't push anymore by http.

Here is the error.
remote: Not Found
fatal: repository

Can you help me please?

**Comment by akorti** [comment]
Another strange think I can pull and push in by ssh but i can't see my changes on gitlab...

**Comment by Razer6** [comment]
Thanks for the issue report. Please reformat your issue to conform to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by rhymoid** [comment]
@akorti If you're using Apache, make sure that you're [not using its default settings](https://github.com/gitlabhq/gitlabhq/issues/8290#issuecomment-88355554).

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
