### ISSUE TITLE
SSL certificates with passwords cannot use builtin nginx

### ISSUE THREAD

**Issue by mattseymour** [gitlabhq/gitlabhq#8856]
It seems as though the built in version of nginx cannot use ssl certificates which are password protected. The configuration file created is correct and will more than likely work but because my certificate is password protected; I am not prompted during the restart of the nginx process for the required passwords.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
