### ISSUE TITLE
LDAP - User OU change blocks user from signing in

### ISSUE THREAD

**Issue by dirkoswanepoel** [gitlabhq/gitlabhq#8862]
If a user is moved to a different OU in an Active Directory, the user can no longer sign in.

**Comment by HofmeisterAn** [comment]
Known issue. Have a look at #8804, for a temporary solution.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
