### ISSUE TITLE
Git clone over ssh after ProxyPass

### ISSUE THREAD

**Issue by jagajaga** [gitlabhq/gitlabhq#8866]
Hello. 
Used `relative_url_path`. So I can access it by `/gitlab`.
I have my apache2 server running on a machine A.
I have there 
```apache
Redirect /gitlab /gitlab/
ProxyPass /gitlab/ http://192.168.0.89/gitlab/
ProxyPassReverse /gitlab/ http://192.168.0.89/gitlab/
```
So I can access gitlab by `mydomain.com/gitlab`.
Everything is ok.

But I can't clone over ssh. (ssh key is added successfully)
```bash
git clone git@mydomain.com:user/repo.git
Cloning into 'repo'...
git@genome.ifmo.ru's password: 
```
So the question is: what do I have to do, to enable `git clone` over ssh?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
