### ISSUE TITLE
WebHook posts wrong commits for rebase

### ISSUE THREAD

**Issue by vlovich** [gitlabhq/gitlabhq#8876]
7.2.2-ee

Similar to how https://github.com/gitlabhq/gitlabhq/issues/8401 has an empty payload on the initial creation of a branch, a rebase causes too many commits to be emitted.  The intervening commits are listed.  Trying to figure out the set of reviewers that are involved with the branch is thus made impossible.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
