### ISSUE TITLE
gitlab backup rake fails on empty project

### ISSUE THREAD

**Issue by t3mux** [gitlabhq/gitlabhq#8878]
I wanted to back up our GitLab via gitlab-rake gitlab:backup:create but the backup fails on an empty repository/project with the following message:

failed: git --git-dir=/var/opt/gitlab/git-data/repositories/xx.git bundle create /var/opt/gitlab/backups/repositories/mirror/xx.bundle --all

error: rev-list died
Backup failed

The hole backup process is stopped because of this.

I suggest the rake should leave out empty projects and continue backing up the other repositories.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
