### ISSUE TITLE
merge request wall notes API endpoint does not differentiate user comments from actions

### ISSUE THREAD

**Issue by mathstuf** [gitlabhq/gitlabhq#8902]
When looking at merge request comments, there is no difference between adding a label or a user adding the text `_Added ~XX label_`. It would be nice to have something to indicate if it was a label change, branch update, status change, or any other action which causes a comment to appear.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by mathstuf** [comment]
This has actually been fixed upstream: there's now a `system` boolean field in the wallnotes API results.

**Comment by jvanbaarsen** [comment]
@mathstuf Thanks for reporting back! :heart:
