### ISSUE TITLE
Issue tracking mentions/closed status are garbled in FireFox

### ISSUE THREAD

**Issue by lilnate22** [gitlabhq/gitlabhq#8903]
how it looks in FF:
![image](https://cloud.githubusercontent.com/assets/882236/6452063/0328b9ae-c101-11e4-80a2-4c7e4555130d.png)

how it looks in chrome:
![image](https://cloud.githubusercontent.com/assets/882236/6452088/3a4e7b6c-c101-11e4-8229-a68af7539440.png)

this is due to the gravatar alt text....

![image](https://cloud.githubusercontent.com/assets/882236/6452163/ac3c5a32-c101-11e4-8f77-1bb1654f684b.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
