### ISSUE TITLE
checkins from different timezones not adjusted for correctly

### ISSUE THREAD

**Issue by ribbles** [gitlabhq/gitlabhq#8908]
GitLab 7.7.2 bd98290
Server timezone: UTC 

In the attached screenshot, the order of checkins is incorrect. The top entry is 5 hours old while the next one is 2 minutes. The user at the top, "Ra" is in a different timezone 12 hours ahead, which accounts for the discrepancy.

![image](https://cloud.githubusercontent.com/assets/527705/6455666/e43653f2-c10b-11e4-8ecc-8e9fed9c9e50.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
