### ISSUE TITLE
Graph & Network tab naming

### ISSUE THREAD

**Issue by nils-werner** [gitlabhq/gitlabhq#8910]
Currently you have two tabs in GitLab, named "Graphs" and "Network". I believe these are named incorrectly:

#### Network

You've probably copied the word from GitHub, where "Network" shows your repository in relation to all its fork, essentially the Network of repositories.

In GitLab however you simply show the [repository revision graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph). Hence, **this should be called "graph"**.

#### Graphs

You are basically showing statistics, prettified using a function graph.

However, due to a *graph* being an integral part of a Git repository, the naming of this tab is fundamentally confusing. It is especially funny that you're saying "Building repository graph", which is particularily incorrect.

So, instead **this should be called "stats"**.

**Comment by Zyphrax** [comment]
+1, have a look at "One more" under https://github.com/gitlabhq/gitlabhq/issues/7505#issuecomment-52393682
And https://github.com/gitlabhq/gitlabhq/pull/7520

**Comment by maxiwell** [comment]
+1. The "network" tabs should show the relationships between forks. =/

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
