### ISSUE TITLE
Merge requests calling Push Event webhook

### ISSUE THREAD

**Issue by solomongifford** [gitlabhq/gitlabhq#8913]
I have GitLab 7.7 installed.
I only have a webhook only enabled on Push Events (specifically not Merge Request events)

Create an accept a merge request results in the webhook being called (with the payload expected for a Push Event).

In our use case, we need push events and merge requests handled separately.  The Push Event handler can not determine whether the call was due to a merge request or a push.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
