### ISSUE TITLE
Deleting branches doesn't trigger MR refresh

### ISSUE THREAD

**Issue by zxqfox** [gitlabhq/gitlabhq#8919]
How to reproduce:
Create a branch, add several commits, push, create MR, squash all added commits, delete remote branch, repush it, and look at MR.
```
git checkout -b deletable-branch
git ci -m "1" --allow-empty
git ci -m "2" --allow-empty
git ci -m "3" --allow-empty
git push origin deletable-branch
# Now create MR for this branch
git reset --hard HEAD~2
git ci --amend -m "another commit"
git push origin :deletable-branch
git push origin deletable-branch
```

Expected:
Same as `git push origin deletable-branch -f`.

Actual:
Old commits still persist in MR.

Possible solution:
Trigger some internal event on branch delete and handle it to refresh MR. Probably close it with deleted status, and reopen that MR if somebody pushed to branch with MR with deleted status.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
