### ISSUE TITLE
project_web_hook EOFError: end of file reached

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#8925]
Something is going wrong with sidekiq and custom_hooks. I use custom hooks to mirror projects from my gitlab instance to github. It works quite fine except these errors in sidekiq:

![screenshot from 2015-03-06 16 32 08](https://cloud.githubusercontent.com/assets/1961699/6527851/5cdda714-c41e-11e4-995d-838c15469ec7.png)

As everthing works as intended I am stuck in figuring out what's the problem here...

**Comment by freecastle** [comment]
Same problem here. I'm using a fresh install of Ubuntu 14.04.2 LTS and a downloaded Omnibus package of GitLab CE 7.10.0 (gitlab-ce_7.10.0~omnibus.2-1_amd64.deb). I've migrated from a source installation of GitLab CE, where this problem never occurred.

**Comment by nordicmachine** [comment]
I'm running an Omnibus install of 7.10.1 and using custom hooks and we get a lot of these as well.

**Comment by molisoft** [comment]
me tooo....

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
