### ISSUE TITLE
Merge requests can be created via the API even when not enabled on a project

### ISSUE THREAD

**Issue by m4tthumphrey** [gitlabhq/gitlabhq#8926]
I was doing some testing for my [API Client](https://github.com/m4tthumphrey/php-gitlab-api/) and noticed that I was able to create a merge request for a project that didn't have merge requests enabled. The 'Merge Requests' link on the sidebar was not visible but the MR was there once I enabled merge requests on the project.

I'm not sure if this is by design or because I am an administrator but thought it was worth pointing out.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
