### ISSUE TITLE
Error with tag that points to a raw hash-object

### ISSUE THREAD

**Issue by ohardy** [gitlabhq/gitlabhq#8927]
I used git hash-object to add my public key to a repository and I tag it. When i try to display tags of this repository in gitlab, i got this in log file :
```
ActionView::Template::Error (Invalid raw commit type: Rugged::Blob):
    1: - commit = @repository.commit(tag.target)
    2: %li
    3:   %h4
    4:     = link_to project_commits_path(@project, tag.name), class: "" do
  app/models/repository.rb:30:in `commit'
  app/views/projects/tags/_tag.html.haml:1:in `_app_views_projects_tags__tag_html_haml___2320308574866459770_40378680'
  app/views/projects/tags/index.html.haml:19:in `block in _app_views_projects_tags_index_html_haml___2991469522415897290_39675960'
  app/views/projects/tags/index.html.haml:18:in `each'
  app/views/projects/tags/index.html.haml:18:in `_app_views_projects_tags_index_html_haml___2991469522415897290_39675960'
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
