### ISSUE TITLE
Enable mass label edit

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#8930]
That's more an annoying usability issue rather than a feature request. Could somebody add a label select field here as well? I don't have any Javascript skills for a pull request but I think it is a minor fix with great impact. :)

![screenshot 2015-03-06 20 35 26](https://cloud.githubusercontent.com/assets/1961699/6534840/ce3efdb4-c440-11e4-9cf8-831677183742.png)

**Comment by phongtt** [comment]
+1
I'm also expecting this feature.

**Comment by Leont** [comment]
+1

That's just what I need right now :-/

**Comment by AbrarSyed** [comment]
+1
I also need this feature

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by Leont** [comment]
> If you think this is still an issue I encourage you to open it on the GitLab.com issue tracker.

[Done](https://gitlab.com/gitlab-org/gitlab-ce/issues/12492)
