### ISSUE TITLE
commits calendar doesn't count commits made to forked projects

### ISSUE THREAD

**Issue by pratapvardhan** [gitlabhq/gitlabhq#8931]
commits calendar doesn't count commits which are made to forked projects nor merge actions are captured.

**Comment by 123Haynes** [comment]
This is a known limitation of the current calendar. We're working on improving this for future releases.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

/cc @123Haynes Can you also confirm if this is still an issue?

**Comment by 123Haynes** [comment]
We've switched from counting commits to counting pushes and other events.  
That also closes this issue :)

**Comment by jvanbaarsen** [comment]
Great! Thanks for looking into this :heart: :cake:
