### ISSUE TITLE
Upgrading 7.4 to 7.8 with 502 errors

### ISSUE THREAD

**Issue by kitsos** [gitlabhq/gitlabhq#8934]
I was update my gitlab server from 7.4 to 7.8 version. After succesful update. I am getting too much 502 Errors. I have 3GB RAM so I don't think is a resources issue. As far i can assume what the problem is I think there some malfunctionality on unicorn or on sidekiq. I see in my sidekiq shutting down approx. every 3 mins. 

My `unicorn.stderr.log` is like this 
```
`I, [2015-03-08T10:31:50.204069 #17629]  INFO -- : master complete
I, [2015-03-08T10:32:00.021882 #18661]  INFO -- : Refreshing Gem list
I, [2015-03-08T10:32:21.090756 #18661]  INFO -- : listening on addr=/home/git/gitlab/tmp/sockets/gitlab.socket fd=12
I, [2015-03-08T10:32:21.091238 #18661]  INFO -- : listening on addr=127.0.0.1:8080 fd=13
I, [2015-03-08T10:32:21.101911 #18661]  INFO -- : master process ready
I, [2015-03-08T10:32:21.213453 #18661]  INFO -- : reaped #<Process::Status: pid 18797 exit 0> worker=0
I, [2015-03-08T10:32:21.213613 #18661]  INFO -- : reaped #<Process::Status: pid 18799 exit 0> worker=1
I, [2015-03-08T10:32:21.213708 #18661]  INFO -- : master complete
I, [2015-03-08T10:32:25.578338 #18885]  INFO -- : Refreshing Gem list`
```
My `sidekiq.log` is like this 
```
`2015-03-08T04:40:30.004Z 26513 TID-osq7tqpvo INFO: Running in ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
2015-03-08T04:40:30.004Z 26513 TID-osq7tqpvo INFO: See LICENSE and the LGPL-3.0 for licensing details.
2015-03-08T04:40:30.004Z 26513 TID-osq7tqpvo INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org/pro
2015-03-08T04:41:47.707Z 26513 TID-osq7tqpvo INFO: Shutting down
2015-03-08T04:41:48.039Z 26513 TID-osq96lyzw INFO: Shutting down 25 quiet workers
Sidekiq shut down gracefully.
Pidfile /home/git/gitlab/tmp/pids/sidekiq.pid does not exist
2015-03-08T04:42:36.024Z 27266 TID-otfzkli0s INFO: Booting Sidekiq 3.3.0 with redis options {:url=>"unix:/var/run/redis/redis.sock", :namespace=>"resque:gitlab"}` 
```
It is not always non-working, but fails every 4-10 clicks on my UI. So it is not usable. 
Is there any suggestion to fix it or I should rollback my installation?

Regards, 

K.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
