### ISSUE TITLE
Overlapping Button

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#8935]
**Information:**
I am currently using master 1475cb9aaae75d37719c8eac92f9483bb2fde416. And this doesn't look right.

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/4362134/6545405/9d48a76a-c5c0-11e4-8728-f7c2f6e348e4.png)

**Comment by duduribeiro** [comment]
The same behavior on e7e329d.
But I don't know if it is a bug. I don't have idea where this button need to be placed :smile:

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
