### ISSUE TITLE
Can't find issue via API: {"message":"404 Not found"}

### ISSUE THREAD

**Issue by marlboromoo** [gitlabhq/gitlabhq#8946]
Hi there,

After upgrading Gitlab from version **gitlab_7.6.2-omnibus.5.3.0.ci-1_amd64** to **gitlab_7.7.2-omnibus.5.4.2.ci-1_amd64.deb**, I can't get new creation issues via API anymore, example:

- /api/v3/projects/4/issues/35 (create at version 7.6.2): success 
- /api/v3/projects/4/issues/36 (create at version 7.7.2): 404 not found
- /api/v3/projects/5/issues/1 (create at version 7.7.2): 404 not found

I also try to upgrade to verson **gitlab_7.8.2-omnibus.1-1_amd64** but no luck, any suggestions?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
