### ISSUE TITLE
error 500 `app_id' for nil:NilClass for github

### ISSUE THREAD

**Issue by raulperezalejo** [gitlabhq/gitlabhq#8964]
in this file 'lib/gitlab/github_import/client.rb'
i am getting the error "undefined method `app_id' for nil:NilClass"
i don't know where the 'config' variable comes, the initialized receive "access_token" but is also nil when i say "access_token.app_id"

i am using 7.8

regards

**Comment by stanhu** [comment]
Are you using the omnibus version? Make sure in the `omniauth_providers` that you include `app_id` (see step 10):

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/integration/github.md

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
