### ISSUE TITLE
Wiki: anchor hyperlinks trimmed when navigation is collapsed

### ISSUE THREAD

**Issue by guiwoda** [gitlabhq/gitlabhq#8969]
The hyperlink icon needs a bit more space in collapsed mode.
See attached image.

Cheers

![gitlab-error](https://cloud.githubusercontent.com/assets/1625545/6712336/c7d73fc6-cd6a-11e4-9e61-89a46ff8dfba.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
