### ISSUE TITLE
7.9.0: Applying a milestone filter to issues causes other milestones disappear from filter menu

### ISSUE THREAD

**Issue by ccharles** [gitlabhq/gitlabhq#8987]
Using  7.9.0.rc3-ee 82a199a as implemented on GitLab.com, when I filter issues by milestone the other milestones disappear from the menu:

![gitlab_filter-any](https://cloud.githubusercontent.com/assets/37932/6754428/d7295cf0-cef2-11e4-96a1-024cd4695c38.png)

*I have two milestones: Version 1.1 and Version 2.0*

![gitlab_filter-1 1](https://cloud.githubusercontent.com/assets/37932/6754430/da4cbcd8-cef2-11e4-9173-71e954d440e3.png)

*When filtering for Version 1.1, Version 2.0 is missing from the dropdown*

Filtering by "None (backlog)" also causes milestones to disappear:

![gitlab_filter-none](https://cloud.githubusercontent.com/assets/37932/6754433/dde01b74-cef2-11e4-9ab8-a666082c7a20.png)

*Here, both milestones are missing.*

Switching the filter from one milestone to another requires that I first select "Any", which repopulates the list of milestones, then select the new milestone for filtering.

**Comment by ccharles** [comment]
This is still an issue under 7.9.1-ee fe6a583.

**Comment by ccharles** [comment]
And 7.9.3-ee b18d07e.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
