### ISSUE TITLE
Autocompletion does not work for closed merge requests

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#8994]
I just updated to GitLab 7.9.0 16d6f0e, the autocompletion for merge requests is broken. For issues it works fine.

This does not affect gitlab.com which obviously is another version.

**Comment by rumpelsepp** [comment]
Ahh, it seems to be "broken" when the merge requests are *closed*, sry. Personally I prefer autocompletion for closed and open issues/merge request.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
