### ISSUE TITLE
Deploy in progress

### ISSUE THREAD

**Issue by dsoap** [gitlabhq/gitlabhq#9009]
I am running Ubuntu 14.04 and Apache I have installed and checked the configurations and everything seems to be fine and GitLab is running. Yet when I go to my URL I get the Deploy in Progress screen only. I am unsure of where to go from here?

**Comment by PaulBGD** [comment]
Having the same issue.

**Comment by Razer6** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the [GitLab.com issue tracker][https://gitlab.com/gitlab-org/gitlab-ce/issues]. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker][https://gitlab.com/gitlab-org/gitlab-ce/issues].
