### ISSUE TITLE
Preview Does Not Show Task List

### ISSUE THREAD

**Issue by jchristman** [gitlabhq/gitlabhq#9011]
The following screenshots show this.

![capture](https://cloud.githubusercontent.com/assets/4226546/6801797/82388c68-d201-11e4-8b0e-0677c09f2e12.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4226546/6801798/8238b6d4-d201-11e4-91a0-ba9fb93c4ef0.PNG)

I'm not sure if this necessarily a bug, but it seems as though it should render the same as the final result.

**Comment by mr-vinn** [comment]
I've noticed a few other things that render differently in previews, too - I'll look into it and see if we can make the preview parsing the same as the real thing.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
