### ISSUE TITLE
Illogical behaviour in building merge request

### ISSUE THREAD

**Issue by dilcom** [gitlabhq/gitlabhq#9013]
Summary: Merging forked repository retrieves build result for fork
Steps to reproduce: 
1. Create repository A
2. Fork repository A into B
3. Add CI services to A and B
4. Add some commits to B
5. Create merge request from B to A
Expected behavior: build status in merge request should relate to CI service binded to A
Observed behavior: build status in merge request relates to CI service binded to B
Last commit SHA1 of my Gitlab: bc57ff0
Possible fixes: I have some ideas about how to fix it but I want to know if it seems illogical only for me or not.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
