### ISSUE TITLE
[7.9] Commit history: branch view with slashes leads to 404

### ISSUE THREAD

**Issue by stefan-it** [gitlabhq/gitlabhq#9022]
Hi,

in addition to #8990 I found another bug in the latest stable release (using 7.9 16d6f0e):

When clicking on "Files" and selecting a branch with contains slashes like `feature/issue-361` the commit history won't be loaded. A *404* error returns:

```
project/refs/feature%2Fissue-361/logs_tree/?_=1427295830339
```

Another interesting point is a *404* error for:

```
refs/master/logs_tree/CISWAB%2FMs-114_OA
```

The folder structure in my GitLab project was `CISWAB/Ms-114_OA/` -> this time no slashes but a "-" sign and an underscore appears in the git foldername. This also lead  to a *404*.

Thanks again!

**Comment by lukaszczerpak** [comment]
Not sure whether relevant to WIKIs also, but previous version accepted folders in page name (i.e.: /wikis/server/security/Hardening-Tips) but 7.9 encodes '/' to '%2F' and edit is no longer possible (results in 404s). 404s are also returned when clicking on a wiki page within search results (if the page is inside any folder).

**Comment by stanhu** [comment]
I think the upgrade from Rails v4.1.2 to v4.1.9 (76aad9b76ed) causes slashes to be esacped. Adding the hotfix (inserting `%2F` in the routes.rb) seems to make the URLs resolve properly. I will submit a pull request.

**Comment by lukaszczerpak** [comment]
Thanks! I've updated routes.rb for wiki pages and it works. So definitely good direction. The question is whether we can go further and just avoid escaping / in paths as it looks strange and inconsistent (maybe I am too purist):
https://<server>/<user>/<project>/wikis/notes%2Fmail_server.md

**Comment by stanhu** [comment]
I was wondering that myself. It looks like we cannot include slashes into the URL itself because Rails does not allow a model to have slashes in them. This Stack Overflow posts confirms what I found:

http://stackoverflow.com/questions/25031791/rails-4-1-2-to-param-escapes-slashes-and-breaks-app

> It looks like the parameterized model is now strictly treated as a single slash-delimited segment of the path and escaped accordingly, with no options to tell the formatter otherwise.

The code in question is here:

https://github.com/rails/rails/blob/4-1-stable/actionpack/lib/action_dispatch/journey/visitors.rb#L159

I even tried to force the `wikis/pages.html.haml` to generate URLs with slashes:

```haml
= link_to wiki_page.title, namespace_project_path(@project.namespace, @project) + "/#{wiki_page.slug}"
```

But that didn't work either because I think the router isn't treating the multiple slashes as a single ID <sigh>  It sounds like either GitLab needs to use the ugly escaped slashes or disable path support altogether.

**Comment by stanhu** [comment]
Fix has been submitted here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/502

**Comment by stanhu** [comment]
I realize that we seem to be conflating two different issues here: slashes in the Wiki page and slashes in the commit history. The latter probably relates to the Rails v4.1.9+ escaping as well.

**Comment by Razer6** [comment]
Closed because MR merged.

**Comment by stefan-it** [comment]
@Razer6 I'm not sure if that MR also patches the commit history problem?

**Comment by stanhu** [comment]
I am running GitLab v7.9.2, and a slash in the branch name works fine for me. Is this a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/1105?
