### ISSUE TITLE
Dashboard Issues set assignee but don't indicate it?

### ISSUE THREAD

**Issue by Codelica** [gitlabhq/gitlabhq#9025]
Hello,

Running 7.8.4 Omnibus on CentOS 6.  

It looks like when I choose the Dashboard "Issues" link it sets the Assignee to the current user by default. (from what i see in the URL)  However this isn't reflected in the Web form on the page -- 
which actually doesn't indicate there are any users.  I imagine defaulting to the current user is correct, but there's just a form issue?

Thanks.

![dashboard gitlab 2015-03-25 10-07-05](https://cloud.githubusercontent.com/assets/386101/6829118/fb2e4524-d2d6-11e4-815c-23a072a18000.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
