### ISSUE TITLE
updating service templates should be reflected in existing repositories that never changed the service settings

### ISSUE THREAD

**Issue by joernhees** [gitlabhq/gitlabhq#9026]
Situation:
 - local gitlab server with 100+ existing repos
 - recently set up slack for the team

We now told our users they can get activity messages from gitlab in their slack channels using the slack integration. We already created the webhook in slack and updated the slack service template in https://<server>/admin/application_settings/services/307/edit .

Going to the settings of an existing repository, this update is not visible even though the users never opened the page. They all need to manually configure the webhook, username and channel :(

It appears to me as if the service templates are copied on repository creation, which now makes it very hard for us to set good defaults in one place. Maybe one could defer this till a service is actually modified on a repository, so that changing the templates would also be useful for existing repositories that later on want to configure a service?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by samy100** [comment]
I'm having the exact same issue. Is there any way to resolve this?
