### ISSUE TITLE
GitLab API Issue State should read Open rather than "Opened"

### ISSUE THREAD

**Issue by StephenOTT** [gitlabhq/gitlabhq#9052]
When reading issues through the API, a issue's state is referenced as either "Opened" or "Closed".  Opened reads as a past-tense as well as a Action: i.e. They Opened the Issue last week, or they opened an issue.  A state should not reference a past-tense.

Opened, should be changed to Open.

Additionally, GitLab UI shows a Issue as Open and Closed, Not Opened and Closed.
![screen shot 2015-03-30 at 1 24 13 am](https://cloud.githubusercontent.com/assets/1994838/6890551/83971b64-d67b-11e4-962e-19b6d99bb05f.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
