### ISSUE TITLE
Enable LDAP in Doorkeeper

### ISSUE THREAD

**Issue by roshangautam** [gitlabhq/gitlabhq#9082]
If you are using grant_type = password for OAuth authentication LDAP logins do not work. You have to use standard password to make it work. It would be wonderful if we can find a way to use LDAP authentication in password type grant_flow in doorkeeper.rb

**Comment by devin909** [comment]
Facing the same issue here...it looks like Doorkeeper looks for "find_for_database_authentication" when you do grant type password.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
