### ISSUE TITLE
Options Select should be wider.

### ISSUE THREAD

**Issue by fabrouy** [gitlabhq/gitlabhq#9086]
[UI]
Admin Area -> Projects -> Transfer project -> When clicking 'Namespace', options select is too narrow.

![trunked_gitlab](https://cloud.githubusercontent.com/assets/5365733/6975416/6356727e-d972-11e4-8daf-7d7098b927d4.png)

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
