### ISSUE TITLE
sudo -u git -H bundle exec rake gitlab:setup RAILS_ENV=production broken

### ISSUE THREAD

**Issue by ghost** [gitlabhq/gitlabhq#9092]
I was trying to install gitlab and when I ran 

sudo -u git -H bundle exec rake gitlab:setup RAILS_ENV=production 

I got back 

rake aborted!
uninitialized constant Rack::Attack
/home/git/gitlab/config/application.rb:79:in `<class:Application>'
/home/git/gitlab/config/application.rb:9:in `<module:Gitlab>'
/home/git/gitlab/config/application.rb:8:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `require'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

How do I fix this?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
