### ISSUE TITLE
Application settings - Signin enabled

### ISSUE THREAD

**Issue by C-Wx** [gitlabhq/gitlabhq#9103]
Let Admin uncheck "Signin enabled" only if OmniAuth is active.
Otherwise you can block you out completely.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
