### ISSUE TITLE
Gitlab packages not cached locally by composer?

### ISSUE THREAD

**Issue by huglester** [gitlabhq/gitlabhq#9135]
Hello,

I am not sure, how to describe the problem. But for example, we are using composer to download packages from github/gitlab.

And packages (tags) from github, are cached by composer:
```php
  - Installing symfony/process (v2.5.11)
    Loading from cache
```

it is loading from cache, if it was at least once downloaded in the past.

But for example, for our gitlab packages, we always get this:
```php
  - Installing pyro-modules/forms (v1.1.1)
    Cloning 72fc88a91e21a7f10275d0fa06b62bcb9a17a380
```
no matter how many times it is downloaded. It is always cloning from gitlab, but not picked up from local cache?

So now the question is, the problem is in gitlab, or maybe in my composer/satis setup?

Thank you

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
