### ISSUE TITLE
Notify people upon unassignment

### ISSUE THREAD

**Issue by Michael-E-Rose** [gitlabhq/gitlabhq#9139]
When I un-assign someone from a issue, that person should get a notification. It's a vital part in the participation process. It also reduces the risk that two people work on the same issue when at the same time someone new is assigned.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
