### ISSUE TITLE
grant_type should not be case sensitive

### ISSUE THREAD

**Issue by JerryLeooo** [gitlabhq/gitlabhq#9141]
I follow the instructions of https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/oauth2.md, and when I use 'AUTHORIZATION_CODE' as grant_type, the server sends
```
{
    "error": "unsupported_grant_type",
    "error_description": "The authorization grant type is not supported by the authorization server."
}
```
back to me, and when I use 'authorization_code' as grant_type, it works.

So, either correct the doc or add support for upper case.
Thanks

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
