### ISSUE TITLE
Integration with Pivotal Tracker can't work with more guys working on same project

### ISSUE THREAD

**Issue by thanhtrancong** [gitlabhq/gitlabhq#9142]
I can configure gitlab integrate with pivotal tracker using my pivotal tracker token. But, if I have more guys working on same project, all commits will show my name on pivotal tracker's story. How to configure this integration for showing correct name of the guys in team?

Thanks.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
