### ISSUE TITLE
redis with unix socket and requirepass

### ISSUE THREAD

**Issue by takeseem** [gitlabhq/gitlabhq#9151]
gitlab not support: redis with unix socket and requirepass

*gitlab-shell fix*
**set redis unix socket and pass (gitlab-shell/config.yml)**
```sh
redis:
  bin: "/usr/local/bin/redis-cli"
  socket: /my/redis/run/redis.sock
  pass: "pwd"
```
**fix**
change the code in gitlab-shell/lib/gitlab_config.rb Line 68
```rb
      if redis.has_key?("socket")
        if redis.has_key?("pass")
          %W(#{redis['bin']} -s #{redis['socket']} -n #{redis['database']} -a #{redis['pass']})
        else
          %W(#{redis['bin']} -s #{redis['socket']} -n #{redis['database']})
        end
      else
```

*gitlab sidekiq how to fix?*
**gitlab/config/resque.yml**
```sh
production: unix://:pwd@:/my/redis/run/redis.sock
```
**console logs/sidekiq.log**
```sh
INFO: Booting Sidekiq 3.3.0 with redis options {:url=>"unix::REDACTED@/my/redis/run/redis.sock", :namespace=>"resque:gitlab"}
ERROR: heartbeat: NOAUTH Authentication required.
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
