### ISSUE TITLE
Why I can't block/unblock users via API?

### ISSUE THREAD

**Issue by shbmira** [gitlabhq/gitlabhq#9152]
Hello there,

I'm creating an internal central system in my work that controls everything, and this includes GitLab.
I need to create an user when a developer is hired and block an user when a developer is dismissed.

First part is ok.
But block user is not possible via "PUT /users/:id", because 'state' is not editable. Why?

Thanks!

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
