### ISSUE TITLE
Merge requests list lack checkboxes for mass editing

### ISSUE THREAD

**Issue by rumpelsepp** [gitlabhq/gitlabhq#9160]
The merge_requests page lacks checkboxes for mass editing. The issue list already supports it. For the sake of consistency the merge request list should support it as well.

I tried to create a pull request myself, but since I don't speak any java-/coffeescript this is a bit too tricky for me. :)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
