### ISSUE TITLE
Getting permissions for a project while listing projects using API

### ISSUE THREAD

**Issue by vr100** [gitlabhq/gitlabhq#9161]
This is a feature / improvement request

Current Behaviour:
Permissions for a project is not retrieved when listing the projects using the "GET /projects" api. Instead, we have to query each project individually using the "GET /projects/:id" api to get the permissions the user has for the given project.
Reference: http://doc.gitlab.com/ce/api/projects.html

Desired Behaviour: 
We are integrating currently with the Gitlab apis. We have a use case where we need to list all the projects for which the user is allowed to add web hooks (that is, the user has the access level - master or owner - for the given project). It would be great if the listing projects "GET /projects" api could also retrieve the permissions for the projects that it lists.

Please let me know if more information is needed.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
