### ISSUE TITLE
Project deletes after trying to download archive

### ISSUE THREAD

**Issue by velichkin** [gitlabhq/gitlabhq#9168]
When I click on "Download zip" (or other formats - it doesn't metter), I receive error with 500 status. On server, project folder disappears. In interface then I see "No repository" error. First time I've found this error on 7.7 version. Then I've upgraded to 7.9.4 and it still exists. I've tried to find out the reason in logs, but haven't found anything helpful.

**Comment by velichkin** [comment]
I've updated to 8.0.5 and issue is still there. Now I'm commenting this button after update. If you haven't time to fix it, disabling button by some new option would be helpful.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
