### ISSUE TITLE
Network graph has some issues with squashed commits

### ISSUE THREAD

**Issue by Zyphrax** [gitlabhq/gitlabhq#9172]
I've created a test git repository to illustrate the problem:

![graph](https://cloud.githubusercontent.com/assets/966500/7291201/279daba8-e9d0-11e4-8068-a8136e5f6a37.png)

This could be a problem with long / multi-line commit messages in general
I'm using the latest version at the moment of writing this: 7.10.0

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
