### ISSUE TITLE
Use AutoMergeWorker in api calls

### ISSUE THREAD

**Issue by aiionx** [gitlabhq/gitlabhq#9183]
In merge_requests controller you do merges with AutoMergeWorker which uses sidekiq.
Why are you not using this when merging through API?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
