### ISSUE TITLE
Commenter doesn't show up as a participant on a thread until after page reload

### ISSUE THREAD

**Issue by oliverbarnes** [gitlabhq/gitlabhq#9191]
Couldn't find this issue by googling or browsing the issues list, I apologize in advance if this is a duplicate (I'm new to the project).

Using the latest version, we just noticed new people commenting on a merge-request don't get added as participants automatically, and therefore don't get notified on replies to them, unless they're specifically mentioned or if they're watching the whole project.

**Comment by oliverbarnes** [comment]
tested again and seems like commenter actually does get added, but the interface only updates after a full reload. and in one case here our commenter didn't have their notifications on :)

but looks like it's an UX issue then?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
