### ISSUE TITLE
To inform which branch or tag is deleted in the message box

### ISSUE THREAD

**Issue by philibe** [gitlabhq/gitlabhq#9193]
When we delete a branch we don't really which is deleted.

In the list of branches or tags, when we click on trash can, we have a message box without the indication of branch or tag.

Because the trash can (at right) is far away of the name (at left), I have often a doubt. I expect in the confirmation message box the precision of the tag or branch is deleted.

A branch or a tag could be very important, and I often a doubt of which branch or tag is deleted.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
