### ISSUE TITLE
Can browse repository but git bash says: FATAL, repository not found

### ISSUE THREAD

**Issue by dmitrynovik** [gitlabhq/gitlabhq#9204]
I am permitted to https://github.com/BlueChilli/ComWriter.git - I cab browse and download sources via the browser, but git bash gives "fatal, repository not found".

The message is not helpful at all because it does not indicate the problem - and I really don't know what's causing the issue - the User, email, and SSH keys are configured and correct.
user.email: cryinstone@gmail.com
user.name: dmitrynovik

HELL, WHAT's THE ISSUE? WHY ON EARTH i CAN BROWSE SOURCES THROUGH THE BROWSER, BUT GIT SAYS IT CANNOT FIND THEM.

**Comment by Senorsen** [comment]
0. This url seems tp be a 404 not found.
0. The whole thread is nothing to do with GitLab? I guess so

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
