### ISSUE TITLE
Inconsistent code span styling in unordered lists & tables

### ISSUE THREAD

**Issue by danseely** [gitlabhq/gitlabhq#9215]
I've noticed that there is some inconsistency with styling when placing code spans inside `<ul>` tags as well as tables. See images. The issue is present when displaying the `README` file as well as inside issue descriptions & comments.
![css-code-in-issue-comment](https://cloud.githubusercontent.com/assets/2266893/7352922/8868677e-ecdd-11e4-94fe-d69d61c7099a.PNG)
![css-code-in-issue-desc](https://cloud.githubusercontent.com/assets/2266893/7352923/8cc7b450-ecdd-11e4-9f37-1ffea4e9ed58.PNG)
![css-code-in-readme](https://cloud.githubusercontent.com/assets/2266893/7352926/907dd48a-ecdd-11e4-802d-66bcd12ba73d.PNG)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
