### ISSUE TITLE
There are plans to integrate docker？

### ISSUE THREAD

**Issue by geekwolf** [gitlabhq/gitlabhq#9221]
The project presentation via  docker

**Comment by dosire** [comment]
I don't understand the question, please see https://github.com/gitlabhq/gitlabhq/tree/master/docker

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by geekwolf** [comment]
not via docker to run gitlab, want to use gitlab  to publish the codes to docker?

**Comment by dosire** [comment]
@geekwolf Feel free to submit something like this.
