### ISSUE TITLE
user comfirm link misses the 'port'

### ISSUE THREAD

**Issue by pyKun** [gitlabhq/gitlabhq#9229]
the url should be "host:post/user/...."

but mine is host/user/....

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
