### ISSUE TITLE
Branch labels underlined when hovered over

### ISSUE THREAD

**Issue by awiddersheim** [gitlabhq/gitlabhq#9250]
On a projects branches page or in the settings of a project when looking at protected branches, if you hover over the branch it will create an underline beneath the labels which does not look very good. Here is an example:

![image](https://cloud.githubusercontent.com/assets/3237256/7492216/83c54744-f3bf-11e4-9425-caa2ef4d21e0.png)

See #9240 for additional information.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
