### ISSUE TITLE
Wiki edit page did not refresh before edit

### ISSUE THREAD

**Issue by truebit** [gitlabhq/gitlabhq#9256]
* user A stayed on the wiki page for some time
* user B edited that wiki page during that time
* user A click "Edit" button to edit the page. 
user A would override the wiki page, discarding user B's work.

So I think click Edit should get the latest content instead of the cache on page

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
