### ISSUE TITLE
[>=7.10] Commit history: Escape special chars 

### ISSUE THREAD

**Issue by stefan-it** [gitlabhq/gitlabhq#9257]
In reference to #9022 I found out that branches with special chars like */* are displayed correctly now, but the url contains the escaped version. 

For me this causes "not found" errors when retrieving the commit history. I guess the only difference to the *gitlab.com* page is that I'm using passenger instead of unicorn.

See this example:

```bash
https://gitlab.com/bminor/mesa-mesa/refs/origin%2Fgallium-tex-surfaces/logs_tree/doxygen?offset=25&_=1430990336589
```

The branch name is "origin/gallium-tex-surfaces" but as you can see on the link above it is translated to *origin%2Fgallium-tex-surfaces*. 

It would be great if that can be fixed :) 

Thanks in advance,

Stefan

**Comment by Razer6** [comment]
@stanhu Is this still an issue?

**Comment by stanhu** [comment]
Thanks for the report. I do see the URLs mentioned, but if you peruse the site, GitLab seems to retrieve the commit data just fine despite the escaped slashes. For example:

https://gitlab.com/bminor/mesa-mesa/tree/origin/gallium-tex-surfaces/progs/beos

I am a little puzzled how this does work because the module `ExtractsPath` doesn't appear to be unescaping the ref ID, but in my debugger the ref shows up properly as `origin/gallum-tex-surfaces` despite that.

@stefan-it, if you're up for it, I would try modifying `extracts_path.rb` (located in `/opt/gitlab/embedded/service/gitlab-rails/lib/extracts_path.rb` with the Omnibus version). Let me know if this helps:

```diff
diff --git a/lib/extracts_path.rb b/lib/extracts_path.rb
index 6e4ed01..9a8ad25 100644
--- a/lib/extracts_path.rb
+++ b/lib/extracts_path.rb
@@ -117,6 +117,7 @@ module ExtractsPath
 
   def get_id
     id = params[:id] || params[:ref]
+    id = URI.unescape(id)
     id += "/" + params[:path] unless params[:path].blank?
     id
   end
```

**Comment by stefan-it** [comment]
Hi Stan,

thanks for your help! I patched the `extracts_path.rb` file, but the error still exists. Here's a sample project where you can see the "not found" error: `https://gitlab.cis.uni-muenchen.de/wast/wast-doc/tree/feature/docker`.

Thanks many in advance for your help!

**Comment by stanhu** [comment]
@stefan-it Thanks for the link. I suspect Passenger is not allowing encoded slashes. Perhaps you need to enable this configuration option?

https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#_passengerallowencodedslashes_lt_on_off_gt

**Comment by thomasschaeferm** [comment]
@stanhu  and @stefan-it 

Thank you very much!!!

**Comment by stefan-it** [comment]
@stanhu Thanks for that great hint. It is working now with the suggested *passenger* option and it is **not** needed to edit `lib/extracts_path.rb`.

Closing now :)

**Comment by stanhu** [comment]
@stefan-it Great! Would you consider submitting documentation on how to make Passenger work with GitLab?

https://gitlab.com/gitlab-org/gitlab-recipes
