### ISSUE TITLE
API create_group 403 Forbidden 

### ISSUE THREAD

**Issue by erwin16** [gitlabhq/gitlabhq#9260]
It seems impossible to create a group into Gitlab.com account  for non admin user via the API even if the user can create a group via the web browser .. Is that a correct behaviour ??

the user is not_admin, but can can_create_groups = true

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
