### ISSUE TITLE
Mobile View Buttons 

### ISSUE THREAD

**Issue by MDXDave** [gitlabhq/gitlabhq#9262]
In the mobile view most of the buttons are behind other objects/lists (e.g. Viewing Issues)

**Comment by MDXDave** [comment]
![screenshot_2015-05-08-00-36-16_1](https://cloud.githubusercontent.com/assets/6099976/7527352/a05777e0-f51a-11e4-8a8c-444ddcb26e31.jpg)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
