### ISSUE TITLE
Premature end of pack file, index-pack failed error when cloning new repo

### ISSUE THREAD

**Issue by demisx** [gitlabhq/gitlabhq#9264]
I am on Mac OS X Yosemite, git 2.4 and GitLab Community 7.10. I don't have issue with repos under 500MB, but when I clone a remote repo with 19K files 5G total, I quite often see get this error at the start of clone:

```bash
fatal: premature end of pack file, 33 bytes missing
fatal: index-pack failed
```

Usually need to try a couple of times before I am able to clone it. I have nginx `client_max_body_size` param set at 300MB and the files am I checking out appear to be under 30MB. Any idea what maybe causing this issue or where to start looking?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
