### ISSUE TITLE
SVG files are displayed as plain text when seing the raw file

### ISSUE THREAD

**Issue by allan-simon** [gitlabhq/gitlabhq#9265]
I perfectly understand that in the diff view etc.  the svg file is rendered as text, as this way it's easier to see if there's just one change in color etc.
but it would great if when showing the raw file, it sends it with the correct mime type

**Comment by stanhu** [comment]
Good idea. Here is the merge request:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/637

**Comment by allan-simon** [comment]
awesome, thanks a lot, as a company doing mainly development and having switch recently to SVG for our icons etc. , it really helps a lot .

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
