### ISSUE TITLE
Referencing lines and groups of lines in issues/bugs/wiki

### ISSUE THREAD

**Issue by juangamnik** [gitlabhq/gitlabhq#9271]
It would be nice to be able to reference a line or a group of lines in a file of a specific commit.

This is the corresponding feature in GitHub:
http://www.morethanseven.net/2009/03/22/github-links-lines-code/

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
