### ISSUE TITLE
Syntax highlighted diffs in issues/comments/wiki

### ISSUE THREAD

**Issue by juangamnik** [gitlabhq/gitlabhq#9272]
It would be nice, to be able to write a code snippet with diff information what has been (or needs to be) changed instead of putting two code snippets one after another. A possible syntax might be to add a `+` or `-` sign before a line (or a space in order to differentiate between a diff sign and a private/public method definition in obejctive-c, for eyample)  and it is interpreted accordingly. Example:

```swift(wdiff)
 func foo() {
-  println("foo")
+ println("bar")
 }
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
