### ISSUE TITLE
Links to files in gitlab markdown do not point to default branch

### ISSUE THREAD

**Issue by juangamnik** [gitlabhq/gitlabhq#9273]
My default branch is set to develop, but still when I add a link to a file as described in the gitlab flavored markdown guide (`help/markdown/markdown#special-gitlab-references`) `[file](path/to/file)` it always points to the "master" branch. I cannot find a way to change the branch to `develop` or another branch or to a specific commit ...

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
