### ISSUE TITLE
gitlab does not open default git:// protocol port 9418 and documentation is missing

### ISSUE THREAD

**Issue by ssbarnea** [gitlabhq/gitlabhq#9284]
It seems that there is no information regarding enabling the default git:// protocol port 9418 in gitlab.

**Comment by morsik** [comment]
I don't think GitLab uses this anyway… There is no daemon listening on 9418.
All docs says about using git via ssh or http(s).

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
