### ISSUE TITLE
Gitlab sending multiple web-hooks?

### ISSUE THREAD

**Issue by huglester** [gitlabhq/gitlabhq#9286]
Hello,

could it be possible, that GitLAB (starting from 7.8 or up) is somehow sending multiple Webhooks?

For example I have a satis server, which starts a build on webhook sent from GitLAB, but I somehow I see one satis build started, and then in ~10 seconds one more.

I looked ar some cacti graphs, and yes, I see the load is bit higher now:
http://pic.webas.lt/webas.lt-dbb784ceec.png

Thanks

**Comment by megaponchic** [comment]
+1 the same issue

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
