### ISSUE TITLE
API - list issues order_by updated_at not working 

### ISSUE THREAD

**Issue by JumBay** [gitlabhq/gitlabhq#9292]
I'm trying to sort all closed project's issues order by "updated_at" desc, but if an issued has been closed, reopened then closed again it won't sorted as it should be

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
