### ISSUE TITLE
Comments in diff views is reported as being posted  , but refreshing the page display nothing

### ISSUE THREAD

**Issue by allan-simon** [gitlabhq/gitlabhq#9298]
i'm using version  7.9.1 

when i try to post a comment, (not on a specific lines, i know there used to be a bug about comments being posted on the first line of a file)  the comment is reported as posted (i got the UI feedback that the form disapear and is replace by the comment view) 

the POST to notes  report a 200 ,  with a correct json (container  an id, a discussion id etc.) 

but refreshing the page does not display it

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
