### ISSUE TITLE
Search string with spaces does not find search string

### ISSUE THREAD

**Issue by haisamido** [gitlabhq/gitlabhq#9312]
When a query search string has one or more white spaces the search does not find matches. The search string in the below example is 'Unix distributions'

gitlab: 
https://gitlab.com/search?utf8=%E2%9C%93&search=Unix+distributions&group_id=&project_id=13083&search_code=true&repository_ref=master ,  returns no results. While if one searches for 'distributions' https://gitlab.com/search?utf8=%E2%9C%93&project_id=13083&group_id=&snippets=&scope=&search=distributions a successful search is found.

github: https://github.com/gitlabhq/gitlabhq/search?utf8=%E2%9C%93&q=Unix+distributions

**Comment by haisamido** [comment]
Also searches take extremely long!

**Comment by dosire** [comment]
@haisamido this is important functionality and we welcome merge requests to improve it!

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
