### ISSUE TITLE
No authentication methods configured.

### ISSUE THREAD

**Issue by lipangit** [gitlabhq/gitlabhq#9336]
I cancel the signin feature in setting page.
And I can not find setting.rb to change the config [signup_enabled]  in path /opt/gitlab.
I remember I install by this page https://about.gitlab.com/downloads/
SO where is my setting.rb file.
Thank you.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
