### ISSUE TITLE
OmniAuth CSRF protection break the Atlassian Crowd provider

### ISSUE THREAD

**Issue by hudecof** [gitlabhq/gitlabhq#9337]
*Atlassian Crowd* is using  `OmniAuth::Form` to build the login form. In the form is missing the CSRF token.
Is there any way how tu push the CSRF token to OmniAuth without patching the OmniAuth provider?

See my hack to get it work on https://github.com/gitlabhq/gitlabhq/issues/1240

I do not think this new feature has been heavy tested and is finished. How could you pass this token to the other providers?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
