### ISSUE TITLE
Should this set up not allow me to force push a protected branch?

### ISSUE THREAD

**Issue by m4tthumphrey** [gitlabhq/gitlabhq#9342]
I've noticed that for new projects (last month or so) that I create, the master branch is defaulted to protected. That's fine. But today I tried pushing to some of them and got the error below.

```
remote: GitLab: You don't have permission
To git@git.domain.co.uk:components/test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

This is the member set up for that project:

![Members](https://photos-4.dropbox.com/t/2/AAAPUoMDyNgPxaHxfJhyft4PGipHL86EQC0FBnUreSkaOw/12/20898265/png/32x32/1/1432821600/0/2/Screenshot%202015-05-28%2013.14.00.png/CNnD-wkgASACIAMgBCAFIAYoASgC/N-aPCQglXwMNch2pw84uFAfVTsJ4dUT0sW68CPm8dsg?size=1280x960&size_mode=2)

Surely this should allow me to push being in the group as the owner?

**Comment by stanhu** [comment]
What version of GitLab are you running? Can you show the output of `sudo gitlab-rake gitlab:check`?

**Comment by m4tthumphrey** [comment]
@stanhu 7.10.1 754f672

I assume mean this command? `sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production`

Everything is green in that output..

**Comment by m4tthumphrey** [comment]
Ok, so I just upgraded and the problem is still there. But I now know the specific edge case in which it happens. I can push to a protected branch fine if it's a normal push. But if I'm force pushing (`git push --force`) I get the following error message, which has changed for 7.11:

````
remote: GitLab: You are not allowed to force push code to a protected branch on this project.
To git@git.windsor-telecom.co.uk:components/test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

So looks like this is semi by design? IMO it should still let me force push as I'm still the owner of the group.

Thoughts?

**Comment by stanhu** [comment]
Right, this is by design. Perhaps an option should be added to allowed owners to force push to a protected branch, but you can workaround the issue by disabling the protected branch and re-enabling it when you're ready.

**Comment by m4tthumphrey** [comment]
Yeh now I know that it's explicitly because I was forcing it's not an issue! :)

**Comment by rulatir** [comment]
... aaand how do I unprotect a branch for manual override?

**Comment by m4tthumphrey** [comment]
@rulatir Go to the project's settings page from the left menu and then select Protected Branches. You can delete it, push then reprotect.

**Comment by leycec** [comment]
**This is an unfortunate default.**

While I sympathize with the core reasoning, having to manually and unprotect branches to perform forced pushes arguably invites even _larger_ issues. During the brief window in which the branch is unprotected, users who would otherwise be prohibited (e.g., developers) from pushing are permissively allowed. Likewise, accidentally neglecting to reprotect the branch after the forced push leads to a grim, feces-smeared alleyway of insecurity and woe.

> Perhaps an option should be added to allowed owners to force push to a protected branch,

Certainly, that would be helpful. Ideally, such option would be enabled by default for new projects. Owners should be assumed to be innocent rather than guilty, and sufficiently aware of the pitfalls (and occasional benefits) in forced pushing.

**Comment by m4tthumphrey** [comment]
I would agree with @leycec :+1:

**Comment by sampablokuper** [comment]
@m4tthumphrey , since you agree with @leycec , please could you reopen this issue? Thanks! (Alternatively, if there's already an open feature request to implement @leycec's proposal, would you mind linking to it from this thread? Thanks!)

**Comment by cmuller** [comment]
Yes please reopen the issue. I would not vote in favour of the force allowed by default but an option to allow owners would definitely be nice. I have the problem with a bot actually making synchronizations and it is important to have forced mirror push in order to ensure the replicated repo is exactly similar.
In the meanwhile I am going to investigate in the API if it is possible to automatically remove protections from repos on the mirror. (Note Gitlab Geo usage would be a bit tricky because some groups are primary on one node and some others on the other node.. :-) ).
