### ISSUE TITLE
Backup problem

### ISSUE THREAD

**Issue by thelinuxlich** [gitlabhq/gitlabhq#9343]
I was using Gitlab 7.11.2 but my VPS instance had a security problem and I had to backup it to rebuild it but in the meantime Gitlab 7.11.4 was released and it is the only version available on ubuntu, thus invalidating my backup, what can I do?

**Comment by stanhu** [comment]
You can download older versions here:

https://packages.gitlab.com/gitlab/gitlab-ce

I think your backup should still work with GitLab v7.11.4; there were only minor changes between v7.11.2 and v7.11.4.

**Comment by thelinuxlich** [comment]
it doesn't work unless there is a trick to fool the rake task

**Comment by stanhu** [comment]
Can you clarify what exactly is wrong?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
