### ISSUE TITLE
Relative URL for Avatars

### ISSUE THREAD

**Issue by jangrewe** [gitlabhq/gitlabhq#9344]
I have an issue with avatars not showing up because they are always requested from the configured URL, not the hostname i'm accessing GitLab on (and into which i'm logged in).

If i have http://gitlab.example.com configured that the site URL, and access GL via http://gitlab, the avatars are requested from http://gitlab.example.com, for which i (sometimes) don't have a login session.

I'm not sure if there are any security implications to this, but i think they should be loaded from the same hostname that the site is being accessed, probably most easily accomplished by just using a relative URL instead of prepending the hostname, too. Another option would be to generally redirect all accesses to the configured hostname, so that this issue doesn't happen.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
