### ISSUE TITLE
[Potential Bug] Project List Anchor Redirection Error

### ISSUE THREAD

**Issue by vinkla** [gitlabhq/gitlabhq#9347]
We've an error on our current setup where an old project has all of a sudden become empty and the link to the repository links to another projects archive file.

1. Visit the group page.
2. I click on the project I want to visit (the anchor seems to be correct in the web inspector).
3. I'm being redirected to another project in the same group and to its `archive.zip` file.

Isn't this very strange? We are running GitLab `7.11.1` and Shell `2.6.3` on a Debian installation. What information can I provide to easier get help with this issue?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
