### ISSUE TITLE
Get false on very large diff download

### ISSUE THREAD

**Issue by Soullivaneuh** [gitlabhq/gitlabhq#9357]
One of our customers has a MR on a project with a diff patch size of ~8.8Mo.

Obviously, this diff can't be show on interface.

But if we try to download it, we simply got a text response with `false` content inside.

Does Gitlab have size limit for `.diff` download or is that an issue?

On first case, could we adjust this size limit over configuration?

Regards.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
