### ISSUE TITLE
Invalid Feed Due to Incompatible Date Format

### ISSUE THREAD

**Issue by p3k** [gitlabhq/gitlabhq#9366]
We are running version 7.11.4 / b725318 and currently observe all items of the dashboard feed having the date 1970-01-01 01:00 in our feed reader (Thunderbird)…

Validating the feed with http://validator.w3.org we get the following message:

```
This feed does not validate.
line 12, column 35: updated must be an RFC-3339 date-time: 2015-06-08T07:57:02UTC (20 occurrences) [help]
    <updated>2015-06-08T07:57:02UTC</updated>
                                   ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.
line 274, column 35: Two entries with the same value for atom:updated: 2015-06-03T10:46:04UTC [help]
    <updated>2015-06-03T10:46:04UTC</updated>
                                   ^
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
