### ISSUE TITLE
Accepts null as extern_uid with Shibboleth OmniAuth

### ISSUE THREAD

**Issue by Aethylred** [gitlabhq/gitlabhq#9369]
We had an issue with the SP not requesting HTTP_EPPN correctly when authenticating users, this meant some users were logging in with a null extern_uid

```
May 25, 2015 17:49: (OAuth) saving user X@site.one from logi
n with extern_uid => X@site.one
June 03, 2015 11:22: (OAuth) saving user Y@site.two from login wi
th extern_uid =>
June 03, 2015 11:35: (OAuth) saving user Y@site.two from login with extern_uid =>
June 03, 2015 11:37: (OAuth) saving user Z@site.three from login with extern_uid =>
June 03, 2015 14:42: (OAuth) saving user Y@site.two from login with extern_uid =>
June 03, 2015 15:20: (OAuth) saving user A@site.one from login with extern_uid => A@site.one
```

This meant users Y and Z had the same null extern_uid and kept logging in and getting the same 'identity'

The expected outcome was that users with a null extern_uid would be rejected as unauthorized.

**Comment by Aethylred** [comment]
We set up the following require in the Apache config:

```
require shib-attr eppn ~ ^.+$
```

Which produced the expected outcome, however it should also be checked at the application level by GitLab.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
