### ISSUE TITLE
Problem in Group Members RestAPI pagination

### ISSUE THREAD

**Issue by lokeshkumar** [gitlabhq/gitlabhq#9374]
Hi All,

While trying to get the group members by sending api request recursively along with the page number am getting the same response. I think there is some issue in the pagination in group members api.

Example api requests commands:

    curl -H "PRIVATE-TOKEN: <PRIVATE_TOKEN>" http://git/api/v3/groups/123/members?page=1
    curl -H "PRIVATE-TOKEN: <PRIVATE_TOKEN>" http://git/api/v3/groups/123/members?page=2

While executing the above commands am getting same response and it is same for any page number due to this am not able to find that i have got all the group users or not.

Anybody please help me by fixing this issue.

Thanks in advance.

Regards,
Lokesh

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
