### ISSUE TITLE
API: No way to find out if user has access to a project

### ISSUE THREAD

**Issue by gubby** [gitlabhq/gitlabhq#9389]
There appears to be no way to use the API to answer either of the following questions:

* Which projects does $USER have access to?
* Does $USER have access to $PROJECT?

The endpoint `/api/v3/projects/:id/members` lists the users that are directly a member of a given project, but not those that inherit their membership via the project's group.

The workaround is to make quite a few API calls; i.e.:

1. Get the group for a project,
2. Build the list of users in the group,
3. List the direct members of the project,
4. Then finally work out the maximum access level granted by both the group and direct project membership for each.

My suggestion would be a parameter to `/projects/:id/members` e.g. `transitive=true` that then returns the full set of project members that have access to a project.

**Comment by stanhu** [comment]
Right, you make a good point. I agree that the API should support this use case via a parameter (would `full` be better than `transitive`?). Would you care to send a MR for this?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
