### ISSUE TITLE
Issues with large commit handling: moving lots of images causes 502

### ISSUE THREAD

**Issue by Blaisorblade** [gitlabhq/gitlabhq#9405]
I've run into a variation of #2259 (partially fixed by #5014).
A user of my GitLab instance has a commit where he moves around 1GB of images — viewing that commit fails a 502 error. Creating a merge request for the branch containing that commit does the same.

After increasing the unicorn timeout to 360 (`unicorn['worker_timeout'] = 360` in `/etc/gitlab/gitlab.rb`), I get instead a partial diff. It says:

"Too many changes.
To preserve performance only 100 of 1383 files are displayed."

For many of the shown files, it either says "No preview for this file type" (for .psd files) or shows the images themselves.

The host seem powerful enough for Gitlab: Gitlab's running (through Docker) on a 12-core Xeon E5-2420 2.20GHz, 32GB RAM and SSD... For comparison, `git show -M --stat` on the offending commit takes ~7s, and `git show --stat` takes ~13s, while `diff-tree -r` is instantaneous (and the files are moved unchanged).

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
