### ISSUE TITLE
Web UI + custom hook + ruby

### ISSUE THREAD

**Issue by iakovgan** [gitlabhq/gitlabhq#9409]
Hi, 
I need to use some ruby tools from custom hook and i find that ruby bahaves differently for commits made from Web-UI and classic http/ssh push. 

Ruby script shows varios exceptions, generally related to the fact that some ruby gems are not found.  The issue appears only for Web-UI commits. 

I used following workaround for this issue: 
```
# my .../custom_hooks/post-receive:
# clean up GitLab Web-UI env variables 
unset GEM_PATH
unset RUBYOPT

# start my ruby tool.
...
```
This works fine, but still this is a workaround for an unexpected GitLab behavoir. Can GitLab Web-UI clean up env varibles before calling custom_hook script? 

Regards, 
Iakov

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
