### ISSUE TITLE
The returned json strings in the API documentation doesn't match with the actual Json strings returned

### ISSUE THREAD

**Issue by bhargavms** [gitlabhq/gitlabhq#9414]
The returned json strings in the API documentation doesn't match with the actual Json strings returned for the "author" object in the return json string for GET request to "/projects/:id/issues". Also the returned json string for "http://localhost:3000/oauth/authorize?client_id=APP_ID&redirect_uri=REDIRECT_URI&response_type=code". Please update the documentation.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
