### ISSUE TITLE
LDAP users can't login if Password contain special characters

### ISSUE THREAD

**Issue by real-napster** [gitlabhq/gitlabhq#9415]
Hey Guys,

got a GitLab CE on my Server connected to LDAP. User can only Login through LDAP. If a Password contains a special character the Authentication failed and I cannot clone, fetch, push... whatever!

Ist this a config Problem on my Server or does GitLab have problems with this?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
