### ISSUE TITLE
Install documentation does not set postgresql database encoding

### ISSUE THREAD

**Issue by lloeki** [gitlabhq/gitlabhq#9420]
The following is found in the installation documentation, section database.

```CREATE DATABASE gitlabhq_production OWNER git;```

This is probably what's expected instead:

```CREATE DATABASE gitlabhq_production OWNER git ENCODING utf8;```

This poses no problem for english-speaking users and is probably why it easily went under the radar.

This is very troublesome as following documentation such as in `doc/update/mysql_to_postgresql.md` will create an utf8 dump that will not be restored correctly (this just happened).

**Comment by stanhu** [comment]
It looks like the omnibus version uses `utf8` by default, which is probably why most people don't run into this issue. Could you submit a pull request for these documentation changes?

**Comment by lloeki** [comment]
Traced the problem to come from postgresql having been installed *before* system locale was set to utf8, which created `template0` and `template1` with a C locale. It should happen only very rarely (turns out Digital Ocean's default Debian image locale is set up like that).

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
