### ISSUE TITLE
CI runner coverage not properly displayed

### ISSUE THREAD

**Issue by BridgeAR** [gitlabhq/gitlabhq#9433]
If you add the `Test coverage parsing` and have more than one job per commit the coverage will only be visible next to the job and not in the commits overview if it's not the last job that should be looked at for the coverage. And the jobs are in random order.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
