### ISSUE TITLE
Plain text emails lack content of HTML emails

### ISSUE THREAD

**Issue by warsaw** [gitlabhq/gitlabhq#9434]
Let's say a new issue is created on my project.  I get an email which contains:

message/rfc822
  multipart/alternative
     text/plain
     text/html

The text/html part contains the actual contents of the new issue, but the text/plain part only gives me the very basic, e.g. that a new issue was created, who the author was, and the link to the gitlab.com issue.

Please include at least the contents of the initial bug report in the text/plain part.  Ideally it should be functionally similar to the text/html part.  This also shouldn't be limited to just new issue emails.

**Comment by stanhu** [comment]
Indeed, this is non-ideal. This seems like an easy issue to fix, but there are a lot of e-mails to go through:

https://github.com/gitlabhq/gitlabhq/tree/master/app/views/notify

The text/plain types are in the *.text.erb files. Would you consider helping us out to make this better?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
