### ISSUE TITLE
I have to change my ssh-key frequently

### ISSUE THREAD

**Issue by xidui** [gitlabhq/gitlabhq#9450]
Every time I added a ssh-key to the gitlab, it will work for several days without having to input my password. But it just for several days, sometimes one day.
Then I can not pull or push my code unless I change a new ssh-key.
I wonder why? and what can I do if I don't want to change the key any more?
<img width="599" alt="qq20150712-1 2x" src="https://cloud.githubusercontent.com/assets/4591091/8637754/21e95eca-28d5-11e5-983e-df930b66b90c.png">

**Comment by stanhu** [comment]
Are you generating SSH keys with an expiration date (e.g. `-t` option)?

**Comment by xidui** [comment]
After I clone the repo with http instead of git, the problem never occur again.
But I still have no idea why the previous problem occurred.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
