### ISSUE TITLE
Dashboard event filters should be more evident, or moved to profile

### ISSUE THREAD

**Issue by bostjan** [gitlabhq/gitlabhq#9454]
Hi,

I've spent about an hour (cumulatively over a couple of days) wondering and trying to figure out why activity is occasionally not showing up, only to find out that those blue/grey buttons at the top do not function as tabs, but as filters.

I believe they should be either:
- changed so something that reflects on/off status better (image switches between x and ✓ symbol), or
- moved to profile settings.

This is just my 2 cents of personal UX with GitLab.

What does the community think about this?

Best regards,
b.

**Comment by stanhu** [comment]
I agree that that the filters could be more visually obvious. Perhaps some of the ideas under the "Filter" section could be applied?

http://www.smashingmagazine.com/2012/04/10/ui-patterns-for-mobile-apps-search-sort-filter/

**Comment by bostjan** [comment]
Probaby the presence of additional button "All" or "Show all" would be a good-enough clue.

b.

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by bostjan** [comment]
Excellent! :)
