### ISSUE TITLE
Sorting issues not working

### ISSUE THREAD

**Issue by 3rdcycle** [gitlabhq/gitlabhq#9458]
Changing the sort order in the top right corner of the issues page seems to activate a filter instead. I tried selecting e.g. _Milestone due soon_ from the drop down menu. This reduces the list of displayed issues when I would have expected them to just show in a different order. Also, the new order is not reflected in the _sort_ button title.

I'm running GitLab 7.12

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
