### ISSUE TITLE
Repo sync with gitlab giving issue

### ISSUE THREAD

**Issue by percy-g2** [gitlabhq/gitlabhq#9470]
fatal: https://gitlab.com/mygroup/myproject/info/refs not valid: is this a git repository?

git pull and push is fine with ssh and without ssh .

**Comment by MarkJonas** [comment]
The original description is a little terse so I hope that the problem I am experiencing is the same: I try use Google Repo to clone repositories from a GitLab server and it fails if I use HTTP but it works flawlessly when using SSH.

I have an instance of GitLab 7.13.3 running. I host several repositories on it and want to use Google Repo to comfortably clone all of them in one go. This is the manifest file I am using (changed some names for privacy reasons).

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>

  <default sync-j="1" revision="master"/>

  <remote fetch="ssh://git@some.server.com" name="fir"/>

  <project remote="fir" revision="refs/tags/yocto-1.7.2" name="yoctoproject/poky" path="poky"/>
  <project remote="fir" revision="dizzy" name="yoctoproject/meta-fsl-arm" path="meta-fsl-arm"/>
  <project remote="fir" revision="dizzy" name="openembedded/meta-openembedded" path="meta-openembedded"/>

</manifest>
```
Doing a `repo sync` with the manifest file above works just great. If I substitute the remote given above with one which uses HTTP it fails.

```
  <remote fetch="http://some.server.com" name="fir"/>
```

The error message is the following.

```
$ repo sync
Username for 'http://some.server.com': someuser
Password for 'http://some.server.com': 
Fetching project yoctoproject/meta-fsl-arm
fatal: http://some.server.com/yoctoproject/meta-fsl-arm/info/refs not valid: is this a git repository?
```
I need the feature to use HTTP with Repo because in my network some people are only able to access the GitLab server using HTTP.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by timkoers** [comment]
What is the fix?

**Comment by ramtej** [comment]
same issue here.. What is the fix ?
