### ISSUE TITLE
Slow performance with 16,000 commits / 16,000 tags

### ISSUE THREAD

**Issue by linagee** [gitlabhq/gitlabhq#9473]
I have a repo that has about 16,000 commits and 16,000 tags.
When I pull it up in GitLab, it takes around 10 seconds to render the commits page and 4 seconds to render the tags page. Is there any way to get this to come up faster? Looking at 'top' inside the server, it seems the problem is one ruby process on one core using 100% cpu. (Looks like a unicorn worker.) The server is using an AMD Phenom II X4 975. If I were to switch to an Intel Core i7-4790K which apparently has better single core performance, do you think I would see an improvement? Is there anything I can tune anywhere that would help? It does not appear to be running out of RAM and it has 8GB available. It does not appear to be I/O bound looking at iowait.
Thanks.

edit: It seems that the commits page I was pulling up only lists 40 commits. So, this command should emulate what its doing: (I've set my git pager to cat) Not sure why this takes about a second where GitLab takes 10x as long to display the same thing?
```
time git log --all --oneline -n 40 >/dev/null

real	0m0.895s
user	0m0.868s
sys	0m0.028s
```

**Comment by stanhu** [comment]
What version of GitLab are you using?

**Comment by linagee** [comment]
GitLab 7.12.2 30bffd5 (it says up to date)

**Comment by stanhu** [comment]
Looks like there is some GitLab optimization work is needed. I added 16,000 tags to the Linux kernel repository. This is the New Relic data I see for the commits page:

![image](https://cloud.githubusercontent.com/assets/963826/8840163/4a8c1a4c-3092-11e5-84c8-69af51fff280.png)

For the tags page:

![image](https://cloud.githubusercontent.com/assets/963826/8840173/6ae8c8a8-3092-11e5-8888-9c0d901aedbb.png)

It looks to me that the bottlenecks are in the controller code. Will have to use `ruby-prof` to drill down more.

**Comment by linagee** [comment]
This is really great work. It makes me wish I knew more about the internals of the DB that GitLab is using!

**Comment by stanhu** [comment]
Here's a partial snippet of the profiler of the commit controller. It's quite a tree:

![image](https://cloud.githubusercontent.com/assets/963826/8846285/9fa053ca-30da-11e5-819b-18266f9f5c90.png)

It looks to me like Markdown processing is consuming most of this time.

Here's the profile of the tags controller:

![image](https://cloud.githubusercontent.com/assets/963826/8846303/cd0e04a6-30da-11e5-8fd8-e6d2d2041546.png)

In this case, it looks like the bulk of the time is spent reading from the Redis cache. That is surprising to me.

**Comment by stanhu** [comment]
I did some more digging. It looks like the `empty?` call is normally pretty fast (e.g. calling it 78 times  only took < 300 ms), but when you add 16,000 tags this increases to ~3 s. I also profiled and studied `libgit2` in more detail, and it looks like it [iterates through each tag](https://github.com/libgit2/libgit2/blob/bf7d2761d4d9da79c3ae26e94da6a95b27e8769f/src/repository.c#L1774) and calls `lstat()` to check whether the file is a link. This requires a lot of filesystem access, which is why this is slow.

@tsigo Do we even need the `repository.empty?` check? We could cache the result, but removing this  things up significantly.

**Comment by tsigo** [comment]
@stanhu I didn't write the RelativeLinkFilter so I'm not as familiar with it as I am with the others. Removing the `empty?` check does break the specs, however.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
