### ISSUE TITLE
Disable edit button in wiki when edititing

### ISSUE THREAD

**Issue by blackshadev** [gitlabhq/gitlabhq#9476]
Upon editing an article within the wiki pages. Please remove or disable the edit button.

if a user decides to preview his edits and wants to go back editing, he will think it is a good idea to press the edit button. But this reloads the edit page and thus all progress on the page is lost.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
