### ISSUE TITLE
TortoiseGit clone new project find error

### ISSUE THREAD

**Issue by longting** [gitlabhq/gitlabhq#9494]
Cloning into 'C:\Users\Administrator\Desktop\rtas'...
fatal: http://192.168.1.230/server_rta/rtas.git/info/refs not valid: is this a git repository?

git did not exit cleanly (exit code 128) (546 ms @ 2015/7/28 15:13:07)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
