### ISSUE TITLE
Kernel Ressource update needed

### ISSUE THREAD

**Issue by thorian93** [gitlabhq/gitlabhq#9499]
On my VPS running Ubuntu 14.04 LTS 64bit I had issues getting GitLab CE Omnibus to work.
I followed the instructions for my OS on https://about.gitlab.com/downloads/ and made the necessary changes for GitLab to work with Apache2. That far: No noticeable problems.
But when I tried to do a `gitlab-ctl reconfigure` I was not able to get the built-in postgresql server running.
After days of research and no helpful content online I identified two kernel parameters as the villains: `kernel.shmmax` and `kernel.shmall`.
As far as I can tell the problem is the following: The correct values for GitLab to work are set in `/etc/sysctl.d/90-postgresql.conf` but without a reboot the old values stay active. In my case my server provider had too small default values.
Maybe it is possible to have `gitlab-ctl reconfigure` update the kernel parameters with:

`sysctl -w kernel.shmall=123456`
`sysctl -w kernel.shmmax=123456`

This is my first issue so if I am missing important information or if I said too much please let me know.

**Comment by stanhu** [comment]
You can reload the `sysctl` parameters this way too:

```
sudo sysctl -p /etc/sysctl.conf
```

[The GitLab documentation](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/common_installation_problems/README.md#postgres-error-fatal-could-not-create-shared-memory-segment-cannot-allocate-memory) also explains how you can limit PostgreSQL's memory usage.

I don't think `gitlab-ctl reconfigure` should be tampering with `sysctl` parameters. Going forward, I think GitLab should upgrade to PostgreSQL 9.4 since it doesn't require tinkering with these values.

I'll close this issue for now. 

/cc: @maxlazio
