### ISSUE TITLE
Project page > Too many icons?

### ISSUE THREAD

**Issue by andytruong** [gitlabhq/gitlabhq#9507]
Can reduce number of icons on sidebar? When I collapse the sidebar, it's hard to find the tab I want to go.

![gitlab-project](https://cloud.githubusercontent.com/assets/41143/8975009/f9ee62fe-36a2-11e5-80f4-85d73146a1dc.png)

![icons](https://cloud.githubusercontent.com/assets/41143/8975060/8944c8a8-36a3-11e5-81ac-b3c4f50f2ae5.png)

**Comment by mrsinguyen** [comment]
Yeah, many icon on project page is not good, we can order the icon per context.

Ex: The labels, milstones should be tab at issues page.

**Comment by message** [comment]
First world problems?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
