### ISSUE TITLE
[suggestion] Assigned issues of archived projects are still listed

### ISSUE THREAD

**Issue by patschi** [gitlabhq/gitlabhq#9512]
When archiving a project, the project will be read-only and will be hidden in searches, which is a great idea. But when the project still have issues assigned to people and exactly this project gets archived, the issues still show up on the user`s issues summary page (/dashboard/issues).

Wouldn't it be a great idea to hide these issues from archived projects too? Some issues are e.g. related to some fixes of the code, but they can't commit anything because the project is read-only because it is archived anyway.

**Comment by DamienFontaine** [comment]
+1

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
