### ISSUE TITLE
[UI] Problem with images width in issues description

### ISSUE THREAD

**Issue by bartek5186** [gitlabhq/gitlabhq#9514]
There is a problem, when we drop image into description of the issue, the image have a full width and collide with menu on right side.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
