### ISSUE TITLE
Gitlab clone fails due to ssh issue

### ISSUE THREAD

**Issue by dexterddit** [gitlabhq/gitlabhq#9515]
This is what i get :
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress 
git@git.work.int:user/repo.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly

Is the ssh git connection handled by sshd on the machine on gitlab-shell  or is there somewhere in the config that has setting for the max number of connections at the same time ?

**Comment by stanhu** [comment]
Should be sshd on the machine on gitlab-shell.

Looks you're you're using Jenkins. Are you sure the user has a deploy key or access to clone?

**Comment by dexterddit** [comment]
The user has the key and it`s injected form jenkins and the user has clone access . It`s doesn`t fail all the time it just does this randomly from time to time

**Comment by stanhu** [comment]
Perhaps you can [enable verbose logging](http://stackoverflow.com/questions/25388499/how-can-i-run-git-push-pull-commands-with-ssh-verbose-mode) on both the client and the server to see why the connection is closing? The real question is whether `gitlab-shell` is doing this or sshd itself.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
