### ISSUE TITLE
Mentioning wrong HipChat room throws internal server error 500

### ISSUE THREAD

**Issue by spritle** [gitlabhq/gitlabhq#9529]
HipChat::UnknownRoom (Unknown room: 'mergehub'):” 
app/models/project_services/hipchat_service.rb:60:in 'execute'
app/controllers/projects/services_controller.rb:42:in 'test'

This throw internal server error 500 instead of capturing it gracefully.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
