### ISSUE TITLE
Merge requests use wrong commits for diffing images

### ISSUE THREAD

**Issue by davidfraser** [gitlabhq/gitlabhq#9537]
Merge requests show "old" and "new" images side by side in diffs. However, the "old" image comes from the parent of the HEAD of the merge request, so any changes that didn't happen in the final commit are not shown correctly.

See https://gitlab.com/davidfraser/gitlab-test/merge_requests/1/diffs as an example

**Comment by stanhu** [comment]
Nice catch. For reference, it's the difference between the two images:

[Correct:](https://gitlab.com/davidfraser/gitlab-test/commit/2f63565e7aac07bcdadb654e253078b727143ec4)

![image](https://cloud.githubusercontent.com/assets/963826/9118344/9807dcfa-3c24-11e5-8c38-523d93419971.png)

Incorrect:

![image](https://cloud.githubusercontent.com/assets/963826/9118356/a43596e8-3c24-11e5-94ce-a30603fd7c4a.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
