### ISSUE TITLE
[Info request] GitLab repo use more space than imported repo

### ISSUE THREAD

**Issue by tsumi** [gitlabhq/gitlabhq#9541]
Hi,
i noticed that repos created and populated trough gitlab commit-by-commit use more disk space than repos created on gitlab but imported trough remote add/git push from an existing repo.

For example, gitlab managed repo:
* real data (git clone of all branch): 796Kb
* on server: 2356Kb (about 3 times)

repo imported into Gitlab:
* real data (git clone of all branch): 3776Kb
* on server: 4064Kb (quite the same, some commit was made on gitlab after import)

Is this a sort of bug or an expected behavior (and, in this case, why more space is used?)

Thanks
Best Regards :)

**Comment by tsumi** [comment]
Ok, partially self-responding, doing a ```git gc``` into the repo on server clean up lots of disk space (tried on a copy of a repo, not on the production one for now).
Should i assume that it's only garbage? Is it safe to run ```git gc``` on GitLab repos or it can have some side effect on GitLab appication?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
