### ISSUE TITLE
is gitlab api's user avatar_url relative path ?

### ISSUE THREAD

**Issue by letusfly85** [gitlabhq/gitlabhq#9547]
### sumary 

is gitlab api's user avatar_url relative path ?

Hi, I use gitlab v7.13.0

I use gitlab api and expected for avatar_url with absolute path like below

https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/users.md

However, I got relative path like `"avatar_url":"/uploads/user/avatar/2/hoge.jpg",`

Is this situation right?

### Steps to reproduce

1. generate private token
1. get `$GITLAB_ROOT/users/:id`

### Expected behavior

 `"avatar_url":"https://my.gitlab.com/gitlab/uploads/user/avatar/2/hoge.jpg",`

### Observed behavior

 `"avatar_url":"/uploads/user/avatar/2/hoge.jpg",`

**Comment by stanhu** [comment]
I got an absolute URL. The code that does this:

```
def avatar_url(size = nil)
    if avatar.present?
      [gitlab_config.url, avatar.url].join
    else
      GravatarService.new.execute(email, size)
    end
  end
```

Is it possible `gitlab_config.url` is blank for you? You may need check `gitlab.yml` for the host and port configuration values.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
