### ISSUE TITLE
Group Access owner override

### ISSUE THREAD

**Issue by vkareh** [gitlabhq/gitlabhq#9558]
When adding Developers to a group I owned, I accidentally added my own name: it changed my access level from Owner to Developer.

To reproduce:
1. Create a group, verify that you're the owner
2. Add yourself as a member of the group with a permission other than Owner
3. See that group no longer has an owner

Expected behavior should be to either silently fail to modify the owner's access level, or warn that it cannot be changed, or ensure that at least one other owner exists within the group.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
