### ISSUE TITLE
Gitlab 7.13.5 500 error in services

### ISSUE THREAD

**Issue by foxdalas** [gitlabhq/gitlabhq#9561]
Hi

```
ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'BuildboxService'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Service.inheritance_column to use another column for that information.):
  app/models/project.rb:404:in `find_service'
  app/models/project.rb:391:in `block in build_missing_services'
  app/models/project.rb:385:in `each'
  app/models/project.rb:385:in `build_missing_services'
  app/controllers/projects/services_controller.rb:21:in `index'
```

**Comment by stanhu** [comment]
`BuildboxService` has been renamed `BuildkiteService`. There is a migration in 20150411180045_renaame_buildbox_service.rb` that updates the `services` table this way. Have you run `gitlab-ctl reconfigure`? Otherwise you may want to run the SQL command directly:

```sql
UPDATE services SET type = 'BuildkiteService' WHERE type = 'BuildboxService'
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
