### ISSUE TITLE
dot in project path

### ISSUE THREAD

**Issue by ns3777k** [gitlabhq/gitlabhq#9573]
Hey there, I ran into a problem using API. When I run this:
```
curl -H 'PRIVATE-TOKEN: ***' http://***/api/v3/projects/nikita.safonov%2Fapi-test
```
It gives me:
```json
{"message":"404 Project Not Found"}
```

I decide to rename myself and then got it working:
```
curl -H 'PRIVATE-TOKEN: ***' http://***/api/v3/projects/nsafonov%2Fapi-test
```

Is it a problem with dot or I'm missing something?
Gitlab (7.13.4)
Thanks.

**Comment by stanhu** [comment]
It looks like you found a bug. Thanks. As a workaround, you can use "%2E" as a dot.

There is a proposed fix here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1218

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
