### ISSUE TITLE
Redirect page not exist

### ISSUE THREAD

**Issue by illay1994** [gitlabhq/gitlabhq#9580]
steps to reproduce:
1. Create Project in Group
2. Push Marge Request
3. Go to Person Activity(or Group Ativity)
4. Click on Merge Url(red area)
  and you get status 404

1. Group url http://test.gitlab/groupname
2. Project url http://test.gitlab/groupname/projectname
3. in Red area you view url http://test.gitlab/groupname/p... and redirect http://test.gitlab/groupname/p (but must http://test.gitlab/groupname/projectname)

Details in attachments:
![bugs](https://cloud.githubusercontent.com/assets/10198202/9469822/bfe638ca-4b51-11e5-8f38-6813000cbfe1.png)

System information:
GitLab 7.13.1
GitLab Shell 2.6.3
GitLab API v3
Ruby 2.1.6p336
Rails 4.1.11

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
