### ISSUE TITLE
Reporters are not able to set MR assignee anymore

### ISSUE THREAD

**Issue by Stevko-sk** [gitlabhq/gitlabhq#9585]
We use forking workflow [1] in our Gitlab installation where people for the central repository and create Merge requests from their fork. They are set as reporters for the central project. Until recently they could assign their merge request to appropriate person with higher rights. However, after recent update they cannot change assignee of a Merge request they created. I think they should be able to do it.

This MR seems to be relevant: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1183

[1] http://doc.gitlab.com/ce/workflow/authorization_for_merge_requests.html#forking-workflow

**Comment by Zeboch** [comment]
:+1:

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
