### ISSUE TITLE
Init script broken on FreeBSD

### ISSUE THREAD

**Issue by clorichel** [gitlabhq/gitlabhq#9592]
I'm sorry to say @drunkard commit https://github.com/gitlabhq/gitlabhq/commit/4c5adb702caef0aebe0d10416521e24e68fa0801 broke the init script on FreeBSD.

See https://github.com/gitlabhq/gitlabhq/blob/master/lib/support/init.d/gitlab#L47

Without `-s $shell_path` it works like a charm.
For sure, yes I replaced `shell_path` to `"/usr/local/bin/bash"`

FreeBSD man page for `su` gives the clue : `-s` has nothing to do with a shell choice on FreeBSD...
see https://www.freebsd.org/cgi/man.cgi?query=su&apropos=0&sektion=0&manpath=FreeBSD+10.2-stable&arch=default&format=html

Without altering https://github.com/gitlabhq/gitlabhq/blob/master/lib/support/init.d/gitlab#L47 to remove the `-s $shell_path` part, on FreeBSD you get stuck to git shell with nothing starting :
```
root@host:/usr/home/git/gitlab # service gitlab start
[git@host ~]$
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
