### ISSUE TITLE
Can't comment on binary files in merge requests

### ISSUE THREAD

**Issue by jonathanfoster** [gitlabhq/gitlabhq#9594]
In merge requests, I can't comment on a binary file. It would be nice if I could comment on the file itself. Instead I have to leave a general comment on the entire merge request. For instance, if someone adds a new image to a repo and I don't see any reference to the image anywhere in the source code then I'd comment that the file should be removed.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by shanawarwht** [comment]
![image](https://cloud.githubusercontent.com/assets/25561736/22624635/aab0a294-eba3-11e6-9c50-feada113df31.png)
![image](https://cloud.githubusercontent.com/assets/25561736/22624636/ad507af6-eba3-11e6-8720-270bd60816b9.png)
![image](https://cloud.githubusercontent.com/assets/25561736/22624638/b606ed56-eba3-11e6-973d-1686d0ce5488.png)

**Comment by shanawarwht** [comment]
![image](https://cloud.githubusercontent.com/assets/25561736/22624641/c5373542-eba3-11e6-8cae-d5e3ddbe2881.png)
[
![image](https://cloud.githubusercontent.com/assets/25561736/22624649/e27c09ac-eba3-11e6-9706-1ecaa8f78d71.png)
]([](**[](![image](https://cloud.githubusercontent.com/assets/25561736/22624647/d1a7c418-eba3-11e6-9ca3-5432505ff257.png))**))
