### ISSUE TITLE
ssh is not working properly with relative paths - yet it works when the username is specified twice within the path!

### ISSUE THREAD

**Issue by missmah** [gitlabhq/gitlabhq#9599]
When things fail, GitLab replies that the project does not exist, or that the project was not found. I spent many hours trying all of the existing solutions mentioned online for these symptoms; but, this seems to be a new problem. It started when I updated to 7.14.1 today.

WORKS:
https://server:port/USER/PROJECT.git
> gitlab-shell: executing git command {git-upload-pack /var/opt/gitlab/git-data/repositories/USER/PROJECT.git} for user with key key-3.

WORKS:
git@server:USER/PROJECT.git
> gitlab-shell: executing git command {git-upload-pack /var/opt/gitlab/git-data/repositories/USER/PROJECT.git} for user with key key-3.

BROKEN:
ssh://git@server:USER/PROJECT.git
> gitlab-shell: Access denied for git command {git-receive-pack **'/PROJECT.git'**} by user with key key-3.

WORKS!?:
ssh://git@server:**USER/USER**/PROJECT.git
> gitlab-shell: executing git command {git-upload-pack /var/opt/gitlab/git-data/repositories/USER/PROJECT.git} for user with key key-3.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
