### ISSUE TITLE
New graph (contributors graph)

### ISSUE THREAD

**Issue by MauriceMohlek** [gitlabhq/gitlabhq#9610]
It would be lovely to have a "Lines of code" graph for each user like the GitHub contributors graph.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
