### ISSUE TITLE
Gitlab API - missing parameters for the Gitlab CI service

### ISSUE THREAD

**Issue by mako101** [gitlabhq/gitlabhq#9612]
When creating a Gitlab CI service via API there are no parameters to set the trigger options.

By default both are on which is not always desirable.

I tried using the params from webhooks:

"push_events":false
"tag_push_events":false

But they have had no effect

**Comment by stanhu** [comment]
Indeed. Feel free to send a PR for this. You'll have to update `lib/api/services.rb` to incorporate `supported_events`.

**Comment by mako101** [comment]
Unfortunately I'm not a dev myself, just using your API for scripting.

So wont be able to submit patch to fix this

Thanks

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
