### ISSUE TITLE
UTF8 encoding issue on Merge Request

### ISSUE THREAD

**Issue by mattseymour** [gitlabhq/gitlabhq#9615]
When trying to create a merge request which contains unicode characters in the diff the merge request fails with a 500 error. I have pulled the following from the application log. The error is caused when trying to store the diff into the database.

    ActiveRecord::StatementInvalid (PG::UntranslatableCharacter: ERROR:  character 0xe287a7 of encoding "UTF8" has no equivalent in "LATIN1"
    : UPDATE "merge_request_diffs" SET "st_commits" = $1, "st_diffs" = $2, "state" = $3, "updated_at" = $4 WHERE "merge_request_diffs"."id" = 207):
      app/models/merge_request_diff.rb:142:in `reload_diffs'
      app/models/merge_request_diff.rb:44:in `reload_content'
      app/services/merge_requests/create_service.rb:17:in `execute'
      app/controllers/projects/merge_requests_controller.rb:107:in `create'

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
