### ISSUE TITLE
[API] Search endpoints

### ISSUE THREAD

**Issue by valeriomazzeo** [gitlabhq/gitlabhq#9628]
Many API endpoints are missing the very basic *search* functionality:

* Project Snippets
* Repositories
* Repositories Files
* Commits
* Branches
* Merge Requests
* Issues (only searchable by label, but not title and description)
* Labels
* Milestone
* Notes
* Deploy Keys
* System Hooks
* SSH Keys

**Comment by valeriomazzeo** [comment]
Any feedback on this? @randx @dosire 

Without those endpoints the only way to perform a search on those resources is to download and index them all that is really inefficient.

**Comment by randx** [comment]
@valeriomazzeo makes sense to have it. We are open for merge requests which add basic search functionality to listed items

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
