### ISSUE TITLE
Does gitlabhd support aws region cn-north-1 ?

### ISSUE THREAD

**Issue by William-Sang** [gitlabhq/gitlabhq#9653]
Does gitlabhd support aws region cn-north-1 ?
I try to set aws region as cn-north-1, but there socket error. Can't backup to aws region cn-north-1 in china.

**Comment by stanhu** [comment]
I believe fog-aws added `cn-north-1` via [this commit](https://github.com/fog/fog-aws/commit/ff252c39793f788bc3869d89e08376addbb823c7), but I think GitLab is using an older version of fog at the moment that doesn't have this. I think it would be a simple matter of upgrading Gem versions, but someone would have to test this.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
