### ISSUE TITLE
Push gitlab to CF

### ISSUE THREAD

**Issue by zhangdong89** [gitlabhq/gitlabhq#9656]

**Comment by zhangdong89** [comment]
i want to push gitlab to cloud foundry, but when i clicked the url which is ceated by itself , it shown error 500. please tell me, how to push it to cloud foundry?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
