### ISSUE TITLE
markdown: nested lists should require 2 space, not 4

### ISSUE THREAD

**Issue by Necroskillz** [gitlabhq/gitlabhq#9665]
Gitlab markdown behaves inconsistently for nested lists. for the 2nd level, it's renders correctly with 2 spaces, but then for deeper levels it requires 4 spaces. This breaks lists generated by https://github.com/jsdoc2md/jsdoc-to-markdown a bit.

Example:
source:
```
* level 1
  * level 2
    * level 3
      * level 4
```

result:
![image](https://cloud.githubusercontent.com/assets/346477/10051734/4af16eca-6223-11e5-9642-6f1088f078d6.png)

with 4 spaces for level 3 & 4:
source
```
* level 1
  * level 2
      * level 3
          * level 4
```
result:
![image](https://cloud.githubusercontent.com/assets/346477/10051765/7df0a764-6223-11e5-9d65-6593c67d858a.png)

github renders it correctly with 2 spaces:
* level 1
  * level 2
    * level 3
      * level 4

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by pinkgothic** [comment]
Related gitlab.com issue for lists _containing links_, for those searching for it: https://gitlab.com/gitlab-org/gitlab-ce/issues/18888
