### ISSUE TITLE
"Create Merge Request" button has scrolbar in "Activity" page

### ISSUE THREAD

**Issue by ahmadalli** [gitlabhq/gitlabhq#9668]
![image](https://cloud.githubusercontent.com/assets/2167301/10101099/4d0c46f4-63a3-11e5-8120-3694dff48a1a.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
