### ISSUE TITLE
"Branches" Tab on the Sidebar?

### ISSUE THREAD

**Issue by jordan-wright** [gitlabhq/gitlabhq#9672]
Congrats on the fantastic v8 release!

So, both branches and commits are considered first class citizens in Git. With the motto being to "branch early and branch often", I find myself constantly interfacing with the branches screen.

Unfortunately, it's a bit of a pain to have to always navigate to "Commits" -> "Branches". It's not really intuitive on how to get to the branches page in the first place, and even then it feels like it's just *hidden*.

Has there been any thought into making a "Branches" entry in the left sidebar? I did it in a (probably not the best) way in my own instance that had the label "Branches" with the number of branches to the right of it (similar to "Issues"). This was a **huge** help to my workflow, and I think it would help quite a few other users as well.

Keep up the great work on Gitlab!

**Comment by stanhu** [comment]
Thanks for your suggestion. I think this would make the left sidebar more crowded than it already is; the list is already so long people even miss the "Settings" button because you have to scroll down for it. I have a feeling the GitLab UI experts will not approve of this change. I'm going to close this issue for now unless more users clamor for this change.
