### ISSUE TITLE
Turbolinks broken for repositories with a dot in name

### ISSUE THREAD

**Issue by ninja-** [gitlabhq/gitlabhq#9674]
If a repository name contains a dot and you try to navigate to it, it would refresh the page without turbolinks. It's reproducible for every repo with a dot in URL.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
