### ISSUE TITLE
Cache /gitlab/uploads with expire header

### ISSUE THREAD

**Issue by ninja-** [gitlabhq/gitlabhq#9675]
It lacks an expires header by default so it will download all the avatars etc. every time, it affects loading time

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
