### ISSUE TITLE
Cannot reference snippet from wiki

### ISSUE THREAD

**Issue by epsitec** [gitlabhq/gitlabhq#9676]
I should be able to write:

```md
see [this snippet]($123)
```

from a markdown wiki page entry. However, this does not resolve to the correct URL and instead points to `blob/master/%24123`.

**Comment by Zasch** [comment]
+1
giving snippet-links a name would be really useful

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
