### ISSUE TITLE
Some MySQL tables have wrong collation after upgrade to Gitlab 8

### ISSUE THREAD

**Issue by benkovsk** [gitlabhq/gitlabhq#9685]
After migration to Gitlab 8.0, some tables have collation latin1_swedish_ci, instead of utf8_unicode_ci. For example, table audit_events.

This possibly causes error when logging in:

**Comment by benkovsk** [comment]
Could not authorize you from Ldapmain because "Mysql2::error: incorrect  string value: '\xc5\x99\xc3\xad \xc5...' for column 'details' at row 1:  insert into `audit events` (`author id`, `created at`, `details`,  `entity id`, `entity type`, `type`, `updated at`) values (10,  '2015-10-01 08:46:52', '---\n:with: :ldap\n:target id: 10\n:target type:  user\n:target details: jiří ...\n', 10, 'user', 'securityevent',  '2015-10-01 08:46:52')".

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
