### ISSUE TITLE
gitlab 8.0.0pre branch not found in files.

### ISSUE THREAD

**Issue by tangnan526** [gitlabhq/gitlabhq#9699]
I push a new branch,but I can not find it in files or commits.

**Comment by tangnan526** [comment]
It's ok after flush redis,but the problem still exists when push a new branch.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
