### ISSUE TITLE
Errors in "GitLab Docker images" documentation

### ISSUE THREAD

**Issue by matm** [gitlabhq/gitlabhq#9702]
There are errors in the documentation at http://doc.gitlab.com/omnibus/docker/. How do I submit a patch? Is this doc on github somewhere so I can make a pull request? Thanks.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
