### ISSUE TITLE
MR with fork can mess up upstream project's issues

### ISSUE THREAD

**Issue by roboogle** [gitlabhq/gitlabhq#9704]
## Summary
Accepting MR involving forked project, may wrongly close issues in upstream project.

## Steps to reproduce
Suppose you have project P1 and fork a project P2 out of P1: P1 is upstream, P2 is fork.

Now you work on P2, and fix issue `#1` with a commit C1 whose message contains `Fixes #1`.
Then open a MR of P2 into P1, containing commit C1.
Accepting the MR, will correctly close `P2#1`, but will also close `P1#1` which is wrong as it may be a completely unrelated  issue.

## Expected behaviour
Wrt the previous example, when accepting MR, issue `P2#1` shall be closed, and issue `P1#1` shall be not closed.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
