### ISSUE TITLE
gitlab can not show diffs in chinese

### ISSUE THREAD

**Issue by chengweiv5** [gitlabhq/gitlabhq#9707]
I'm using gitlab 7.9.2 release and generally it works great, however, it sometimes can not show diffs in chinese, like below.

![gitlab-diff-with-chinese](https://cloud.githubusercontent.com/assets/689798/10362939/01a70f3c-6de4-11e5-867e-ab0d5dc48f41.png)

However, I can review the new commit contents in gitlab which show chinese correctly, but only the `Changes` page (generated by a merge request) doesn't work.

It confused me a lot.

**Comment by chengweiv5** [comment]
confirmed on gitlab v8.0.4

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
