### ISSUE TITLE
Responsive design bug : Issue button behind issue list

### ISSUE THREAD

**Issue by M0dM** [gitlabhq/gitlabhq#9708]
Reproduce :
* Use ctrl+maj+m with firefox 
* Gitlab version : GitLab 7.14.3 d321305
![screen shot 2015-10-08 at 13 01 30](https://cloud.githubusercontent.com/assets/1061506/10364775/a2118450-6dbe-11e5-972c-5b745ce892f3.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
