### ISSUE TITLE
guest users can read merge requests

### ISSUE THREAD

**Issue by gordonmleigh** [gitlabhq/gitlabhq#9709]
The whole point of the 'guest' user level is to stop those users having access to the code.  However, they can still view merge requests and even diffs (which are obviously pieces of code).

Is this intended?  What's the rationale?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
