### ISSUE TITLE
Branch/tag dropdown to limit results, manual text entry

### ISSUE THREAD

**Issue by nf-contribute** [gitlabhq/gitlabhq#9710]
Can you please make it so the branch/tag dropdown limits the results? Right now, we have around 15,000 items that appear in the list and it's either rendered in such a complex way through GitLab, or something? It slows down my very fast computer to the point of being non-functional. (More than minutes to render, haven't ever bothered to wait.) Past a few thousand, is it possible to revert to something like a text entry box? (I think GitHub allows text entry on most of these boxes...?) I am running GitLab CE 8.0.2

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
