### ISSUE TITLE
Issue email address not showing who the author is

### ISSUE THREAD

**Issue by dgubb** [gitlabhq/gitlabhq#9711]
I have performed an upgrade from gitlab 7.12.1 to gitlab 7.13.1 and the from address now appears as  

From: Unattended mailbox <no-reply@email.domain>

The from address used to show 

From: Joe Bloggs <no-reply@email.domain>

Is this a bug or has this functionality been removed?

I have noticed that this functionality was added in commit 96dded3ec8401e9832b3888338f37c846bd43583 by Pierre de La Morinerie two years ago

**Comment by Razer6** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the [GitLab.com issue tracker][https://gitlab.com/gitlab-org/gitlab-ce/issues]. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker][https://gitlab.com/gitlab-org/gitlab-ce/issues].
