### ISSUE TITLE
author.email missing in merge request API responses

### ISSUE THREAD

**Issue by cxfinnag** [gitlabhq/gitlabhq#9714]
After upgrading our GitLab installation to 8.0.3 (from 6.2)
GET /projects/:id/merge_requests
No longer returns author.email. 

It is still listed as a returned field in https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/merge_requests.md

**Comment by stanhu** [comment]
I think ae564c97 restricted author e-mails to the admin user only. Perhaps that should have been clarified. I could see a case where public emails may be permitted to be seen by other users.

**Comment by cxfinnag** [comment]
Right. Our gitlab installation is purely company internal, so we'd rather have the email information available.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
