### ISSUE TITLE
Hovering over 'Reopen' button on a closed merge request shows wrong text

### ISSUE THREAD

**Issue by brunhil** [gitlabhq/gitlabhq#9724]
When hovering over the 'Reopen' merge request button on a closed merge request it shows "Close merge request".

![image](https://cloud.githubusercontent.com/assets/2320689/10461139/8d90c5ee-719d-11e5-8489-93121f4c8ce3.png)

Using GitLab Enterprise Edition 8.0.4-ee 5dc6dda

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
