### ISSUE TITLE
Merged merge request shows misleading information in Activity

### ISSUE THREAD

**Issue by brunhil** [gitlabhq/gitlabhq#9725]
After a Merge Request is accepted, the history that shows up in the 'Activity' page is misleading.

See picture below...

![image](https://cloud.githubusercontent.com/assets/2320689/10461543/68dfa146-719f-11e5-82ad-47dcd887c690.png)

The commit sha and message are correct. But the person who pushed, the repo that was pushed to, and the branch are all wrong.

The action that happened was merging from a forked repo into the repo that was forked. 

In the picture...Dev 1 was the person who opened the merge request from **Branch1** in his/her fork into branch **master** in Repo2.

Dev2 was actually the person who accepted the merge request, not Dev1. I would expect it to show that "**Dev2** pushed to branch **master** at **Repo2/master**" Producing the picture below...

![image](https://cloud.githubusercontent.com/assets/2320689/10461684/29212cb8-71a0-11e5-9394-622133a72c12.png)

I am using GitLab Enterprise Edition 8.0.4-ee 5dc6dda.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
