### ISSUE TITLE
[Feature request] Creating branch from issue 

### ISSUE THREAD

**Issue by lottietoday** [gitlabhq/gitlabhq#9726]
Please add functionality to make branch from issue (after click on button)
this feature can be available for user who have assigned task...

for example after clicking on button in issue#7 it will create branch issue-7 and show instruction to checkout it.

**Comment by AlexDubstone** [comment]
+1, I'm totally with you, but I think the official place for feature requests is the forum at:
http://feedback.gitlab.com/forums/176466-general

**Comment by lottietoday** [comment]
ill write it there :) thanks

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
