### ISSUE TITLE
Buttons to open and to pin left drawer at width < 1199px

### ISSUE THREAD

**Issue by kevinlitchfield** [gitlabhq/gitlabhq#9727]
GitLab's left drawer collapses at a breakpoint of width 1199px and can't be reopened. I find this behavior inconvenient (and currently use a userstyle to override it), both because it hides the link text and because it hides badge counts. I'm wondering if the maintainers would be open to a patch that implemented the following features:

- keep the collapse/open buttons for the drawer visible at width < 1199px, which is currently the breakpoint at which they disappear
- a "Pin" button somewhere on the drawer, which would set an option to keep the drawer open until unpinned, similar to how Feedly currently does this

I would be happy to make a PR for this.

**Comment by stanhu** [comment]
Sounds good to me.

**Comment by kevinlitchfield** [comment]
Great! I'll get on that. :smile:

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
