### ISSUE TITLE
[8.0.4] Gitlab CI service not configurable

### ISSUE THREAD

**Issue by avdv** [gitlabhq/gitlabhq#9733]
After upgrading from 7.x the settings for all projects using the Gitlab CI service (project -> settings -> services -> Gitlab CI) are gone and no build is triggered on push and/or tag events.

The page is missing the URL which should be called and the token information.

![1444821957](https://cloud.githubusercontent.com/assets/3471749/10482277/3abab494-7277-11e5-8dc2-da2860434f68.png)

**Comment by axilleas** [comment]
Did you follow the steps outlined [here](https://github.com/gitlabhq/gitlabhq/blob/master/doc/migrate_ci_to_ce/README.md) for the migration?

**Comment by avdv** [comment]
> Did you follow the steps outlined here for the migration?

No. We are not using Gitlab CI. Just the Gitlab CI service hook to push notifications for push events.

The workaround seems to be to use a simple web-hook which does the same thing as the former service hook.. ?!

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
