### ISSUE TITLE
500 error when saving a wiki page with "," or "&" (and others) in title

### ISSUE THREAD

**Issue by Ciki** [gitlabhq/gitlabhq#9736]
similar to #7035 #3318 and others
is there a page with supported whitelist of characters to be used in wiki page title?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
