### ISSUE TITLE
delete branch returns 405 when branch name has "." with gitlab api 'Delete repository branch'

### ISSUE THREAD

**Issue by maxingchi** [gitlabhq/gitlabhq#9745]
* gitlab version:7.8.4
* branch name:'0.0.1'
* gitlab api name
        
        DELETE /projects/:id/repository/branches/:branch
* returns
       
        405 error and empty response

after changing br name to '001', api works

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
