### ISSUE TITLE
Upgrade from 6.5 to 8.0?

### ISSUE THREAD

**Issue by trusktr** [gitlabhq/gitlabhq#9748]
How would I do such a thing? Would I need to go through [all of these](https://github.com/gitlabhq/gitlabhq/tree/master/doc/update) one by one? My GitLab is running on Arch Linux by the way, the [package from AUR](https://aur.archlinux.org/packages/gitlab) at version 6.5.

**Comment by axilleas** [comment]
Ah that's gonna be difficult because much have changed in the PKGUILD till today.

In general yes, you should follow the guides you mentioned, not 1-1 check out the major version bumps to save some time. That said, the PKGBUILD will have to be adopted accordingly each time.

Since the AUR now supports git, check out the revisions on each release [here](https://aur.archlinux.org/cgit/aur.git/log/?h=gitlab). Not all are present but you'll get the idea.

To save the hassle of messing with PKGBUILDs, what I would do is:

1. Migrate your existing installation to a source one
  1. Make a backup
  1. Install source GitLab 6.5
  1. Restore the backup
1. Follow the remaining update guides to the latest GitLab version
1. Make a backup
1. Install the Archlinux package
1. Restore the backup

That's from the top of my head so I may forget something.

**Comment by axilleas** [comment]
Since Archlinux is not officially supported, I would suggest to open a topic in the [forum](https://forum.gitlab.com) and continue there. Or even open a topic in the Archlinux forum and ping me to take part.
