### ISSUE TITLE
broken multibyte characters commit message[8.0 to 8.1 update]

### ISSUE THREAD

**Issue by meke** [gitlabhq/gitlabhq#9774]
Hi
Though updated from 8.0 to 8.1 , it's a multi- byte string will break

* Broken Message
![commit-msg](https://cloud.githubusercontent.com/assets/44907/10728500/c8c62630-7c25-11e5-9787-4f19fc4bc3d2.png)

* No Problem
![commit-msg-ok](https://cloud.githubusercontent.com/assets/44907/10728506/ceed28ec-7c25-11e5-85a8-a10a5b566fe1.png)

It seems to work properly When you revert to this commit

https://github.com/gitlabhq/gitlabhq/commit/a3c6ed5c4650a7c8643e57929a34a219c6a15a8a#diff-30ddd6cd014ef79766cb231f315891ef

**Comment by jvanbaarsen** [comment]
@meke I tried this locally with some japanese I copied from the internet, and its working fine:

![image](https://cloud.githubusercontent.com/assets/1362793/10785686/036583a8-7d66-11e5-8c44-a3d99c7c3c21.png)

Can you paste the exact characters you are trying to use here? That way I can see if any of those is causing issues.

**Comment by jvanbaarsen** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by meke** [comment]
For libxml2 is old CentOS6, it seems this problem occurs
