### ISSUE TITLE
relative_url doesn't work when sign out

### ISSUE THREAD

**Issue by ikaruce** [gitlabhq/gitlabhq#9785]
I just install new gitlab version ( 8.1.2 ) 
I'm very thankful, because there are great feature in new version. 

But, I think there is a bug using relative url. especially when sign out, I go to wrong url. for example,   `www.myserver.com/gitlab`  move to `www.myserver.com/` after sign out. 

Does anyone have experienced this situation?

**Comment by ikaruce** [comment]
I solved this problem by setting ater sign-out path. but I think it's weird.

**Comment by ikaruce** [comment]
It looks like you guys don't care about this problem. I found the reason why move to wrong URL after sign out. 
It was because `After sign out path` setting in admin page. I left that field empty. and GitLab check only that field is nil. 

I hope someday someone will fix it.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
