### ISSUE TITLE
Error 500 when try to change root username

### ISSUE THREAD

**Issue by arnaud-zg** [gitlabhq/gitlabhq#9790]
Hi everyone,
I just installed Gitlab and I would like to change root username, but browser tells me an error 500 when I try to save that. Just below you can see an extract of `gitlab/log/production.log`.

```
Started PATCH "/admin/users/root" for 180.160.2.14 at 2015-10-31 06:15:02 +0100
Processing by Admin::UsersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"name"=>"Name", "username"=>"login", "email"=>"email@domain.eu", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "projects_limit"=>"10000", "can_create_group"=>"1", "skype"=>"", "linkedin"=>"", "twitter"=>"", "website_url"=>""}, "id"=>"root"}
Completed 500 Internal Server Error in 205ms (ActiveRecord: 65.3ms)

Exception (namespace directory cannot be moved):
  app/models/namespace.rb:137:in `move_dir'
  app/models/user.rb:679:in `ensure_namespace_correct'
  app/controllers/admin/users_controller.rb:113:in `block in update'
  app/controllers/admin/users_controller.rb:111:in `update'
```

Sincerely yours

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
