### ISSUE TITLE
No /etc/init.d/gitlab exists

### ISSUE THREAD

**Issue by TotalKrill** [gitlabhq/gitlabhq#9793]
i am using the omnibus package and there is no /etc/init.d/gitlab file on my system. Trying to reinstall the package with apt-get install gitlab-ce --reinstall does not work

neither does doing a apt-get remove --purge gitlab-ce and then reinstalling it.

Could someone provde me with a standard of this file or the steps to recreate them?

Also the apt-get remove --purge does not remove the folders under /opt/gitlab/

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
