### ISSUE TITLE
use custom nginx, everything normal,but pull&push&clone got 502 via "http"(ssh normal)

### ISSUE THREAD

**Issue by steventong** [gitlabhq/gitlabhq#9796]
http://doc.gitlab.com/omnibus/settings/nginx.html#using-an-existing-passengernginx-installation

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
