### ISSUE TITLE
Feature: Trigger build from UI

### ISSUE THREAD

**Issue by jas99** [gitlabhq/gitlabhq#9798]
Trigger build from UI

**Comment by axilleas** [comment]
Can you ellaborate on that? Builds are run on every push and they can be retriggered from the UI.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
