### ISSUE TITLE
Default fixture e-mail (admin@example.com) can't be delivered by default.

### ISSUE THREAD

**Issue by Blackskyliner** [gitlabhq/gitlabhq#9800]
Summary: Default fixture email (admin@example.com) can't be delivered by default.

Steps to reproduce:
 1. Install Gitlab
 2. Run `bundle exec rake gitlab:setup RAILS_ENV=production`
 3. Look in your mail queue for the mail to admin@example.com which can't be delivered

Expected behavior: Some e-mail gets delivered somewhere successfully.
Observed behavior: The e-mail cant be delivered thus hanging in the queue.
Possible fixes: The default (fixture) e-mail should default to root@localhost which will and can always be delivered locally to the root user of the machine.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
