### ISSUE TITLE
Enable shared runner by default?

### ISSUE THREAD

**Issue by mikew** [gitlabhq/gitlabhq#9802]
After adding a `.gitlab-ci.yml` file to a project and pushing it, it does trigger a CI build, but "Enable Shared Runners" defaults to off, resulting in a build just sitting there as Pending. Am I missing something, or does "Enable Shared Runners" need to be enabled in GitLab?

The runner is definitely shared:

![screen shot 2015-11-04 at 11 01 17 am](https://cloud.githubusercontent.com/assets/4729/10941805/6966937c-82e3-11e5-8e87-c776b799dd1a.png)

**Comment by axilleas** [comment]
Either way there has to be a runner already running. An MR to enable by defaults shared runners is here https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1738

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
