### ISSUE TITLE
Feature Request - Integrate Gitlab milestones with Redmine Project versions

### ISSUE THREAD

**Issue by shikarishambu** [gitlabhq/gitlabhq#9806]
We use Gitlab SCM with Redmine for issues/ project management and we have integrated them both. However, it looks like the integration doesn't extend to Gitlab milestones/ Redmine project versions.

It would be nice to have Gitlab milestones pull from Redmine project versions.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
