### ISSUE TITLE
"allow_failure: true" problem with CI badge on root page (when it - projects index page)

### ISSUE THREAD

**Issue by inner-whisper** [gitlabhq/gitlabhq#9815]
Hello!
We've noticed small issue with CI-status label on root page (if it set to "Projects" page):
If we have project with `allow_failure: true` on one of builds (http://doc.gitlab.com/ci/yaml/README.html#jobs), then we will see `running` icon near project's star counter after build has been accomplished (and "allowed to failure" build failed).
![screen shot 2015-11-09 at 0 06 35](https://cloud.githubusercontent.com/assets/456066/11022707/444ee530-8676-11e5-97d0-da3ec862081d.png)

Simultaneously, directly on `/dashboard/projects` page we see `success` icon.
![screen shot 2015-11-09 at 0 06 25](https://cloud.githubusercontent.com/assets/456066/11022705/4101924c-8676-11e5-87ab-493ce1d8a7d7.png)

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
