### ISSUE TITLE
Committing on the web interface fails

### ISSUE THREAD

**Issue by lorenz** [gitlabhq/gitlabhq#9816]
When I commit changes on the web interface the request times out and after a reload I see the error message `Commit was rejected by pre-receive hook`. I'm using `sameersbn/gitlab` as a container with a Nginx reverse proxy.

Component versions:
GitLab 8.1.3
GitLab Shell 2.6.5
GitLab API v3
Ruby 2.1.7p400
Rails 4.1.12

Thanks for looking into this!

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
