### ISSUE TITLE
gitattributes doesn't work

### ISSUE THREAD

**Issue by Alexhha** [gitlabhq/gitlabhq#9817]
Hello,
Currently I'm using Gitlab 8.0.4 on CentOS 6. And I have encountered with EOL issue. So I'm trying to solve the issue via .gitattributes file with the following content
```
# cat .gitattributes
*.sln text eol=lf
```

But it seems doesn't work.

```
# git clone ssh://git@gitlab.example.net:2222/eol/test.git
Cloning into '.'...
remote: Counting objects: 20404, done.
remote: Compressing objects: 100% (5060/5060), done.
remote: Total 20404 (delta 15085), reused 20316 (delta 15002)
Receiving objects: 100% (20404/20404), 28.55 MiB | 20.54 MiB/s, done.
Resolving deltas: 100% (15085/15085), done.
Checking connectivity... done.
```

```
# cat -A test.sln
Microsoft Visual Studio Solution File, Format Version 12.00^M$
# Visual Studio 2013^M$
VisualStudioVersion = 12.0.21005.1^M$
MinimumVisualStudioVersion = 10.0.40219.1^M$
```
Why is still using windows EOL instead of linux? Did I miss something?

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
