### ISSUE TITLE
Failed to connect to repository : Remote host closed connection during handshake

### ISSUE THREAD

**Issue by sharonfrancis91** [gitlabhq/gitlabhq#9900]
On entering Git repo URL im getting error
Failed to connect to repository : Remote host closed connection during handshake.
![git](https://cloud.githubusercontent.com/assets/10846753/11707551/fa6c08ca-9f2b-11e5-8b89-7235f6f20cd4.png)

**Comment by stanhu** [comment]
I suspect this is an SSL issue, either because the two endpoints can't agree on a compatible cipher/TLS mode or the SSL certificate bundle is not correct. You may want to read this document:

https://blogs.oracle.com/java-platform-group/entry/diagnosing_tls_ssl_and_https

As I don't think this is a GitLab-specific bug, I'm closing this issue for now.
