### ISSUE TITLE
Groups prevents to create new account

### ISSUE THREAD

**Issue by antogerva** [gitlabhq/gitlabhq#9910]
Hello,

A friend of mine imported a project in gitlab from github with my username as group/organization, hence it created a new group on gitlab available here:
https://gitlab.com/groups/antogerva

The problem is that now, I can't register/login to gitlab at all as a new user with the following url:
https://gitlab.com/users/sign_in
This is what I get when I attempt to "login" with my github account:

```
Error 422
Try logging in using your email
Try logging in using your username
If you have forgotten your password, try recovering it using Password recovery
If none of the options work, try contacting the GitLab administrator.
```

I asked my friend to delete the project, but it look like the problem still remain.

And attempting to reset my password with my email(antogerva AT gmail DOT com) doesn't work either, since I believe he imported the project before I register.

**Comment by stanhu** [comment]
I've seen this before. The problem is that there is an account with your e-mail address but no GitHub credentials, so GitLab complains. There is an [outstanding bug for this issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/728), although I'm not sure the best way to resolve it because not all OAuth2 providers report verified e-mail addresses.

I'm not sure why the password reset isn't working; are you getting an e-mail at least?

**Comment by antogerva** [comment]
No... nothing.
``If your email address exists in our database, you will receive a password recovery link at your email address in a few minutes.``

The best thing I could think of at the moment would be to destroy the group/account(can my friend do it?), so I can sign up back with my email only.

**Comment by stanhu** [comment]
Is it possible the e-mail system on the site isn't working, or that the e-mail is going to spam?

**Comment by antogerva** [comment]
I don't known for the site not working, but I didn't get mail from gitlab in my spam inbox.

So at this point, how can I report this issue the gitlab site admin?

**Comment by stanhu** [comment]
Oh, I didn't realize you were speaking specifically about gitlab.com; the e-mail system works fine there.

It sounds like the problem is that your username is already a group, and when GitLab attempts to map your account to it fails.

@dblessing, can you see if the database contains this user's email address and/or group name?

**Comment by antogerva** [comment]
I hate to bump this issue again, but how hard it is to just delete the following group https://gitlab.com/groups/antogerva
So I can finally register to your website with my OWN Github username.
...Thanks
