### ISSUE TITLE
if milestone's title has more than 2 “.”  when show it will return 404 page

### ISSUE THREAD

**Issue by daiyu** [gitlabhq/gitlabhq#9921]
for example,i create milestones:
"v-0.1.0-debug"
"yes"
"wox-sdf"
"3.14 "
"3.14.5"
"3.14.15.926"

result:
http://mydomain/dashboard/milestones/v-0.1.0-debug?title=v-0.1.0-debug
return 404 page;

http://mydomain/dashboard/milestones/yes?title=yes
return ok;

http://mydomain/dashboard/milestones/wox-sdf?title=wox-sdf
return ok;

http://mydomain/dashboard/milestones/3.14?title=3.14
return ok;

http://mydomain/dashboard/milestones/3.14.5?title=3.14.5
return 404 page;

http://mydomain/dashboard/milestones/3.14.15.926?title=3.14.15.926"
return 404 page;

Environment:
ubuntu 14.04
docker 1.9.1
docker images :  sameersbn/docker-gitlab（gitlab:8.2.3 ）  with docker-compse
docker images:  jwilder/nginx-proxy

**Comment by stanhu** [comment]
This should be fixed via https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2182.

**Comment by wataru-chocola** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2182 looks a patch for different problem.
This may be due to inconsistency of constraints for milestone_id in `route.rb`.

In dashboard area, milestone id has no constraints, so it will be not permitted to contain `.`.

```ruby
  resource :dashboard, controller: 'dashboard', only: [] do
    get :issues
    get :merge_requests
    get :activity

    scope module: :dashboard do
      resources :milestones, only: [:index, :show]
```

But in other area, milestone id can contain any characters except `/`.

```ruby
      resources :milestones, constraints: { id: /[^\/]+/ }, only: [:index, :show, :update, :new, :create]
```
